# Final Grammar–KT dataset results

This read-only notebook takes a completed Grammar–KT data-folder path and displays the retained result of every pipeline stage as pandas tables. Edit `DATA_FOLDER` below or set the `GRAMMAR_KT_DATA_FOLDER` environment variable before execution. Relative paths are resolved from the repository root.

Large learner-event and KT-prediction artifacts are summarized and sampled rather than printed in full. Raw source, canonical, item, fold, KC, and metric tables are shown completely at the default row limit. Private simulator truth and superseded pre-curation artifacts are deliberately excluded.

In [1]:
import os

DATA_FOLDER = os.environ.get('GRAMMAR_KT_DATA_FOLDER', 'data/grammar_kt_medium_v1')
TABLE_ROW_LIMIT = 200
EVENT_SAMPLE_ROWS = 20
PREDICTION_SAMPLE_ROWS_PER_TECHNIQUE = 8

## 0. Load and verify the completed dataset

The artifact inventory is the notebook's input contract. Missing final-stage artifacts fail immediately instead of silently producing a partial result.

In [2]:
import json
from pathlib import Path

import pandas as pd
import yaml
from IPython.display import Markdown, display

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_colwidth', 120)
pd.set_option('display.width', 180)

cwd = Path.cwd().resolve()
ROOT = next(
    (candidate for candidate in (cwd, *cwd.parents) if (candidate / 'modules').is_dir()),
    cwd,
)
folder = Path(DATA_FOLDER).expanduser()
DATA_DIR = (folder if folder.is_absolute() else ROOT / folder).resolve()

def read_json(relative_path):
    return json.loads((DATA_DIR / relative_path).read_text(encoding='utf-8'))

def read_jsonl(relative_path, *, nrows=None):
    return pd.read_json(DATA_DIR / relative_path, lines=True, compression='infer', nrows=nrows)

def read_yaml(relative_path):
    with (DATA_DIR / relative_path).open(encoding='utf-8') as handle:
        return yaml.safe_load(handle)

def compact(value):
    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return value

STAGE_TABLES = {}

def show_table(title, frame, *, limit=TABLE_ROW_LIMIT):
    frame = frame.reset_index(drop=True).copy()
    STAGE_TABLES[title] = frame
    display(Markdown(f'**{title}** — {len(frame):,} row(s)'))
    display(frame.head(limit))
    return frame

artifact_spec = [
    ('metadata', 'manifest.json'),
    ('metadata', 'finalization_manifest.json'),
    ('source', 'source/descriptors.jsonl'),
    ('normalisation', 'normalisation/mappings.jsonl'),
    ('canonicalisation', 'canonical/cells.jsonl'),
    ('canonicalisation', 'canonical/source_cell_relations.jsonl'),
    ('item generation', 'items/generation_attempts.jsonl'),
    ('item generation', 'items/candidates.jsonl'),
    ('item validation', 'items/curated_validation.jsonl'),
    ('fixed item bank', 'items/selected_bank.jsonl'),
    ('grammar fold', 'fold/assignments.jsonl'),
    ('KC candidates', 'kc/candidate_inventory.json'),
    ('learner evidence', 'simulation/events.jsonl.gz'),
    ('KC selection', 'kc/selection_trace.json'),
    ('KC stability', 'kc/selection_stability.json'),
    ('projection', 'kc/projections/automated.jsonl'),
    ('Q-matrix', 'kc/q_matrices/automated.csv'),
    ('KT', 'kt/automated/predictions.jsonl.gz'),
    ('evaluation', 'evaluation/automated/results.json'),
    ('uncertainty', 'evaluation/paired_logistic.json'),
]
artifact_inventory = pd.DataFrame([
    {
        'stage': stage,
        'relative_path': relative_path,
        'exists': (DATA_DIR / relative_path).is_file(),
        'size_bytes': (DATA_DIR / relative_path).stat().st_size if (DATA_DIR / relative_path).is_file() else pd.NA,
    }
    for stage, relative_path in artifact_spec
])
missing = artifact_inventory.loc[~artifact_inventory['exists'], 'relative_path'].tolist()
if missing:
    raise FileNotFoundError(f'Incomplete Grammar–KT data folder {DATA_DIR}: missing {missing}')

pipeline_index = pd.DataFrame([
    {'stage': 1, 'name': 'Typed grammar source', 'principal_artifact': 'source/descriptors.jsonl', 'scientific boundary': 'resource-specific evidence'},
    {'stage': 2, 'name': 'Normalisation', 'principal_artifact': 'normalisation/mappings.jsonl', 'scientific boundary': 'constrained source → canonical proposals'},
    {'stage': 3, 'name': 'Canonicalisation', 'principal_artifact': 'canonical/cells.jsonl', 'scientific boundary': 'deduplicated GrammarCells'},
    {'stage': 4, 'name': 'Item generation', 'principal_artifact': 'items/candidates.jsonl', 'scientific boundary': 'no fold, outcome, KC, or KT input'},
    {'stage': 5, 'name': 'Validation and fixed bank', 'principal_artifact': 'items/selected_bank.jsonl', 'scientific boundary': 'independent judgments before learner evidence'},
    {'stage': 6, 'name': 'Semantic grammar fold', 'principal_artifact': 'fold/assignments.jsonl', 'scientific boundary': 'outcome-free grammar regimes'},
    {'stage': 7, 'name': 'KC candidate generation', 'principal_artifact': 'kc/candidate_inventory.json', 'scientific boundary': 'development grammar and fixed items only'},
    {'stage': 8, 'name': 'Learner evidence', 'principal_artifact': 'simulation/events.jsonl.gz', 'scientific boundary': 'development acquisition, then frozen probes'},
    {'stage': 9, 'name': 'Automated KC selection', 'principal_artifact': 'kc/selection_trace.json', 'scientific boundary': 'development train/validation outcomes only'},
    {'stage': 10, 'name': 'Frozen projection / Q-matrix', 'principal_artifact': 'kc/q_matrices/automated.csv', 'scientific boundary': 'selected policy frozen before holdout projection'},
    {'stage': 11, 'name': 'Knowledge tracing', 'principal_artifact': 'kt/*/predictions.jsonl.gz', 'scientific boundary': 'identical event stream across representations'},
    {'stage': 12, 'name': 'Evaluation and uncertainty', 'principal_artifact': 'evaluation/*/results.json', 'scientific boundary': 'held-out probes and learner-paired intervals'},
])

show_table('Resolved input', pd.DataFrame([{'DATA_FOLDER': str(DATA_DIR), 'exists': DATA_DIR.is_dir()}]))
show_table('Required artifact inventory', artifact_inventory)
show_table('Pipeline stage index', pipeline_index)

**Resolved input** — 1 row(s)

                                                   DATA_FOLDER  exists
0  /home/abdullah/grammar_kt_harness/data/grammar_kt_medium_v1    True

**Required artifact inventory** — 20 row(s)

               stage                          relative_path  exists  size_bytes
0           metadata                          manifest.json    True        7998
1           metadata             finalization_manifest.json    True        2663
2             source               source/descriptors.jsonl    True       76932
3      normalisation           normalisation/mappings.jsonl    True       37015
4   canonicalisation                  canonical/cells.jsonl    True        6029
5   canonicalisation  canonical/source_cell_relations.jsonl    True        6297
6    item generation        items/generation_attempts.jsonl    True       29521
7    item generation                 items/candidates.jsonl    True       39630
8    item validation         items/curated_validation.jsonl    True      118099
9    fixed item bank              items/selected_bank.jsonl    True       40763
10      grammar fold                 fold/assignments.jsonl    True        9203
11     KC candidates            kc/candidate_inventory.json    True      123503
12  learner evidence             simulation/events.jsonl.gz    True     1714872
13      KC selection                kc/selection_trace.json    True       16959
14      KC stability            kc/selection_stability.json    True       62657
15        projection         kc/projections/automated.jsonl    True        5322
16          Q-matrix            kc/q_matrices/automated.csv    True        2231
17                KT      kt/automated/predictions.jsonl.gz    True     7605964
18        evaluation      evaluation/automated/results.json    True        6021
19       uncertainty        evaluation/paired_logistic.json    True       15540

**Pipeline stage index** — 12 row(s)

    stage                          name            principal_artifact                               scientific boundary
0       1          Typed grammar source      source/descriptors.jsonl                        resource-specific evidence
1       2                 Normalisation  normalisation/mappings.jsonl          constrained source → canonical proposals
2       3              Canonicalisation         canonical/cells.jsonl                         deduplicated GrammarCells
3       4               Item generation        items/candidates.jsonl                 no fold, outcome, KC, or KT input
4       5     Validation and fixed bank     items/selected_bank.jsonl     independent judgments before learner evidence
5       6         Semantic grammar fold        fold/assignments.jsonl                      outcome-free grammar regimes
6       7       KC candidate generation   kc/candidate_inventory.json          development grammar and fixed items only
7       8              Learner evidence    simulation/events.jsonl.gz       development acquisition, then frozen probes
8       9        Automated KC selection       kc/selection_trace.json        development train/validation outcomes only
9      10  Frozen projection / Q-matrix   kc/q_matrices/automated.csv  selected policy frozen before holdout projection
10     11             Knowledge tracing     kt/*/predictions.jsonl.gz     identical event stream across representations
11     12    Evaluation and uncertainty     evaluation/*/results.json      held-out probes and learner-paired intervals

    stage                          name            principal_artifact                               scientific boundary
0       1          Typed grammar source      source/descriptors.jsonl                        resource-specific evidence
1       2                 Normalisation  normalisation/mappings.jsonl          constrained source → canonical proposals
2       3              Canonicalisation         canonical/cells.jsonl                         deduplicated GrammarCells
3       4               Item generation        items/candidates.jsonl                 no fold, outcome, KC, or KT input
4       5     Validation and fixed bank     items/selected_bank.jsonl     independent judgments before learner evidence
5       6         Semantic grammar fold        fold/assignments.jsonl                      outcome-free grammar regimes
6       7       KC candidate generation   kc/candidate_inventory.json          development grammar and fixed items only
7       8              Learner evidence    simulation/events.jsonl.gz       development acquisition, then frozen probes
8       9        Automated KC selection       kc/selection_trace.json        development train/validation outcomes only
9      10  Frozen projection / Q-matrix   kc/q_matrices/automated.csv  selected policy frozen before holdout projection
10     11             Knowledge tracing     kt/*/predictions.jsonl.gz     identical event stream across representations
11     12    Evaluation and uncertainty     evaluation/*/results.json      held-out probes and learner-paired intervals

In [3]:
manifest = read_json('manifest.json')
finalization = read_json('finalization_manifest.json')

dataset_overview = pd.DataFrame([{
    'dataset_id': finalization['dataset_id'],
    'item_bank_status': manifest['status'],
    'downstream_status': finalization['status'],
    'source_descriptors': manifest['static_summary']['descriptors'],
    'canonical_cells': finalization['scale']['cells'],
    'selected_items': finalization['scale']['selected_items'],
    'learners': finalization['scale']['learners'],
    'events': finalization['scale']['events'],
    'simulation_seed': finalization['simulation']['seed'],
    'latent_world': finalization['simulation']['world_id'],
    'KC_candidate_design': finalization['kc']['candidate_design_id'],
    'KC_selection_method': finalization['kc']['selection_id'],
    'KT_protocol': finalization['kt_protocol_id'],
    'evaluation_protocol': finalization['evaluation_protocol_id'],
}])
model_table = pd.DataFrame([
    {'role': role, 'model_or_source': model}
    for role, model in manifest['models'].items()
])
show_table('Final dataset overview', dataset_overview)
show_table('Model settings retained in the dataset', model_table)

**Final dataset overview** — 1 row(s)

,dataset_id,item_bank_status,downstream_status,source_descriptors,canonical_cells,selected_items,learners,events,simulation_seed,latent_world,KC_candidate_design,KC_selection_method,KT_protocol,evaluation_protocol
0,grammar_kt_medium_v1,fixed_item_bank_complete,downstream_finalized,139,24,44,1000,204000,20260827,phase4_mixed_v1,schema_structural_candidates_v1,forward_predictive_parsimony_v1,simple_online_kt_v1,grammar_kt_evaluation_v1

**Model settings retained in the dataset** — 4 row(s)

               role                           model_or_source
0     normalisation  retained gpt-5.6-sol, medium, 2026-08-20
1        generation                               gpt-5.6-sol
2        validation                             gpt-5.6-terra
3  reasoning_effort                                    medium

               role                           model_or_source
0     normalisation  retained gpt-5.6-sol, medium, 2026-08-20
1        generation                               gpt-5.6-sol
2        validation                             gpt-5.6-terra
3  reasoning_effort                                    medium

## 1. Typed grammar source

The source table contains the retained English Grammar Profile descriptors. Examples remain evidence attached to source records; they are not learner items.

In [4]:
source_rows = read_jsonl('source/descriptors.jsonl')
source_display = source_rows.copy()
source_display['example_count'] = source_display['examples'].map(len)
source_display['examples'] = source_display['examples'].map(compact)
source_group_counts = pd.concat([
    source_rows.groupby('cefr', dropna=False).size().rename('descriptors').reset_index().rename(columns={'cefr': 'value'}).assign(grouping='CEFR'),
    source_rows.groupby('supercategory', dropna=False).size().rename('descriptors').reset_index().rename(columns={'supercategory': 'value'}).assign(grouping='supercategory'),
    source_rows.groupby('subcategory', dropna=False).size().rename('descriptors').reset_index().rename(columns={'subcategory': 'value'}).assign(grouping='subcategory'),
], ignore_index=True)[['grouping', 'value', 'descriptors']]
source_summary = pd.DataFrame([{
    'descriptors': len(source_rows),
    'unique_source_ids': source_rows['source_id'].nunique(),
    'CEFR_levels': source_rows['cefr'].nunique(),
    'supercategories': source_rows['supercategory'].nunique(),
    'subcategories': source_rows['subcategory'].nunique(),
    'source_examples': source_rows['examples'].map(len).sum(),
}])
show_table('Source summary', source_summary)
show_table('Source coverage by declared grouping', source_group_counts.sort_values(['grouping', 'descriptors', 'value'], ascending=[True, False, True]))
show_table('Typed source descriptors', source_display)

**Source summary** — 1 row(s)

   descriptors  unique_source_ids  CEFR_levels  supercategories  subcategories  source_examples
0          139                139            6                8             29              392

**Source coverage by declared grouping** — 43 row(s)

         grouping                       value  descriptors
0            CEFR                          A2           63
1            CEFR                          B1           38
2            CEFR                          A1           18
3            CEFR                          B2           16
4            CEFR                          C2            3
5            CEFR                          C1            1
6     subcategory              passives: form           16
7     subcategory                 imperatives           10
8     subcategory              interrogatives           10
9     subcategory              present simple            9
10    subcategory                 past simple            8
11    subcategory             past continuous            7
12    subcategory         past perfect simple            7
13    subcategory          present continuous            7
14    subcategory     past perfect continuous            6
15    subcategory      present perfect simple            6
16    subcategory                    negation            5
17    subcategory  present perfect continuous            5
18    subcategory                         wh-            5
19    subcategory                         can            3
20    subcategory                       could            3
21    subcategory                         may            3
22    subcategory                       might            3
23    subcategory                        must            3
24    subcategory                       shall            3
25    subcategory                      should            3
26    subcategory                        tags            3
27    subcategory                        will            3
28    subcategory                       would            3
29    subcategory                        dare            2
30    subcategory                      yes/no            2
31    subcategory                 conditional            1
32    subcategory                 declarative            1
33    subcategory                get and have            1
34    subcategory                       types            1
35  supercategory                        PAST           39
36  supercategory                    MODALITY           29
37  supercategory                     CLAUSES           22
38  supercategory                    PASSIVES           17
39  supercategory                     PRESENT           16
40  supercategory                   QUESTIONS           10
41  supercategory                    NEGATION            5
42  supercategory                       VERBS            1

**Typed source descriptors** — 139 row(s)

,source_id,supercategory,subcategory,guideword,can_do,examples,cefr,example_count
0,1741163708336x930002080700909000,CLAUSES,interrogatives,FORM: AFFIRMATIVE INTERROGATIVE,Can form interrogative clauses ('yes/no' forms) of main lexical verbs with auxiliary 'do'.,"[""Do you remember Julie? (Brazil; A2 WAYSTAGE; 2004; Portuguese; Pass)"", ""Did you buy a new mobile phone? (Spain; A2...",A2,2
1,1741163708343x587422418001030500,CLAUSES,interrogatives,"FORM: 'WH-' INTERROGATIVE, SUBJECT","Can form questions with a 'wh-' word as subject, without an auxiliary verb.","[""What happened? (Spanish - Latin American, B1 THRESHOLD)"", ""Who cares? (Spanish - Latin American, B1 THRESHOLD)"", ""...",B1,3
2,1741163715033x199281404596736400,QUESTIONS,yes/no,FORM: LEXICAL VERBS WITH 'DO',Can use auxiliary 'do' + subject + main verb to form 'yes/no' questions.,"[""My favourite song is 'Viva la vida'. Do you know it? (Spain; A2 WAYSTAGE; 2009; Spanish - European; Pass)"", ""My be...",A2,4
3,1741163715031x898125206259626100,QUESTIONS,wh-,FORM: MAIN VERB 'BE',Can use 'wh-'words + main verb 'be' + subject to form 'wh-' questions.,"[""How was your dinner yesterday? (Mexico; A2 WAYSTAGE; 2009; Spanish - Latin American; Pass)"", ""How are you, my frie...",A2,3
4,1741163708330x678606711578176000,CLAUSES,declarative,"FORM/USE: AUXILIARY 'DO', FOR EMPHASIS","Can use the auxiliary verb 'do' in an affirmative declarative clause, for emphasis and affirmation.","[""Yes, I do have a favorite restaurant. (Mexico; B1 THRESHOLD; 2005; Spanish - Latin American; Pass)"", ""I do miss yo...",B1,4
...,...,...,...,...,...,...,...,...
134,1741163710395x413989918547746700,MODALITY,dare,FORM: NEGATIVE,Can use negative form dare not and daren't + infinitive without to.,"[""[talking about a restaurant] But many local people dare not go to Lily, because it is too expensive. (Taiwan; B2 V...",B2,1
135,1741163710395x580382123224487700,MODALITY,dare,FORM: AFFIRMATIVE,Can use affirmative form dare + infinitive without to.,"[""I can cook if you dare eat it! (Taiwan; B2 VANTAGE; 2001; Chinese; Pass)""]",B2,1
136,1741163712056x895221609473611600,PASSIVES,get and have,FORM: 'GET' + '-ED',Can form the 'get'-passive with a range of forms of 'get' + past participles.,"[""[talking about a mirror] I bought it because mine got broken, so I need it to see myself in it. (Mexico; B1 THRESH...",B1,5
137,1741163715620x161645047931569860,CLAUSES,conditional,"FORM/USE: PRESENT SIMPLE 'IF' CLAUSE + MODAL, FUTURE, POSSIBLE OUTCOME","Can use 'if' + present simple to introduce a possible future condition, with modal verbs in the main clause, to talk...","[""I think that it would be very good if you start going to the gym or you start cycling. (Colombia; B1 THRESHOLD; 20...",B1,3
138,1741163713633x978808878460501800,PRESENT,present simple,FORM: INDIRECT QUESTIONS,"Can form indirect questions with 'Do you know' + 'how', 'where', 'why', or 'what …?'","[""Do you know how to get to my house? (Key English Test, A2, Spanish)"", ""Do you know which present I like best? (Key...",A2,2

,source_id,supercategory,subcategory,guideword,can_do,examples,cefr,example_count
0,1741163708336x930002080700909000,CLAUSES,interrogatives,FORM: AFFIRMATIVE INTERROGATIVE,Can form interrogative clauses ('yes/no' forms) of main lexical verbs with auxiliary 'do'.,"[""Do you remember Julie? (Brazil; A2 WAYSTAGE; 2004; Portuguese; Pass)"", ""Did you buy a new mobile phone? (Spain; A2...",A2,2
1,1741163708343x587422418001030500,CLAUSES,interrogatives,"FORM: 'WH-' INTERROGATIVE, SUBJECT","Can form questions with a 'wh-' word as subject, without an auxiliary verb.","[""What happened? (Spanish - Latin American, B1 THRESHOLD)"", ""Who cares? (Spanish - Latin American, B1 THRESHOLD)"", ""...",B1,3
2,1741163715033x199281404596736400,QUESTIONS,yes/no,FORM: LEXICAL VERBS WITH 'DO',Can use auxiliary 'do' + subject + main verb to form 'yes/no' questions.,"[""My favourite song is 'Viva la vida'. Do you know it? (Spain; A2 WAYSTAGE; 2009; Spanish - European; Pass)"", ""My be...",A2,4
3,1741163715031x898125206259626100,QUESTIONS,wh-,FORM: MAIN VERB 'BE',Can use 'wh-'words + main verb 'be' + subject to form 'wh-' questions.,"[""How was your dinner yesterday? (Mexico; A2 WAYSTAGE; 2009; Spanish - Latin American; Pass)"", ""How are you, my frie...",A2,3
4,1741163708330x678606711578176000,CLAUSES,declarative,"FORM/USE: AUXILIARY 'DO', FOR EMPHASIS","Can use the auxiliary verb 'do' in an affirmative declarative clause, for emphasis and affirmation.","[""Yes, I do have a favorite restaurant. (Mexico; B1 THRESHOLD; 2005; Spanish - Latin American; Pass)"", ""I do miss yo...",B1,4
...,...,...,...,...,...,...,...,...
134,1741163710395x413989918547746700,MODALITY,dare,FORM: NEGATIVE,Can use negative form dare not and daren't + infinitive without to.,"[""[talking about a restaurant] But many local people dare not go to Lily, because it is too expensive. (Taiwan; B2 V...",B2,1
135,1741163710395x580382123224487700,MODALITY,dare,FORM: AFFIRMATIVE,Can use affirmative form dare + infinitive without to.,"[""I can cook if you dare eat it! (Taiwan; B2 VANTAGE; 2001; Chinese; Pass)""]",B2,1
136,1741163712056x895221609473611600,PASSIVES,get and have,FORM: 'GET' + '-ED',Can form the 'get'-passive with a range of forms of 'get' + past participles.,"[""[talking about a mirror] I bought it because mine got broken, so I need it to see myself in it. (Mexico; B1 THRESH...",B1,5
137,1741163715620x161645047931569860,CLAUSES,conditional,"FORM/USE: PRESENT SIMPLE 'IF' CLAUSE + MODAL, FUTURE, POSSIBLE OUTCOME","Can use 'if' + present simple to introduce a possible future condition, with modal verbs in the main clause, to talk...","[""I think that it would be very good if you start going to the gym or you start cycling. (Colombia; B1 THRESHOLD; 20...",B1,3
138,1741163713633x978808878460501800,PRESENT,present simple,FORM: INDIRECT QUESTIONS,"Can form indirect questions with 'Do you know' + 'how', 'where', 'why', or 'what …?'","[""Do you know how to get to my house? (Key English Test, A2, Spanish)"", ""Do you know which present I like best? (Key...",A2,2

## 2. Resource-specific normalisation

Only `complete` mappings contribute to the final canonical inventory. Partial rows may contain provisional cells, so the tables keep provisional output distinct from accepted source→cell evidence.

In [5]:
mapping_rows = read_jsonl('normalisation/mappings.jsonl')
mapping_table = mapping_rows[['source_id', 'result', 'cells', 'phase2_eligible', 'note']].copy()
mapping_table['provisional_cell_count'] = mapping_table['cells'].map(len)
mapping_table['accepted_for_canonicalisation'] = mapping_table['result'].eq('complete')
mapping_table['phase2_eligible'] = mapping_table['phase2_eligible'].map(compact)
mapping_table['cells'] = mapping_table['cells'].map(compact)
normalisation_funnel = mapping_rows.groupby('result', dropna=False).agg(
    descriptors=('source_id', 'size'),
    provisional_cells=('cells', lambda values: sum(len(value) for value in values)),
).reset_index()
normalisation_funnel['descriptor_share'] = normalisation_funnel['descriptors'] / len(mapping_rows)

complete_exploded = mapping_rows.loc[mapping_rows['result'].eq('complete'), ['source_id', 'cells']].explode('cells').dropna(subset=['cells'])
accepted_normalised_cells = pd.concat([
    complete_exploded[['source_id']].reset_index(drop=True),
    pd.json_normalize(complete_exploded['cells']).reset_index(drop=True),
], axis=1)
phase2_rows = mapping_rows[['source_id', 'phase2_eligible']].explode('phase2_eligible').dropna(subset=['phase2_eligible'])
phase2_summary = phase2_rows.groupby('phase2_eligible').agg(descriptors=('source_id', 'nunique')).reset_index()
show_table('Normalisation result funnel', normalisation_funnel.sort_values('descriptors', ascending=False))
show_table('Phase-2 eligibility by unresolved dimension', phase2_summary)
show_table('All normalisation mappings', mapping_table)
show_table('Accepted complete source→feature tuples', accepted_normalised_cells)

**Normalisation result funnel** — 4 row(s)

         result  descriptors  provisional_cells  descriptor_share
0       partial           77                 86          0.553957
1      complete           44                 48          0.316547
2  out_of_scope           16                  0          0.115108
3    unresolved            2                  0          0.014388

**Phase-2 eligibility by unresolved dimension** — 1 row(s)

  phase2_eligible  descriptors
0           tense            9

**All normalisation mappings** — 139 row(s)

,source_id,result,cells,phase2_eligible,note,provisional_cell_count,accepted_for_canonicalisation
0,1741163708336x930002080700909000,complete,"[{""aspect"": ""none"", ""clause"": ""polar_question"", ""modal"": ""none"", ""polarity"": ""positive"", ""tense"": ""present"", ""voice""...","[""tense""]",phase2 eligible: tense,2,True
1,1741163708343x587422418001030500,partial,"[{""aspect"": ""none"", ""clause"": ""subject_wh_question"", ""modal"": ""none"", ""polarity"": null, ""tense"": ""present"", ""voice"":...","[""tense""]",phase2 eligible: tense,2,False
2,1741163715033x199281404596736400,partial,"[{""aspect"": ""none"", ""clause"": ""polar_question"", ""modal"": ""none"", ""polarity"": null, ""tense"": ""present"", ""voice"": ""act...","[""tense""]",phase2 eligible: tense,2,False
3,1741163715031x898125206259626100,partial,"[{""aspect"": ""none"", ""clause"": [""subject_wh_question"", ""non_subject_wh_question""], ""modal"": ""none"", ""polarity"": null,...","[""tense""]",phase2 eligible: tense,2,False
4,1741163708330x678606711578176000,complete,"[{""aspect"": ""none"", ""clause"": ""declarative"", ""modal"": ""none"", ""polarity"": ""positive"", ""tense"": ""present"", ""voice"": ""...","[""tense""]",phase2 eligible: tense,2,True
...,...,...,...,...,...,...,...
134,1741163710395x413989918547746700,out_of_scope,[],[],Semi-modal dare is outside the central-modal ontology.,0,False
135,1741163710395x580382123224487700,out_of_scope,[],[],Dare as a semi-modal is outside the frozen schema.,0,False
136,1741163712056x895221609473611600,out_of_scope,[],[],GET-passives are explicitly out of scope.,0,False
137,1741163715620x161645047931569860,out_of_scope,[],[],Linked conditional construction is out of scope.,0,False
138,1741163713633x978808878460501800,out_of_scope,[],[],Embedded or indirect questions are out of scope.,0,False

**Accepted complete source→feature tuples** — 48 row(s)

                           source_id    tense               aspect    voice  polarity          clause  modal
0   1741163708336x930002080700909000  present                 none   active  positive  polar_question   none
1   1741163708336x930002080700909000     past                 none   active  positive  polar_question   none
2   1741163708330x678606711578176000  present                 none   active  positive     declarative   none
3   1741163708330x678606711578176000     past                 none   active  positive     declarative   none
4   1741163708330x197590942940390140       NA                 none   active  positive      imperative   none
5   1741163716068x445742738976088800       NA                 none   active  negative      imperative   none
6   1741163708332x482855077867024000       NA                 none   active  positive      imperative   none
7   1741163708331x843997098925344500       NA                 none   active  positive      imperative   none
8   1741163708332x403656410301087360       NA                 none   active  negative      imperative   none
9   1741163708335x133935596064802990       NA                 none   active  positive      imperative   none
10  1741163708335x356877701278647700       NA                 none   active  positive      imperative   none
11  1741163713626x133661684035994100  present                 none   active  positive     declarative   none
12  1741163713626x335670389512142900  present                 none   active  negative     declarative   none
13  1741163713626x414037782388433340  present                 none   active  positive     declarative   none
14  1741163713626x486355013779909760  present                 none   active  positive     declarative   none
15  1741163713121x244049823776565150  present          progressive   active  positive     declarative   none
16  1741163713121x303053781636601900  present          progressive   active  negative     declarative   none
17  1741163712739x218459335733744320     past                 none   active  positive     declarative   none
18  1741163712739x256584265013129380     past                 none   active  positive     declarative   none
19  1741163712739x998605611367738000     past                 none   active  negative     declarative   none
20  1741163712740x655374430632900200     past                 none   active  positive     declarative   none
21  1741163712321x293020264590759800     past          progressive   active  positive     declarative   none
22  1741163712747x124721408738829090  present              perfect   active  negative     declarative   none
23  1741163712747x157745710696413300  present              perfect   active  negative     declarative   none
24  1741163712747x300382600384414560  present              perfect   active  positive     declarative   none
25  1741163712747x475008652441932600  present              perfect   active  negative     declarative   none
26  1741163712332x472235073902899300     past              perfect   active  negative     declarative   none
27  1741163712332x475879228502143170     past              perfect   active  positive     declarative   none
28  1741163712333x761860144866407300     past              perfect   active  positive     declarative   none
29  1741163712333x761860144866407300     past              perfect   active  negative     declarative   none
30  1741163712744x517808240803915500  present  perfect_progressive   active  positive     declarative   none
31  1741163712328x422695616724010100     past  perfect_progressive   active  negative     declarative   none
32  1741163712328x669008360458158700     past  perfect_progressive   active  positive     declarative   none
33  1741163712047x352927366474730100     past                 none  passive  positive     declarative   none
34  1741163712047x585480674416874600  present                 none  passive  positive     declarative   none
35  1741163712048x136041892375174060  present                 none  passive  positive     declarative   none
36  1741163712048x581247857975133000     past                 none  passive  positive     declarative   none
37  1741163712048x766157093174026800  present          progressive  passive  positive     declarative   none
38  1741163712049x417888525913085100     past              perfect  passive  positive     declarative   none
39  1741163712049x855374993067916200  present                 none  passive  negative     declarative   none
40  1741163711300x444537304178034940       NA                 none   active  positive     declarative  would
41  1741163708331x150409111220634050       NA                 none   active  positive      imperative   none
42  1741163708331x357890058176217500       NA                 none   active  negative      imperative   none
43  1741163708331x891503713311455000       NA                 none   active  negative      imperative   none
44  1741163708331x925040480671095300       NA                 none   active  positive      imperative   none
45  1741163716067x101148462288360720  present                 none   active  negative     declarative   none
46  1741163716068x574314163168649300  present          progressive   active  negative     declarative   none
47  1741163716068x574314163168649300  present              perfect   active  negative     declarative   none

                           source_id    tense               aspect    voice  polarity          clause  modal
0   1741163708336x930002080700909000  present                 none   active  positive  polar_question   none
1   1741163708336x930002080700909000     past                 none   active  positive  polar_question   none
2   1741163708330x678606711578176000  present                 none   active  positive     declarative   none
3   1741163708330x678606711578176000     past                 none   active  positive     declarative   none
4   1741163708330x197590942940390140       NA                 none   active  positive      imperative   none
5   1741163716068x445742738976088800       NA                 none   active  negative      imperative   none
6   1741163708332x482855077867024000       NA                 none   active  positive      imperative   none
7   1741163708331x843997098925344500       NA                 none   active  positive      imperative   none
8   1741163708332x403656410301087360       NA                 none   active  negative      imperative   none
9   1741163708335x133935596064802990       NA                 none   active  positive      imperative   none
10  1741163708335x356877701278647700       NA                 none   active  positive      imperative   none
11  1741163713626x133661684035994100  present                 none   active  positive     declarative   none
12  1741163713626x335670389512142900  present                 none   active  negative     declarative   none
13  1741163713626x414037782388433340  present                 none   active  positive     declarative   none
14  1741163713626x486355013779909760  present                 none   active  positive     declarative   none
15  1741163713121x244049823776565150  present          progressive   active  positive     declarative   none
16  1741163713121x303053781636601900  present          progressive   active  negative     declarative   none
17  1741163712739x218459335733744320     past                 none   active  positive     declarative   none
18  1741163712739x256584265013129380     past                 none   active  positive     declarative   none
19  1741163712739x998605611367738000     past                 none   active  negative     declarative   none
20  1741163712740x655374430632900200     past                 none   active  positive     declarative   none
21  1741163712321x293020264590759800     past          progressive   active  positive     declarative   none
22  1741163712747x124721408738829090  present              perfect   active  negative     declarative   none
23  1741163712747x157745710696413300  present              perfect   active  negative     declarative   none
24  1741163712747x300382600384414560  present              perfect   active  positive     declarative   none
25  1741163712747x475008652441932600  present              perfect   active  negative     declarative   none
26  1741163712332x472235073902899300     past              perfect   active  negative     declarative   none
27  1741163712332x475879228502143170     past              perfect   active  positive     declarative   none
28  1741163712333x761860144866407300     past              perfect   active  positive     declarative   none
29  1741163712333x761860144866407300     past              perfect   active  negative     declarative   none
30  1741163712744x517808240803915500  present  perfect_progressive   active  positive     declarative   none
31  1741163712328x422695616724010100     past  perfect_progressive   active  negative     declarative   none
32  1741163712328x669008360458158700     past  perfect_progressive   active  positive     declarative   none
33  1741163712047x352927366474730100     past                 none  passive  positive     declarative   none
34  1741163712047x585480674416874600  present                 none  passive  positive     declarative   none
35  1741163712048x136041892375174060  present                 none  passive  positive     declarative   none
36  1741163712048x581247857975133000     past                 none  passive  positive     declarative   none
37  1741163712048x766157093174026800  present          progressive  passive  positive     declarative   none
38  1741163712049x417888525913085100     past              perfect  passive  positive     declarative   none
39  1741163712049x855374993067916200  present                 none  passive  negative     declarative   none
40  1741163711300x444537304178034940       NA                 none   active  positive     declarative  would
41  1741163708331x150409111220634050       NA                 none   active  positive      imperative   none
42  1741163708331x357890058176217500       NA                 none   active  negative      imperative   none
43  1741163708331x891503713311455000       NA                 none   active  negative      imperative   none
44  1741163708331x925040480671095300       NA                 none   active  positive      imperative   none
45  1741163716067x101148462288360720  present                 none   active  negative     declarative   none
46  1741163716068x574314163168649300  present          progressive   active  negative     declarative   none
47  1741163716068x574314163168649300  present              perfect   active  negative     declarative   none

## 3. Canonical GrammarCells

Complete source mappings are deduplicated into canonical six-feature GrammarCells while retaining explicit source→cell relations.

In [6]:
canonical_raw = read_jsonl('canonical/cells.jsonl')
canonical_cells = pd.concat([
    canonical_raw[['cell_id']].reset_index(drop=True),
    pd.json_normalize(canonical_raw['features']).reset_index(drop=True),
], axis=1)
canonical_cells['source_support'] = canonical_raw['source_ids'].map(len).to_numpy()
canonical_cells['source_ids'] = canonical_raw['source_ids'].map(compact).to_numpy()
source_cell_relations = read_jsonl('canonical/source_cell_relations.jsonl')
selected_bank_for_support = read_jsonl('items/selected_bank.jsonl')
feature_columns = ['tense', 'aspect', 'voice', 'polarity', 'clause', 'modal']

cell_long = canonical_cells[['cell_id', *feature_columns]].melt(id_vars='cell_id', var_name='dimension', value_name='value')
relation_long = source_cell_relations.merge(canonical_cells[['cell_id', *feature_columns]], on='cell_id').melt(
    id_vars=['source_id', 'cell_id'], value_vars=feature_columns, var_name='dimension', value_name='value'
)
item_long = selected_bank_for_support[['item_id', 'cell_id']].merge(canonical_cells[['cell_id', *feature_columns]], on='cell_id').melt(
    id_vars=['item_id', 'cell_id'], value_vars=feature_columns, var_name='dimension', value_name='value'
)
feature_support = cell_long.groupby(['dimension', 'value']).agg(cells=('cell_id', 'nunique')).reset_index()
feature_support = feature_support.merge(
    relation_long.groupby(['dimension', 'value']).size().rename('source_cell_relations').reset_index(),
    on=['dimension', 'value'], how='left',
).merge(
    item_long.groupby(['dimension', 'value']).size().rename('selected_items').reset_index(),
    on=['dimension', 'value'], how='left',
)
canonical_compression = pd.DataFrame([{
    'complete_descriptors': int(mapping_rows['result'].eq('complete').sum()),
    'accepted_source_cell_relations': len(source_cell_relations),
    'unique_GrammarCells': len(canonical_cells),
    'complete_descriptors_per_cell': mapping_rows['result'].eq('complete').sum() / len(canonical_cells),
    'source_cell_relations_per_cell': len(source_cell_relations) / len(canonical_cells),
}])
show_table('Canonicalisation compression', canonical_compression)
show_table('Canonical GrammarCell inventory', canonical_cells)
show_table('Canonical feature/value support', feature_support.sort_values(['dimension', 'cells', 'value'], ascending=[True, False, True]))
show_table('Retained source→cell relations', source_cell_relations)

**Canonicalisation compression** — 1 row(s)

   complete_descriptors  accepted_source_cell_relations  unique_GrammarCells  complete_descriptors_per_cell  source_cell_relations_per_cell
0                    44                              48                   24                       1.833333                             2.0

**Canonical GrammarCell inventory** — 24 row(s)

,cell_id,tense,aspect,voice,polarity,clause,modal,source_support,source_ids
0,cell_001,present,none,active,positive,polar_question,none,1,"[""1741163708336x930002080700909000""]"
1,cell_002,past,none,active,positive,polar_question,none,1,"[""1741163708336x930002080700909000""]"
2,cell_003,present,none,active,positive,declarative,none,4,"[""1741163708330x678606711578176000"", ""1741163713626x133661684035994100"", ""1741163713626x414037782388433340"", ""174116..."
3,cell_004,past,none,active,positive,declarative,none,4,"[""1741163708330x678606711578176000"", ""1741163712739x218459335733744320"", ""1741163712739x256584265013129380"", ""174116..."
4,cell_005,NA,none,active,positive,imperative,none,7,"[""1741163708330x197590942940390140"", ""1741163708332x482855077867024000"", ""1741163708331x843997098925344500"", ""174116..."
5,cell_006,NA,none,active,negative,imperative,none,4,"[""1741163716068x445742738976088800"", ""1741163708332x403656410301087360"", ""1741163708331x357890058176217500"", ""174116..."
6,cell_007,present,none,active,negative,declarative,none,2,"[""1741163713626x335670389512142900"", ""1741163716067x101148462288360720""]"
7,cell_008,present,progressive,active,positive,declarative,none,1,"[""1741163713121x244049823776565150""]"
8,cell_009,present,progressive,active,negative,declarative,none,2,"[""1741163713121x303053781636601900"", ""1741163716068x574314163168649300""]"
9,cell_010,past,none,active,negative,declarative,none,1,"[""1741163712739x998605611367738000""]"
10,cell_011,past,progressive,active,positive,declarative,none,1,"[""1741163712321x293020264590759800""]"
11,cell_012,present,perfect,active,negative,declarative,none,4,"[""1741163712747x124721408738829090"", ""1741163712747x157745710696413300"", ""1741163712747x475008652441932600"", ""174116..."
12,cell_013,present,perfect,active,positive,declarative,none,1,"[""1741163712747x300382600384414560""]"
13,cell_014,past,perfect,active,negative,declarative,none,2,"[""1741163712332x472235073902899300"", ""1741163712333x761860144866407300""]"
14,cell_015,past,perfect,active,positive,declarative,none,2,"[""1741163712332x475879228502143170"", ""1741163712333x761860144866407300""]"
15,cell_016,present,perfect_progressive,active,positive,declarative,none,1,"[""1741163712744x517808240803915500""]"
16,cell_017,past,perfect_progressive,active,negative,declarative,none,1,"[""1741163712328x422695616724010100""]"
17,cell_018,past,perfect_progressive,active,positive,declarative,none,1,"[""1741163712328x669008360458158700""]"
18,cell_019,past,none,passive,positive,declarative,none,2,"[""1741163712047x352927366474730100"", ""1741163712048x581247857975133000""]"
19,cell_020,present,none,passive,positive,declarative,none,2,"[""1741163712047x585480674416874600"", ""1741163712048x136041892375174060""]"
20,cell_021,present,progressive,passive,positive,declarative,none,1,"[""1741163712048x766157093174026800""]"
21,cell_022,past,perfect,passive,positive,declarative,none,1,"[""1741163712049x417888525913085100""]"
22,cell_023,present,none,passive,negative,declarative,none,1,"[""1741163712049x855374993067916200""]"
23,cell_024,NA,none,active,positive,declarative,would,1,"[""1741163711300x444537304178034940""]"

**Canonical feature/value support** — 16 row(s)

   dimension                value  cells  source_cell_relations  selected_items
0     aspect                 none     12                     30              23
1     aspect              perfect      5                     10               8
2     aspect          progressive      4                      5               8
3     aspect  perfect_progressive      3                      3               5
4     clause          declarative     20                     35              37
5     clause           imperative      2                     11               3
6     clause       polar_question      2                      2               4
7      modal                 none     23                     47              42
8      modal                would      1                      1               2
9   polarity             positive     16                     31              28
10  polarity             negative      8                     17              16
11     tense              present     11                     20              22
12     tense                 past     10                     16              17
13     tense                   NA      3                     12               5
14     voice               active     19                     41              35
15     voice              passive      5                      7               9

**Retained source→cell relations** — 48 row(s)

                           source_id  source_cell_index   cell_id                                        normalisation_note
0   1741163708336x930002080700909000                  0  cell_001                                    phase2 eligible: tense
1   1741163708336x930002080700909000                  1  cell_002                                    phase2 eligible: tense
2   1741163708330x678606711578176000                  0  cell_003                                    phase2 eligible: tense
3   1741163708330x678606711578176000                  1  cell_004                                    phase2 eligible: tense
4   1741163708330x197590942940390140                  0  cell_005                                                      None
5   1741163716068x445742738976088800                  0  cell_006                                                      None
6   1741163708332x482855077867024000                  0  cell_005                 source realization condition: emphatic-DO
7   1741163708331x843997098925344500                  0  cell_005                       source realization condition: LET'S
8   1741163708332x403656410301087360                  0  cell_006                   source realization condition: LET'S NOT
9   1741163708335x133935596064802990                  0  cell_005  source realization condition: LET + third-person pronoun
10  1741163708335x356877701278647700                  0  cell_005  source realization condition: LET + third-person pronoun
11  1741163713626x133661684035994100                  0  cell_003                                                      None
12  1741163713626x335670389512142900                  0  cell_007                                                      None
13  1741163713626x414037782388433340                  0  cell_003                                                      None
14  1741163713626x486355013779909760                  0  cell_003                                                      None
15  1741163713121x244049823776565150                  0  cell_008                                                      None
16  1741163713121x303053781636601900                  0  cell_009                                                      None
17  1741163712739x218459335733744320                  0  cell_004                                                      None
18  1741163712739x256584265013129380                  0  cell_004                                                      None
19  1741163712739x998605611367738000                  0  cell_010                                                      None
20  1741163712740x655374430632900200                  0  cell_004                                                      None
21  1741163712321x293020264590759800                  0  cell_011                                                      None
22  1741163712747x124721408738829090                  0  cell_012                                                      None
23  1741163712747x157745710696413300                  0  cell_012                                                      None
24  1741163712747x300382600384414560                  0  cell_013                                                      None
25  1741163712747x475008652441932600                  0  cell_012                                                      None
26  1741163712332x472235073902899300                  0  cell_014                                                      None
27  1741163712332x475879228502143170                  0  cell_015                                                      None
28  1741163712333x761860144866407300                  0  cell_015                                                      None
29  1741163712333x761860144866407300                  1  cell_014                                                      None
30  1741163712744x517808240803915500                  0  cell_016                                                      None
31  1741163712328x422695616724010100                  0  cell_017                                                      None
32  1741163712328x669008360458158700                  0  cell_018                                                      None
33  1741163712047x352927366474730100                  0  cell_019                                                      None
34  1741163712047x585480674416874600                  0  cell_020                                                      None
35  1741163712048x136041892375174060                  0  cell_020                                                      None
36  1741163712048x581247857975133000                  0  cell_019                                                      None
37  1741163712048x766157093174026800                  0  cell_021                                                      None
38  1741163712049x417888525913085100                  0  cell_022                                                      None
39  1741163712049x855374993067916200                  0  cell_023                                                      None
40  1741163711300x444537304178034940                  0  cell_024                                                      None
41  1741163708331x150409111220634050                  0  cell_005                                                      None
42  1741163708331x357890058176217500                  0  cell_006                                                      None
43  1741163708331x891503713311455000                  0  cell_006                                                      None
44  1741163708331x925040480671095300                  0  cell_005                                                      None
45  1741163716067x101148462288360720                  0  cell_007                                                      None
46  1741163716068x574314163168649300                  0  cell_009                                                      None
47  1741163716068x574314163168649300                  1  cell_012                                                      None

                           source_id  source_cell_index   cell_id                                        normalisation_note
0   1741163708336x930002080700909000                  0  cell_001                                    phase2 eligible: tense
1   1741163708336x930002080700909000                  1  cell_002                                    phase2 eligible: tense
2   1741163708330x678606711578176000                  0  cell_003                                    phase2 eligible: tense
3   1741163708330x678606711578176000                  1  cell_004                                    phase2 eligible: tense
4   1741163708330x197590942940390140                  0  cell_005                                                      None
5   1741163716068x445742738976088800                  0  cell_006                                                      None
6   1741163708332x482855077867024000                  0  cell_005                 source realization condition: emphatic-DO
7   1741163708331x843997098925344500                  0  cell_005                       source realization condition: LET'S
8   1741163708332x403656410301087360                  0  cell_006                   source realization condition: LET'S NOT
9   1741163708335x133935596064802990                  0  cell_005  source realization condition: LET + third-person pronoun
10  1741163708335x356877701278647700                  0  cell_005  source realization condition: LET + third-person pronoun
11  1741163713626x133661684035994100                  0  cell_003                                                      None
12  1741163713626x335670389512142900                  0  cell_007                                                      None
13  1741163713626x414037782388433340                  0  cell_003                                                      None
14  1741163713626x486355013779909760                  0  cell_003                                                      None
15  1741163713121x244049823776565150                  0  cell_008                                                      None
16  1741163713121x303053781636601900                  0  cell_009                                                      None
17  1741163712739x218459335733744320                  0  cell_004                                                      None
18  1741163712739x256584265013129380                  0  cell_004                                                      None
19  1741163712739x998605611367738000                  0  cell_010                                                      None
20  1741163712740x655374430632900200                  0  cell_004                                                      None
21  1741163712321x293020264590759800                  0  cell_011                                                      None
22  1741163712747x124721408738829090                  0  cell_012                                                      None
23  1741163712747x157745710696413300                  0  cell_012                                                      None
24  1741163712747x300382600384414560                  0  cell_013                                                      None
25  1741163712747x475008652441932600                  0  cell_012                                                      None
26  1741163712332x472235073902899300                  0  cell_014                                                      None
27  1741163712332x475879228502143170                  0  cell_015                                                      None
28  1741163712333x761860144866407300                  0  cell_015                                                      None
29  1741163712333x761860144866407300                  1  cell_014                                                      None
30  1741163712744x517808240803915500                  0  cell_016                                                      None
31  1741163712328x422695616724010100                  0  cell_017                                                      None
32  1741163712328x669008360458158700                  0  cell_018                                                      None
33  1741163712047x352927366474730100                  0  cell_019                                                      None
34  1741163712047x585480674416874600                  0  cell_020                                                      None
35  1741163712048x136041892375174060                  0  cell_020                                                      None
36  1741163712048x581247857975133000                  0  cell_019                                                      None
37  1741163712048x766157093174026800                  0  cell_021                                                      None
38  1741163712049x417888525913085100                  0  cell_022                                                      None
39  1741163712049x855374993067916200                  0  cell_023                                                      None
40  1741163711300x444537304178034940                  0  cell_024                                                      None
41  1741163708331x150409111220634050                  0  cell_005                                                      None
42  1741163708331x357890058176217500                  0  cell_006                                                      None
43  1741163708331x891503713311455000                  0  cell_006                                                      None
44  1741163708331x925040480671095300                  0  cell_005                                                      None
45  1741163716067x101148462288360720                  0  cell_007                                                      None
46  1741163716068x574314163168649300                  0  cell_009                                                      None
47  1741163716068x574314163168649300                  1  cell_012                                                      None

## 4. Realistic item generation

Generation uses the fixed GrammarCell and item-design declarations only. Candidate indices 1–3 are the default best-of-three design; indices 4–5 are the preregistered zero-coverage rescue; indices 6–7 are the separate determinacy intervention.

In [7]:
generation_attempts_raw = read_jsonl('items/generation_attempts.jsonl')
generation_attempts = pd.json_normalize(generation_attempts_raw.to_dict('records'), sep='.')
generation_attempts['cohort'] = generation_attempts['candidate_index'].map(
    lambda index: 'default_N3' if index <= 3 else ('conditional_rescue' if index <= 5 else 'determinacy_intervention')
)
generation_attempts['structural_errors'] = generation_attempts['structural_errors'].map(compact)
candidate_rows = read_jsonl('items/candidates.jsonl')
candidate_table = pd.json_normalize(candidate_rows.to_dict('records'), sep='.')
candidate_table['accepted_answers'] = candidate_table['accepted_answers'].map(compact)
generation_funnel = generation_attempts.groupby('cohort').agg(
    attempts=('candidate_id', 'size'),
    cells=('cell_id', 'nunique'),
    structurally_valid=('structurally_valid', 'sum'),
    call_errors=('call_error', lambda values: values.notna().sum()),
    runtime_seconds=('runtime_seconds', 'sum'),
).reset_index()
generation_funnel['structural_validity_rate'] = generation_funnel['structurally_valid'] / generation_funnel['attempts']
attempt_columns = [
    'candidate_id', 'cell_id', 'candidate_index', 'cohort', 'structurally_valid',
    'structural_errors', 'call_error', 'runtime_seconds', 'model', 'provenance.status',
]
candidate_columns = [
    'item_id', 'cell_id', 'generation_metadata.candidate_index', 'format', 'prompt',
    'target_answer', 'accepted_answers', 'generation_metadata.model', 'generation_metadata.provenance.status',
]
show_table('Generation funnel by declared cohort', generation_funnel)
show_table('Generation attempts', generation_attempts[[column for column in attempt_columns if column in generation_attempts]])
show_table('Structurally valid generated candidates', candidate_table[[column for column in candidate_columns if column in candidate_table]])

**Generation funnel by declared cohort** — 3 row(s)

                     cohort  attempts  cells  structurally_valid  call_errors  runtime_seconds  structural_validity_rate
0        conditional_rescue         4      2                   4            0        54.835103                  1.000000
1                default_N3        72     24                  71            0       701.681103                  0.986111
2  determinacy_intervention         2      1                   2            0        27.638386                  1.000000

**Generation attempts** — 78 row(s)

,candidate_id,cell_id,candidate_index,cohort,structurally_valid,structural_errors,call_error,runtime_seconds,model,provenance.status
0,candidate_cell_001_01,cell_001,1,default_N3,True,[],NaN,13.810211,gpt-5.6-sol,reused_live_model_evidence
1,candidate_cell_001_02,cell_001,2,default_N3,True,[],NaN,10.712408,gpt-5.6-sol,reused_live_model_evidence
2,candidate_cell_001_03,cell_001,3,default_N3,False,"[""note must be a non-empty string""]",NaN,15.384500,gpt-5.6-sol,reused_live_model_evidence
3,candidate_cell_002_01,cell_002,1,default_N3,True,[],NaN,8.160050,gpt-5.6-sol,phase6_live_model_evidence
4,candidate_cell_002_02,cell_002,2,default_N3,True,[],NaN,9.300156,gpt-5.6-sol,phase6_live_model_evidence
...,...,...,...,...,...,...,...,...,...,...
73,candidate_cell_023_02,cell_023,2,default_N3,True,[],NaN,6.591508,gpt-5.6-sol,phase6_live_model_evidence
74,candidate_cell_023_03,cell_023,3,default_N3,True,[],NaN,8.398603,gpt-5.6-sol,phase6_live_model_evidence
75,candidate_cell_024_01,cell_024,1,default_N3,True,[],NaN,13.463962,gpt-5.6-sol,reused_live_model_evidence
76,candidate_cell_024_02,cell_024,2,default_N3,True,[],NaN,14.510622,gpt-5.6-sol,reused_live_model_evidence
77,candidate_cell_024_03,cell_024,3,default_N3,True,[],NaN,17.000672,gpt-5.6-sol,reused_live_model_evidence

**Structurally valid generated candidates** — 77 row(s)

,item_id,cell_id,generation_metadata.candidate_index,format,prompt,target_answer,accepted_answers,generation_metadata.model,generation_metadata.provenance.status
0,candidate_cell_001_01,cell_001,1,controlled_production,You want to know whether Mia feeds the cat every morning. Use: Mia / feed the cat every morning. Response: ______,Does Mia feed the cat every morning?,"[""Does Mia feed the cat every morning?""]",gpt-5.6-sol,reused_live_model_evidence
1,candidate_cell_001_02,cell_001,2,controlled_production,Lena wants to know about Tom's daily trip to school. Complete the question using these words: Tom / walk / to school...,Does Tom walk to school every day?,"[""Does Tom walk to school every day?""]",gpt-5.6-sol,reused_live_model_evidence
2,candidate_cell_002_01,cell_002,1,controlled_production,You want to know about Mia's visit yesterday. Complete the question using “call her sister”: [_____],Did Mia call her sister?,"[""Did Mia call her sister?""]",gpt-5.6-sol,NaN
3,candidate_cell_002_02,cell_002,2,controlled_production,You want to know whether Mia took the bus yesterday. Complete the question using the cue “take the bus”: [____]?,Did Mia take the bus yesterday?,"[""Did Mia take the bus yesterday""]",gpt-5.6-sol,NaN
4,candidate_cell_002_03,cell_002,3,controlled_production,You cannot remember whether Mia opened the window yesterday. Ask: ____?,Did Mia open the window yesterday?,"[""Did Mia open the window yesterday""]",gpt-5.6-sol,NaN
...,...,...,...,...,...,...,...,...,...
72,candidate_cell_023_02,cell_023,2,controlled_production,"The café serves lunch, but it closes before dinner. Complete the sentence using “dinner” and “serve”: Dinner ____.",Dinner is not served.,"[""is not served"", ""isn't served""]",gpt-5.6-sol,NaN
73,candidate_cell_023_03,cell_023,3,controlled_production,"Every morning, Mia washes the red cups but leaves the blue cup alone. Complete the sentence using “wash”: The blue c...",The blue cup is not washed.,"[""is not washed"", ""isn't washed""]",gpt-5.6-sol,NaN
74,candidate_cell_024_01,cell_024,1,controlled_production,Ben offered to help with the move. Use the cue “carry the boxes” to complete his response: ____.,He would carry the boxes.,"[""He would carry the boxes.""]",gpt-5.6-sol,reused_live_model_evidence
75,candidate_cell_024_02,cell_024,2,controlled_production,The car is unavailable today. Complete the response using the words in brackets.\nA: How would Ben get to work?\nB: ...,He would take the bus.,"[""He would take the bus."", ""He'd take the bus.""]",gpt-5.6-sol,reused_live_model_evidence
76,candidate_cell_024_03,cell_024,3,controlled_production,"Mia does not have a free afternoon, but imagine that she did. Complete the result using the cue: Mia / visit / her a...",Mia would visit her aunt.,"[""Mia would visit her aunt."", ""Mia'd visit her aunt.""]",gpt-5.6-sol,reused_live_model_evidence

,item_id,cell_id,generation_metadata.candidate_index,format,prompt,target_answer,accepted_answers,generation_metadata.model,generation_metadata.provenance.status
0,candidate_cell_001_01,cell_001,1,controlled_production,You want to know whether Mia feeds the cat every morning. Use: Mia / feed the cat every morning. Response: ______,Does Mia feed the cat every morning?,"[""Does Mia feed the cat every morning?""]",gpt-5.6-sol,reused_live_model_evidence
1,candidate_cell_001_02,cell_001,2,controlled_production,Lena wants to know about Tom's daily trip to school. Complete the question using these words: Tom / walk / to school...,Does Tom walk to school every day?,"[""Does Tom walk to school every day?""]",gpt-5.6-sol,reused_live_model_evidence
2,candidate_cell_002_01,cell_002,1,controlled_production,You want to know about Mia's visit yesterday. Complete the question using “call her sister”: [_____],Did Mia call her sister?,"[""Did Mia call her sister?""]",gpt-5.6-sol,NaN
3,candidate_cell_002_02,cell_002,2,controlled_production,You want to know whether Mia took the bus yesterday. Complete the question using the cue “take the bus”: [____]?,Did Mia take the bus yesterday?,"[""Did Mia take the bus yesterday""]",gpt-5.6-sol,NaN
4,candidate_cell_002_03,cell_002,3,controlled_production,You cannot remember whether Mia opened the window yesterday. Ask: ____?,Did Mia open the window yesterday?,"[""Did Mia open the window yesterday""]",gpt-5.6-sol,NaN
...,...,...,...,...,...,...,...,...,...
72,candidate_cell_023_02,cell_023,2,controlled_production,"The café serves lunch, but it closes before dinner. Complete the sentence using “dinner” and “serve”: Dinner ____.",Dinner is not served.,"[""is not served"", ""isn't served""]",gpt-5.6-sol,NaN
73,candidate_cell_023_03,cell_023,3,controlled_production,"Every morning, Mia washes the red cups but leaves the blue cup alone. Complete the sentence using “wash”: The blue c...",The blue cup is not washed.,"[""is not washed"", ""isn't washed""]",gpt-5.6-sol,NaN
74,candidate_cell_024_01,cell_024,1,controlled_production,Ben offered to help with the move. Use the cue “carry the boxes” to complete his response: ____.,He would carry the boxes.,"[""He would carry the boxes.""]",gpt-5.6-sol,reused_live_model_evidence
75,candidate_cell_024_02,cell_024,2,controlled_production,The car is unavailable today. Complete the response using the words in brackets.\nA: How would Ben get to work?\nB: ...,He would take the bus.,"[""He would take the bus."", ""He'd take the bus.""]",gpt-5.6-sol,reused_live_model_evidence
76,candidate_cell_024_03,cell_024,3,controlled_production,"Mia does not have a free afternoon, but imagine that she did. Complete the result using the cue: Mia / visit / her a...",Mia would visit her aunt.,"[""Mia would visit her aunt."", ""Mia'd visit her aunt.""]",gpt-5.6-sol,reused_live_model_evidence

## 5. Independent validation, curation, and fixed item bank

The active tables use the curated candidate packages and independently retained curated judgments. Raw generation and validation remain immutable audit evidence. Six answer-key packages were corrected and independently rejudged without changing prompts, cell assignments, or item IDs.

In [8]:
raw_validation = read_jsonl('items/validation.jsonl')
curated_validation_raw = read_jsonl('items/curated_validation.jsonl')
curated_validation = pd.json_normalize(curated_validation_raw.to_dict('records'), sep='.')
curated_candidates_raw = read_jsonl('items/curated_candidates.jsonl')
curated_candidates = pd.json_normalize(curated_candidates_raw.to_dict('records'), sep='.')
criterion_columns = sorted(column for column in curated_validation if column.startswith('judgments.') and column.endswith('.passed'))
criterion_names = [column.removeprefix('judgments.').removesuffix('.passed') for column in criterion_columns]
validation_decisions = curated_validation[['item_id', 'accepted', 'rejection_stage', *criterion_columns]].copy()
validation_decisions.columns = ['item_id', 'accepted', 'rejection_stage', *criterion_names]
criterion_results = pd.DataFrame([
    {
        'criterion': criterion,
        'passed': int(curated_validation[column].fillna(False).sum()),
        'failed': int((~curated_validation[column].fillna(False)).sum()),
        'pass_rate': curated_validation[column].fillna(False).mean(),
    }
    for criterion, column in zip(criterion_names, criterion_columns)
])
rejection_summary = curated_validation.assign(
    decision=curated_validation['accepted'].map({True: 'accepted', False: 'rejected'}),
    rejection_stage=curated_validation['rejection_stage'].fillna('accepted'),
).groupby(['decision', 'rejection_stage']).size().rename('items').reset_index()

corrected_items = curated_candidates.loc[curated_candidates['curation_metadata.corrected'].fillna(False)].merge(
    curated_validation[['item_id', 'accepted', 'validation_metadata.status']], on='item_id', how='left'
)
correction_columns = [
    'item_id', 'cell_id', 'prompt', 'target_answer', 'accepted_answers',
    'curation_metadata.corrected_fields', 'accepted', 'validation_metadata.status',
]
for column in ('accepted_answers', 'curation_metadata.corrected_fields'):
    if column in corrected_items:
        corrected_items[column] = corrected_items[column].map(compact)

selected_bank_raw = read_jsonl('items/selected_bank.jsonl')
selected_bank = pd.json_normalize(selected_bank_raw.to_dict('records'), sep='.')
bank_columns = [
    'item_id', 'cell_id', 'selection_metadata.rank', 'selection_metadata.rule',
    'generation_metadata.candidate_index', 'curation_metadata.corrected',
    'format', 'prompt', 'target_answer', 'accepted_answers',
]
selected_bank_display = selected_bank[[column for column in bank_columns if column in selected_bank]].copy()
selected_bank_display['accepted_answers'] = selected_bank_display['accepted_answers'].map(compact)
bank_summary_json = read_json('items/bank_summary.json')
bank_headline_keys = [
    'generated_candidates', 'validator_accepted_candidates', 'validator_acceptance_rate',
    'selected_bank_items', 'selection_rate_among_accepted', 'grammar_cells',
    'covered_cells', 'unique_prompt_rate', 'lexical_types', 'lexical_tokens', 'lexical_diversity',
]
bank_headline = pd.DataFrame([{'metric': key, 'value': bank_summary_json[key]} for key in bank_headline_keys])
audit_counts = pd.DataFrame([{
    'raw_candidates': len(candidate_rows),
    'curated_candidates': len(curated_candidates),
    'raw_judgments': len(raw_validation),
    'curated_judgments': len(curated_validation),
    'packaging_corrections': int(curated_candidates['curation_metadata.corrected'].fillna(False).sum()),
    'corrected_candidates_accepted': int(corrected_items['accepted'].fillna(False).sum()),
    'fixed_bank_items': len(selected_bank),
}])
show_table('Validation and fixed-bank headline results', bank_headline)
show_table('Raw-to-curated audit counts', audit_counts)
show_table('Validation criteria', criterion_results.sort_values(['pass_rate', 'criterion']))
show_table('Acceptance and rejection stages', rejection_summary)
show_table('Per-item active validation decisions', validation_decisions)
show_table('Frozen packaging corrections', corrected_items[[column for column in correction_columns if column in corrected_items]])
show_table('Fixed learner-facing item bank', selected_bank_display)

**Validation and fixed-bank headline results** — 11 row(s)

                           metric       value
0            generated_candidates   77.000000
1   validator_accepted_candidates   54.000000
2       validator_acceptance_rate    0.701299
3             selected_bank_items   44.000000
4   selection_rate_among_accepted    0.814815
5                   grammar_cells   24.000000
6                   covered_cells   24.000000
7              unique_prompt_rate    1.000000
8                   lexical_types  242.000000
9                  lexical_tokens  795.000000
10              lexical_diversity    0.304403

**Raw-to-curated audit counts** — 1 row(s)

   raw_candidates  curated_candidates  raw_judgments  curated_judgments  packaging_corrections  corrected_candidates_accepted  fixed_bank_items
0              77                  77             77                 77                      6                              4                44

**Validation criteria** — 9 row(s)

                        criterion  passed  failed  pass_rate
0                     determinacy      55      22   0.714286
1         pedagogical_suitability      74       3   0.961039
2                     naturalness      75       2   0.974026
3                  grammaticality      77       0   1.000000
4               no_answer_leakage      77       0   1.000000
5           no_extraneous_grammar      77       0   1.000000
6              no_world_knowledge      77       0   1.000000
7  non_target_language_simplicity      77       0   1.000000
8                 target_fidelity      77       0   1.000000

**Acceptance and rejection stages** — 3 row(s)

   decision                   rejection_stage  items
0  accepted                          accepted     54
1  rejected  deterministic_precheck_reapplied      2
2  rejected        independent_model_judgment     21

**Per-item active validation decisions** — 77 row(s)

,item_id,accepted,rejection_stage,determinacy,grammaticality,naturalness,no_answer_leakage,no_extraneous_grammar,no_world_knowledge,non_target_language_simplicity,pedagogical_suitability,target_fidelity
0,candidate_cell_001_01,True,None,True,True,True,True,True,True,True,True,True
1,candidate_cell_001_02,True,None,True,True,True,True,True,True,True,True,True
2,candidate_cell_002_01,True,None,True,True,True,True,True,True,True,True,True
3,candidate_cell_002_02,True,None,True,True,True,True,True,True,True,True,True
4,candidate_cell_002_03,True,None,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
72,candidate_cell_023_02,True,None,True,True,True,True,True,True,True,True,True
73,candidate_cell_023_03,True,None,True,True,True,True,True,True,True,True,True
74,candidate_cell_024_01,False,independent_model_judgment,False,True,False,True,True,True,True,False,True
75,candidate_cell_024_02,True,None,True,True,True,True,True,True,True,True,True
76,candidate_cell_024_03,True,None,True,True,True,True,True,True,True,True,True

**Frozen packaging corrections** — 6 row(s)

,item_id,cell_id,prompt,target_answer,accepted_answers,curation_metadata.corrected_fields,accepted,validation_metadata.status
0,candidate_cell_003_01,cell_003,"Emma has a dog. Every morning, she ___ before breakfast. (walk / the dog)","Every morning, she walks the dog before breakfast.","[""walks the dog""]","[""target_answer""]",True,phase6_frozen_item_packaging_correction
1,candidate_cell_005_01,cell_005,The room is dark. Tell your friend what to do using the cue “turn on / light”: _____.,Turn on the light.,"[""Turn on the light""]","[""accepted_answers""]",False,phase6_frozen_item_packaging_correction
2,candidate_cell_017_06,cell_017,Nina was tired because she [____] well for several nights. Use the negative past perfect continuous form of “sleep.”,Nina was tired because she had not been sleeping well for several nights.,"[""had not been sleeping"", ""hadn't been sleeping""]","[""target_answer""]",True,phase6_frozen_item_packaging_correction
3,candidate_cell_018_01,cell_018,"Maya started at eight. At noon, she was still doing the same job. Use the cue “paint the fence” to complete the sent...",She had been painting the fence for four hours.,"[""She had been painting the fence for four hours"", ""Maya had been painting the fence for four hours""]","[""accepted_answers""]",False,phase6_frozen_item_packaging_correction
4,candidate_cell_018_03,cell_018,"Maya started painting the fence at 8:00. At noon, she was still working. Complete the sentence using the cue (Maya /...","At noon, Maya had been painting the fence for four hours.","[""Maya had been painting the fence for four hours""]","[""accepted_answers"", ""target_answer""]",True,phase6_frozen_item_packaging_correction
5,candidate_cell_019_03,cell_019,"Yesterday, a worker painted the fence. Complete the sentence using the cue (the fence / paint): _____.",The fence was painted.,"[""The fence was painted""]","[""accepted_answers""]",True,phase6_frozen_item_packaging_correction

**Fixed learner-facing item bank** — 44 row(s)

,item_id,cell_id,selection_metadata.rank,selection_metadata.rule,generation_metadata.candidate_index,curation_metadata.corrected,format,prompt,target_answer,accepted_answers
0,candidate_cell_001_01,cell_001,1,earliest_valid,1,False,controlled_production,You want to know whether Mia feeds the cat every morning. Use: Mia / feed the cat every morning. Response: ______,Does Mia feed the cat every morning?,"[""Does Mia feed the cat every morning?""]"
1,candidate_cell_001_02,cell_001,2,maximum_token_set_distance_from_first,2,False,controlled_production,Lena wants to know about Tom's daily trip to school. Complete the question using these words: Tom / walk / to school...,Does Tom walk to school every day?,"[""Does Tom walk to school every day?""]"
2,candidate_cell_002_01,cell_002,1,earliest_valid,1,False,controlled_production,You want to know about Mia's visit yesterday. Complete the question using “call her sister”: [_____],Did Mia call her sister?,"[""Did Mia call her sister?""]"
3,candidate_cell_002_03,cell_002,2,maximum_token_set_distance_from_first,3,False,controlled_production,You cannot remember whether Mia opened the window yesterday. Ask: ____?,Did Mia open the window yesterday?,"[""Did Mia open the window yesterday""]"
4,candidate_cell_003_01,cell_003,1,earliest_valid,1,True,controlled_production,"Emma has a dog. Every morning, she ___ before breakfast. (walk / the dog)","Every morning, she walks the dog before breakfast.","[""walks the dog""]"
5,candidate_cell_003_03,cell_003,2,maximum_token_set_distance_from_first,3,False,controlled_production,Maya has the same routine every morning. Complete the sentence using “pack”: Maya ____ her lunch before school.,Maya packs her lunch before school.,"[""packs""]"
6,candidate_cell_004_01,cell_004,1,earliest_valid,1,False,controlled_production,"Yesterday, Mia found a dirty cup on the table. Complete the sentence using “wash”: Mia ____ the cup.",Mia washed the cup.,"[""washed""]"
7,candidate_cell_004_02,cell_004,2,maximum_token_set_distance_from_first,2,False,controlled_production,"Yesterday, Leo needed some fruit for breakfast. Complete the sentence using “buy”: Leo ____ some apples at the shop.",Leo bought some apples at the shop.,"[""bought""]"
8,candidate_cell_005_03,cell_005,1,earliest_valid,3,False,controlled_production,The room is dark. Tell your friend what to do. Use the cue: turn on / the light\n[____],Turn on the light.,"[""Turn on the light.""]"
9,candidate_cell_006_01,cell_006,1,earliest_valid,1,False,controlled_production,The pan is very hot. Warn a child. Use the cue TOUCH: ____,Don't touch the pan.,"[""Don't touch the pan."", ""Do not touch the pan.""]"
10,candidate_cell_006_03,cell_006,2,maximum_token_set_distance_from_first,3,False,controlled_production,The floor is wet. Tell your friend what to avoid. Use the cue “run.” Response: _____,Don't run on the wet floor.,"[""Don't run on the wet floor."", ""Do not run on the wet floor.""]"
11,candidate_cell_007_01,cell_007,1,earliest_valid,1,False,controlled_production,"Mia usually drinks tea, but she dislikes coffee. Complete the sentence with the cue (drink coffee): Mia ____.",Mia does not drink coffee.,"[""does not drink coffee"", ""doesn't drink coffee""]"
12,candidate_cell_007_02,cell_007,2,maximum_token_set_distance_from_first,2,False,controlled_production,"Mia usually takes the bus to work, so she ___ to work. (walk)",She does not walk to work.,"[""does not walk"", ""doesn't walk""]"
13,candidate_cell_008_01,cell_008,1,earliest_valid,1,False,controlled_production,Maya has a brush in her hand. Complete the sentence using “paint”: She [____] the wall.,She is painting the wall.,"[""is painting""]"
14,candidate_cell_008_02,cell_008,2,maximum_token_set_distance_from_first,2,False,controlled_production,Look at Emma in the kitchen. Complete the sentence using “wash” and “the dishes”: Emma ____.,Emma is washing the dishes.,"[""is washing the dishes""]"
15,candidate_cell_009_01,cell_009,1,earliest_valid,1,False,controlled_production,The children are sitting quietly. Use the cue “play” to complete the sentence: They ____ outside.,They are not playing outside.,"[""are not playing"", ""aren't playing""]"
16,candidate_cell_009_02,cell_009,2,maximum_token_set_distance_from_first,2,False,controlled_production,The children are sitting quietly with their books closed. Complete the sentence using “read”: The children ___.,The children are not reading.,"[""are not reading"", ""aren't reading""]"
17,candidate_cell_010_01,cell_010,1,earliest_valid,1,False,controlled_production,Tom stayed home yesterday. Complete the sentence using the cue (Tom / walk / to the park): ____,Tom did not walk to the park.,"[""Tom did not walk to the park."", ""Tom didn't walk to the park.""]"
18,candidate_cell_010_03,cell_010,2,maximum_token_set_distance_from_first,3,False,controlled_production,The room stayed cold yesterday because the window remained closed. Complete the sentence using the cue: Mia / not op...,Mia did not open the window.,"[""Mia did not open the window."", ""Mia didn't open the window.""]"
19,candidate_cell_011_01,cell_011,1,earliest_valid,1,False,controlled_production,"At 7 p.m. yesterday, Mia was in the kitchen. Complete the sentence using “cook”: Mia [____] dinner.",Mia was cooking dinner.,"[""was cooking""]"
20,candidate_cell_011_03,cell_011,2,maximum_token_set_distance_from_first,3,False,controlled_production,"At eight last night, Maya was busy in the kitchen. Complete the sentence using the cue “make dinner”: Maya _____.",Maya was making dinner.,"[""was making dinner""]"
21,candidate_cell_012_01,cell_012,1,earliest_valid,1,False,controlled_production,"It is noon, but Emma's breakfast is still untouched. Use the cue “Emma / eat / breakfast” to complete the response: ...",Emma has not eaten breakfast.,"[""Emma has not eaten breakfast."", ""Emma hasn't eaten breakfast.""]"
22,candidate_cell_012_02,cell_012,2,maximum_token_set_distance_from_first,2,False,controlled_production,The dishes are still dirty. Complete the response using the cue (Emma / not wash / the dishes): ____,Emma has not washed the dishes.,"[""Emma has not washed the dishes."", ""Emma hasn't washed the dishes.""]"
23,candidate_cell_013_01,cell_013,1,earliest_valid,1,False,controlled_production,The dishes are clean now. Complete the sentence using the cue (wash): Maya ____ the dishes.,Maya has washed the dishes.,"[""has washed""]"
24,candidate_cell_013_02,cell_013,2,maximum_token_set_distance_from_first,2,False,controlled_production,Today is not over. Complete the sentence using “open”: Leo ____ the window three times so far today.,Leo has opened the window three times so far today.,"[""has opened""]"
25,candidate_cell_014_01,cell_014,1,earliest_valid,1,False,controlled_production,"When Mia arrived at noon, the door was still closed. Complete the sentence using “open”: Mia ___ the door yet.",Mia had not opened the door yet.,"[""had not opened"", ""hadn't opened""]"
26,candidate_cell_014_03,cell_014,2,maximum_token_set_distance_from_first,3,False,controlled_production,"When the bus arrived, Maya was still at the stop. Complete the sentence using “leave”: Maya _____.",Maya had not left.,"[""had not left"", ""hadn't left""]"
27,candidate_cell_015_03,cell_015,1,earliest_valid,3,False,controlled_production,"The family sat down for dinner at seven. Complete the sentence using the verb in brackets: By then, Mia _____ the ta...","By then, Mia had set the table.","[""had set""]"
28,candidate_cell_016_01,cell_016,1,earliest_valid,1,False,controlled_production,"Mia started washing the car an hour ago, and she is still doing it. Complete the sentence using the verb in brackets...",Mia has been washing the car for an hour.,"[""has been washing""]"
29,candidate_cell_016_02,cell_016,2,maximum_token_set_distance_from_first,2,False,controlled_production,Maya started cleaning the kitchen an hour ago and is still doing it. Maya [____]. (clean the kitchen),Maya has been cleaning the kitchen.,"[""has been cleaning the kitchen"", ""'s been cleaning the kitchen""]"
30,candidate_cell_017_06,cell_017,1,earliest_valid,6,True,controlled_production,Nina was tired because she [____] well for several nights. Use the negative past perfect continuous form of “sleep.”,Nina was tired because she had not been sleeping well for several nights.,"[""had not been sleeping"", ""hadn't been sleeping""]"
31,candidate_cell_017_07,cell_017,2,maximum_token_set_distance_from_first,7,False,controlled_production,Use the negative past perfect continuous with the words in brackets. Ben's clothes were clean because ________. (he ...,Ben's clothes were clean because he had not been painting the wall.,"[""he had not been painting the wall"", ""he hadn't been painting the wall""]"
32,candidate_cell_018_03,cell_018,1,earliest_valid,3,True,controlled_production,"Maya started painting the fence at 8:00. At noon, she was still working. Complete the sentence using the cue (Maya /...","At noon, Maya had been painting the fence for four hours.","[""Maya had been painting the fence for four hours""]"
33,candidate_cell_019_02,cell_019,1,earliest_valid,2,False,controlled_production,"Yesterday, someone repaired the broken gate. Report what happened, starting with “The broken gate.” Response: ____",The broken gate was repaired.,"[""The broken gate was repaired.""]"
34,candidate_cell_019_03,cell_019,2,maximum_token_set_distance_from_first,3,True,controlled_production,"Yesterday, a worker painted the fence. Complete the sentence using the cue (the fence / paint): _____.",The fence was painted.,"[""The fence was painted""]"
35,candidate_cell_020_01,cell_020,1,earliest_valid,1,False,controlled_production,"Every morning, a worker opens the park gate. Complete the sentence using the cue (open): The park gate ____ every mo...",The park gate is opened every morning.,"[""is opened""]"
36,candidate_cell_020_03,cell_020,2,maximum_token_set_distance_from_first,3,False,controlled_production,A worker cleans the shop windows every morning. Complete the sentence using the verb in brackets: The shop windows _...,The shop windows are cleaned every morning.,"[""are cleaned""]"
37,candidate_cell_021_01,cell_021,1,earliest_valid,1,False,controlled_production,"The workers have started work on the kitchen, but they have not finished. Complete the sentence using the cue (the k...",The kitchen is being painted.,"[""The kitchen is being painted.""]"
38,candidate_cell_021_03,cell_021,2,maximum_token_set_distance_from_first,3,False,controlled_production,Workers are putting fresh paint on the fence right now. Complete the response using the cue: (the fence / paint) ___,The fence is being painted.,"[""The fence is being painted.""]"
39,candidate_cell_022_05,cell_022,1,earliest_valid,5,False,controlled_production,"Before the guests arrived, the room was ready. Complete the sentence using the cue “move”: By then, the chairs ____ ...","By then, the chairs had been moved into the hall.","[""had been moved""]"
40,candidate_cell_023_02,cell_023,1,earliest_valid,2,False,controlled_production,"The café serves lunch, but it closes before dinner. Complete the sentence using “dinner” and “serve”: Dinner ____.",Dinner is not served.,"[""is not served"", ""isn't served""]"
41,candidate_cell_023_03,cell_023,2,maximum_token_set_distance_from_first,3,False,controlled_production,"Every morning, Mia washes the red cups but leaves the blue cup alone. Complete the sentence using “wash”: The blue c...",The blue cup is not washed.,"[""is not washed"", ""isn't washed""]"
42,candidate_cell_024_02,cell_024,1,earliest_valid,2,False,controlled_production,The car is unavailable today. Complete the response using the words in brackets.\nA: How would Ben get to work?\nB: ...,He would take the bus.,"[""He would take the bus."", ""He'd take the bus.""]"
43,candidate_cell_024_03,cell_024,2,maximum_token_set_distance_from_first,3,False,controlled_production,"Mia does not have a free afternoon, but imagine that she did. Complete the result using the cue: Mia / visit / her a...",Mia would visit her aunt.,"[""Mia would visit her aunt."", ""Mia'd visit her aunt.""]"

,item_id,cell_id,selection_metadata.rank,selection_metadata.rule,generation_metadata.candidate_index,curation_metadata.corrected,format,prompt,target_answer,accepted_answers
0,candidate_cell_001_01,cell_001,1,earliest_valid,1,False,controlled_production,You want to know whether Mia feeds the cat every morning. Use: Mia / feed the cat every morning. Response: ______,Does Mia feed the cat every morning?,"[""Does Mia feed the cat every morning?""]"
1,candidate_cell_001_02,cell_001,2,maximum_token_set_distance_from_first,2,False,controlled_production,Lena wants to know about Tom's daily trip to school. Complete the question using these words: Tom / walk / to school...,Does Tom walk to school every day?,"[""Does Tom walk to school every day?""]"
2,candidate_cell_002_01,cell_002,1,earliest_valid,1,False,controlled_production,You want to know about Mia's visit yesterday. Complete the question using “call her sister”: [_____],Did Mia call her sister?,"[""Did Mia call her sister?""]"
3,candidate_cell_002_03,cell_002,2,maximum_token_set_distance_from_first,3,False,controlled_production,You cannot remember whether Mia opened the window yesterday. Ask: ____?,Did Mia open the window yesterday?,"[""Did Mia open the window yesterday""]"
4,candidate_cell_003_01,cell_003,1,earliest_valid,1,True,controlled_production,"Emma has a dog. Every morning, she ___ before breakfast. (walk / the dog)","Every morning, she walks the dog before breakfast.","[""walks the dog""]"
5,candidate_cell_003_03,cell_003,2,maximum_token_set_distance_from_first,3,False,controlled_production,Maya has the same routine every morning. Complete the sentence using “pack”: Maya ____ her lunch before school.,Maya packs her lunch before school.,"[""packs""]"
6,candidate_cell_004_01,cell_004,1,earliest_valid,1,False,controlled_production,"Yesterday, Mia found a dirty cup on the table. Complete the sentence using “wash”: Mia ____ the cup.",Mia washed the cup.,"[""washed""]"
7,candidate_cell_004_02,cell_004,2,maximum_token_set_distance_from_first,2,False,controlled_production,"Yesterday, Leo needed some fruit for breakfast. Complete the sentence using “buy”: Leo ____ some apples at the shop.",Leo bought some apples at the shop.,"[""bought""]"
8,candidate_cell_005_03,cell_005,1,earliest_valid,3,False,controlled_production,The room is dark. Tell your friend what to do. Use the cue: turn on / the light\n[____],Turn on the light.,"[""Turn on the light.""]"
9,candidate_cell_006_01,cell_006,1,earliest_valid,1,False,controlled_production,The pan is very hot. Warn a child. Use the cue TOUCH: ____,Don't touch the pan.,"[""Don't touch the pan."", ""Do not touch the pan.""]"
10,candidate_cell_006_03,cell_006,2,maximum_token_set_distance_from_first,3,False,controlled_production,The floor is wet. Tell your friend what to avoid. Use the cue “run.” Response: _____,Don't run on the wet floor.,"[""Don't run on the wet floor."", ""Do not run on the wet floor.""]"
11,candidate_cell_007_01,cell_007,1,earliest_valid,1,False,controlled_production,"Mia usually drinks tea, but she dislikes coffee. Complete the sentence with the cue (drink coffee): Mia ____.",Mia does not drink coffee.,"[""does not drink coffee"", ""doesn't drink coffee""]"
12,candidate_cell_007_02,cell_007,2,maximum_token_set_distance_from_first,2,False,controlled_production,"Mia usually takes the bus to work, so she ___ to work. (walk)",She does not walk to work.,"[""does not walk"", ""doesn't walk""]"
13,candidate_cell_008_01,cell_008,1,earliest_valid,1,False,controlled_production,Maya has a brush in her hand. Complete the sentence using “paint”: She [____] the wall.,She is painting the wall.,"[""is painting""]"
14,candidate_cell_008_02,cell_008,2,maximum_token_set_distance_from_first,2,False,controlled_production,Look at Emma in the kitchen. Complete the sentence using “wash” and “the dishes”: Emma ____.,Emma is washing the dishes.,"[""is washing the dishes""]"
15,candidate_cell_009_01,cell_009,1,earliest_valid,1,False,controlled_production,The children are sitting quietly. Use the cue “play” to complete the sentence: They ____ outside.,They are not playing outside.,"[""are not playing"", ""aren't playing""]"
16,candidate_cell_009_02,cell_009,2,maximum_token_set_distance_from_first,2,False,controlled_production,The children are sitting quietly with their books closed. Complete the sentence using “read”: The children ___.,The children are not reading.,"[""are not reading"", ""aren't reading""]"
17,candidate_cell_010_01,cell_010,1,earliest_valid,1,False,controlled_production,Tom stayed home yesterday. Complete the sentence using the cue (Tom / walk / to the park): ____,Tom did not walk to the park.,"[""Tom did not walk to the park."", ""Tom didn't walk to the park.""]"
18,candidate_cell_010_03,cell_010,2,maximum_token_set_distance_from_first,3,False,controlled_production,The room stayed cold yesterday because the window remained closed. Complete the sentence using the cue: Mia / not op...,Mia did not open the window.,"[""Mia did not open the window."", ""Mia didn't open the window.""]"
19,candidate_cell_011_01,cell_011,1,earliest_valid,1,False,controlled_production,"At 7 p.m. yesterday, Mia was in the kitchen. Complete the sentence using “cook”: Mia [____] dinner.",Mia was cooking dinner.,"[""was cooking""]"
20,candidate_cell_011_03,cell_011,2,maximum_token_set_distance_from_first,3,False,controlled_production,"At eight last night, Maya was busy in the kitchen. Complete the sentence using the cue “make dinner”: Maya _____.",Maya was making dinner.,"[""was making dinner""]"
21,candidate_cell_012_01,cell_012,1,earliest_valid,1,False,controlled_production,"It is noon, but Emma's breakfast is still untouched. Use the cue “Emma / eat / breakfast” to complete the response: ...",Emma has not eaten breakfast.,"[""Emma has not eaten breakfast."", ""Emma hasn't eaten breakfast.""]"
22,candidate_cell_012_02,cell_012,2,maximum_token_set_distance_from_first,2,False,controlled_production,The dishes are still dirty. Complete the response using the cue (Emma / not wash / the dishes): ____,Emma has not washed the dishes.,"[""Emma has not washed the dishes."", ""Emma hasn't washed the dishes.""]"
23,candidate_cell_013_01,cell_013,1,earliest_valid,1,False,controlled_production,The dishes are clean now. Complete the sentence using the cue (wash): Maya ____ the dishes.,Maya has washed the dishes.,"[""has washed""]"
24,candidate_cell_013_02,cell_013,2,maximum_token_set_distance_from_first,2,False,controlled_production,Today is not over. Complete the sentence using “open”: Leo ____ the window three times so far today.,Leo has opened the window three times so far today.,"[""has opened""]"
25,candidate_cell_014_01,cell_014,1,earliest_valid,1,False,controlled_production,"When Mia arrived at noon, the door was still closed. Complete the sentence using “open”: Mia ___ the door yet.",Mia had not opened the door yet.,"[""had not opened"", ""hadn't opened""]"
26,candidate_cell_014_03,cell_014,2,maximum_token_set_distance_from_first,3,False,controlled_production,"When the bus arrived, Maya was still at the stop. Complete the sentence using “leave”: Maya _____.",Maya had not left.,"[""had not left"", ""hadn't left""]"
27,candidate_cell_015_03,cell_015,1,earliest_valid,3,False,controlled_production,"The family sat down for dinner at seven. Complete the sentence using the verb in brackets: By then, Mia _____ the ta...","By then, Mia had set the table.","[""had set""]"
28,candidate_cell_016_01,cell_016,1,earliest_valid,1,False,controlled_production,"Mia started washing the car an hour ago, and she is still doing it. Complete the sentence using the verb in brackets...",Mia has been washing the car for an hour.,"[""has been washing""]"
29,candidate_cell_016_02,cell_016,2,maximum_token_set_distance_from_first,2,False,controlled_production,Maya started cleaning the kitchen an hour ago and is still doing it. Maya [____]. (clean the kitchen),Maya has been cleaning the kitchen.,"[""has been cleaning the kitchen"", ""'s been cleaning the kitchen""]"
30,candidate_cell_017_06,cell_017,1,earliest_valid,6,True,controlled_production,Nina was tired because she [____] well for several nights. Use the negative past perfect continuous form of “sleep.”,Nina was tired because she had not been sleeping well for several nights.,"[""had not been sleeping"", ""hadn't been sleeping""]"
31,candidate_cell_017_07,cell_017,2,maximum_token_set_distance_from_first,7,False,controlled_production,Use the negative past perfect continuous with the words in brackets. Ben's clothes were clean because ________. (he ...,Ben's clothes were clean because he had not been painting the wall.,"[""he had not been painting the wall"", ""he hadn't been painting the wall""]"
32,candidate_cell_018_03,cell_018,1,earliest_valid,3,True,controlled_production,"Maya started painting the fence at 8:00. At noon, she was still working. Complete the sentence using the cue (Maya /...","At noon, Maya had been painting the fence for four hours.","[""Maya had been painting the fence for four hours""]"
33,candidate_cell_019_02,cell_019,1,earliest_valid,2,False,controlled_production,"Yesterday, someone repaired the broken gate. Report what happened, starting with “The broken gate.” Response: ____",The broken gate was repaired.,"[""The broken gate was repaired.""]"
34,candidate_cell_019_03,cell_019,2,maximum_token_set_distance_from_first,3,True,controlled_production,"Yesterday, a worker painted the fence. Complete the sentence using the cue (the fence / paint): _____.",The fence was painted.,"[""The fence was painted""]"
35,candidate_cell_020_01,cell_020,1,earliest_valid,1,False,controlled_production,"Every morning, a worker opens the park gate. Complete the sentence using the cue (open): The park gate ____ every mo...",The park gate is opened every morning.,"[""is opened""]"
36,candidate_cell_020_03,cell_020,2,maximum_token_set_distance_from_first,3,False,controlled_production,A worker cleans the shop windows every morning. Complete the sentence using the verb in brackets: The shop windows _...,The shop windows are cleaned every morning.,"[""are cleaned""]"
37,candidate_cell_021_01,cell_021,1,earliest_valid,1,False,controlled_production,"The workers have started work on the kitchen, but they have not finished. Complete the sentence using the cue (the k...",The kitchen is being painted.,"[""The kitchen is being painted.""]"
38,candidate_cell_021_03,cell_021,2,maximum_token_set_distance_from_first,3,False,controlled_production,Workers are putting fresh paint on the fence right now. Complete the response using the cue: (the fence / paint) ___,The fence is being painted.,"[""The fence is being painted.""]"
39,candidate_cell_022_05,cell_022,1,earliest_valid,5,False,controlled_production,"Before the guests arrived, the room was ready. Complete the sentence using the cue “move”: By then, the chairs ____ ...","By then, the chairs had been moved into the hall.","[""had been moved""]"
40,candidate_cell_023_02,cell_023,1,earliest_valid,2,False,controlled_production,"The café serves lunch, but it closes before dinner. Complete the sentence using “dinner” and “serve”: Dinner ____.",Dinner is not served.,"[""is not served"", ""isn't served""]"
41,candidate_cell_023_03,cell_023,2,maximum_token_set_distance_from_first,3,False,controlled_production,"Every morning, Mia washes the red cups but leaves the blue cup alone. Complete the sentence using “wash”: The blue c...",The blue cup is not washed.,"[""is not washed"", ""isn't washed""]"
42,candidate_cell_024_02,cell_024,1,earliest_valid,2,False,controlled_production,The car is unavailable today. Complete the response using the words in brackets.\nA: How would Ben get to work?\nB: ...,He would take the bus.,"[""He would take the bus."", ""He'd take the bus.""]"
43,candidate_cell_024_03,cell_024,2,maximum_token_set_distance_from_first,3,False,controlled_production,"Mia does not have a free afternoon, but imagine that she did. Complete the result using the cue: Mia / visit / her a...",Mia would visit her aunt.,"[""Mia would visit her aunt."", ""Mia'd visit her aunt.""]"

## 6. Outcome-free semantic grammar fold

Development cells support candidate construction and acquisition. Compositional cells contain seen constituents in unseen exact tuples; novel-feature cells contain at least one value unseen in development. Outcomes are not used to construct this fold.

In [9]:
fold_raw = read_jsonl('fold/assignments.jsonl')
fold_assignments = pd.concat([
    fold_raw.drop(columns=['features']).reset_index(drop=True),
    pd.json_normalize(fold_raw['features']).reset_index(drop=True),
], axis=1)
fold_assignments['accepted_item_ids'] = fold_assignments['accepted_item_ids'].map(compact)
fold_assignments['unseen_development_values'] = fold_assignments['unseen_development_values'].map(compact)
fold_summary = fold_assignments.groupby('grammar_split').agg(
    cells=('cell_id', 'nunique'),
    selected_items=('accepted_item_support', 'sum'),
    minimum_items_per_cell=('accepted_item_support', 'min'),
    maximum_items_per_cell=('accepted_item_support', 'max'),
).reset_index()
bank_with_grammar = selected_bank_display.merge(
    fold_assignments[['cell_id', 'grammar_split', *feature_columns]], on='cell_id', how='left'
)
show_table('Grammar-fold summary', fold_summary)
show_table('Semantic GrammarCell assignments', fold_assignments)
show_table('Final item bank with canonical features and grammar regime', bank_with_grammar)

**Grammar-fold summary** — 3 row(s)

           grammar_split  cells  selected_items  minimum_items_per_cell  maximum_items_per_cell
0  compositional_holdout      5              10                       2                       2
1            development     18              32                       1                       2
2  novel_feature_holdout      1               2                       2                       2

**Semantic GrammarCell assignments** — 24 row(s)

,cell_id,grammar_split,accepted_item_ids,accepted_item_support,unseen_development_values,selection_reason,tense,aspect,voice,polarity,clause,modal
0,cell_020,compositional_holdout,"[""candidate_cell_020_01"", ""candidate_cell_020_03""]",2,[],semantic_sample_with_supported_development_constituents,present,none,passive,positive,declarative,none
1,cell_007,compositional_holdout,"[""candidate_cell_007_01"", ""candidate_cell_007_02""]",2,[],semantic_sample_with_supported_development_constituents,present,none,active,negative,declarative,none
2,cell_011,compositional_holdout,"[""candidate_cell_011_01"", ""candidate_cell_011_03""]",2,[],semantic_sample_with_supported_development_constituents,past,progressive,active,positive,declarative,none
3,cell_019,compositional_holdout,"[""candidate_cell_019_02"", ""candidate_cell_019_03""]",2,[],semantic_sample_with_supported_development_constituents,past,none,passive,positive,declarative,none
4,cell_010,compositional_holdout,"[""candidate_cell_010_01"", ""candidate_cell_010_03""]",2,[],semantic_sample_with_supported_development_constituents,past,none,active,negative,declarative,none
5,cell_003,development,"[""candidate_cell_003_01"", ""candidate_cell_003_03""]",2,[],development_acquisition,present,none,active,positive,declarative,none
6,cell_018,development,"[""candidate_cell_018_03""]",1,[],development_acquisition,past,perfect_progressive,active,positive,declarative,none
7,cell_017,development,"[""candidate_cell_017_06"", ""candidate_cell_017_07""]",2,[],development_acquisition,past,perfect_progressive,active,negative,declarative,none
8,cell_002,development,"[""candidate_cell_002_01"", ""candidate_cell_002_03""]",2,[],development_acquisition,past,none,active,positive,polar_question,none
9,cell_005,development,"[""candidate_cell_005_03""]",1,[],development_acquisition,NA,none,active,positive,imperative,none
10,cell_012,development,"[""candidate_cell_012_01"", ""candidate_cell_012_02""]",2,[],development_acquisition,present,perfect,active,negative,declarative,none
11,cell_021,development,"[""candidate_cell_021_01"", ""candidate_cell_021_03""]",2,[],development_acquisition,present,progressive,passive,positive,declarative,none
12,cell_023,development,"[""candidate_cell_023_02"", ""candidate_cell_023_03""]",2,[],development_acquisition,present,none,passive,negative,declarative,none
13,cell_001,development,"[""candidate_cell_001_01"", ""candidate_cell_001_02""]",2,[],development_acquisition,present,none,active,positive,polar_question,none
14,cell_022,development,"[""candidate_cell_022_05""]",1,[],development_acquisition,past,perfect,passive,positive,declarative,none
15,cell_006,development,"[""candidate_cell_006_01"", ""candidate_cell_006_03""]",2,[],development_acquisition,NA,none,active,negative,imperative,none
16,cell_014,development,"[""candidate_cell_014_01"", ""candidate_cell_014_03""]",2,[],development_acquisition,past,perfect,active,negative,declarative,none
17,cell_009,development,"[""candidate_cell_009_01"", ""candidate_cell_009_02""]",2,[],development_acquisition,present,progressive,active,negative,declarative,none
18,cell_008,development,"[""candidate_cell_008_01"", ""candidate_cell_008_02""]",2,[],development_acquisition,present,progressive,active,positive,declarative,none
19,cell_024,novel_feature_holdout,"[""candidate_cell_024_02"", ""candidate_cell_024_03""]",2,"[{""dimension"": ""modal"", ""value"": ""would""}]",contains_declared_novel_feature_value,NA,none,active,positive,declarative,would
20,cell_013,development,"[""candidate_cell_013_01"", ""candidate_cell_013_02""]",2,[],development_acquisition,present,perfect,active,positive,declarative,none
21,cell_015,development,"[""candidate_cell_015_03""]",1,[],development_acquisition,past,perfect,active,positive,declarative,none
22,cell_004,development,"[""candidate_cell_004_01"", ""candidate_cell_004_02""]",2,[],development_acquisition,past,none,active,positive,declarative,none
23,cell_016,development,"[""candidate_cell_016_01"", ""candidate_cell_016_02""]",2,[],development_acquisition,present,perfect_progressive,active,positive,declarative,none

**Final item bank with canonical features and grammar regime** — 44 row(s)

,item_id,cell_id,selection_metadata.rank,selection_metadata.rule,generation_metadata.candidate_index,curation_metadata.corrected,format,prompt,target_answer,accepted_answers,grammar_split,tense,aspect,voice,polarity,clause,modal
0,candidate_cell_001_01,cell_001,1,earliest_valid,1,False,controlled_production,You want to know whether Mia feeds the cat every morning. Use: Mia / feed the cat every morning. Response: ______,Does Mia feed the cat every morning?,"[""Does Mia feed the cat every morning?""]",development,present,none,active,positive,polar_question,none
1,candidate_cell_001_02,cell_001,2,maximum_token_set_distance_from_first,2,False,controlled_production,Lena wants to know about Tom's daily trip to school. Complete the question using these words: Tom / walk / to school...,Does Tom walk to school every day?,"[""Does Tom walk to school every day?""]",development,present,none,active,positive,polar_question,none
2,candidate_cell_002_01,cell_002,1,earliest_valid,1,False,controlled_production,You want to know about Mia's visit yesterday. Complete the question using “call her sister”: [_____],Did Mia call her sister?,"[""Did Mia call her sister?""]",development,past,none,active,positive,polar_question,none
3,candidate_cell_002_03,cell_002,2,maximum_token_set_distance_from_first,3,False,controlled_production,You cannot remember whether Mia opened the window yesterday. Ask: ____?,Did Mia open the window yesterday?,"[""Did Mia open the window yesterday""]",development,past,none,active,positive,polar_question,none
4,candidate_cell_003_01,cell_003,1,earliest_valid,1,True,controlled_production,"Emma has a dog. Every morning, she ___ before breakfast. (walk / the dog)","Every morning, she walks the dog before breakfast.","[""walks the dog""]",development,present,none,active,positive,declarative,none
5,candidate_cell_003_03,cell_003,2,maximum_token_set_distance_from_first,3,False,controlled_production,Maya has the same routine every morning. Complete the sentence using “pack”: Maya ____ her lunch before school.,Maya packs her lunch before school.,"[""packs""]",development,present,none,active,positive,declarative,none
6,candidate_cell_004_01,cell_004,1,earliest_valid,1,False,controlled_production,"Yesterday, Mia found a dirty cup on the table. Complete the sentence using “wash”: Mia ____ the cup.",Mia washed the cup.,"[""washed""]",development,past,none,active,positive,declarative,none
7,candidate_cell_004_02,cell_004,2,maximum_token_set_distance_from_first,2,False,controlled_production,"Yesterday, Leo needed some fruit for breakfast. Complete the sentence using “buy”: Leo ____ some apples at the shop.",Leo bought some apples at the shop.,"[""bought""]",development,past,none,active,positive,declarative,none
8,candidate_cell_005_03,cell_005,1,earliest_valid,3,False,controlled_production,The room is dark. Tell your friend what to do. Use the cue: turn on / the light\n[____],Turn on the light.,"[""Turn on the light.""]",development,NA,none,active,positive,imperative,none
9,candidate_cell_006_01,cell_006,1,earliest_valid,1,False,controlled_production,The pan is very hot. Warn a child. Use the cue TOUCH: ____,Don't touch the pan.,"[""Don't touch the pan."", ""Do not touch the pan.""]",development,NA,none,active,negative,imperative,none
10,candidate_cell_006_03,cell_006,2,maximum_token_set_distance_from_first,3,False,controlled_production,The floor is wet. Tell your friend what to avoid. Use the cue “run.” Response: _____,Don't run on the wet floor.,"[""Don't run on the wet floor."", ""Do not run on the wet floor.""]",development,NA,none,active,negative,imperative,none
11,candidate_cell_007_01,cell_007,1,earliest_valid,1,False,controlled_production,"Mia usually drinks tea, but she dislikes coffee. Complete the sentence with the cue (drink coffee): Mia ____.",Mia does not drink coffee.,"[""does not drink coffee"", ""doesn't drink coffee""]",compositional_holdout,present,none,active,negative,declarative,none
12,candidate_cell_007_02,cell_007,2,maximum_token_set_distance_from_first,2,False,controlled_production,"Mia usually takes the bus to work, so she ___ to work. (walk)",She does not walk to work.,"[""does not walk"", ""doesn't walk""]",compositional_holdout,present,none,active,negative,declarative,none
13,candidate_cell_008_01,cell_008,1,earliest_valid,1,False,controlled_production,Maya has a brush in her hand. Complete the sentence using “paint”: She [____] the wall.,She is painting the wall.,"[""is painting""]",development,present,progressive,active,positive,declarative,none
14,candidate_cell_008_02,cell_008,2,maximum_token_set_distance_from_first,2,False,controlled_production,Look at Emma in the kitchen. Complete the sentence using “wash” and “the dishes”: Emma ____.,Emma is washing the dishes.,"[""is washing the dishes""]",development,present,progressive,active,positive,declarative,none
15,candidate_cell_009_01,cell_009,1,earliest_valid,1,False,controlled_production,The children are sitting quietly. Use the cue “play” to complete the sentence: They ____ outside.,They are not playing outside.,"[""are not playing"", ""aren't playing""]",development,present,progressive,active,negative,declarative,none
16,candidate_cell_009_02,cell_009,2,maximum_token_set_distance_from_first,2,False,controlled_production,The children are sitting quietly with their books closed. Complete the sentence using “read”: The children ___.,The children are not reading.,"[""are not reading"", ""aren't reading""]",development,present,progressive,active,negative,declarative,none
17,candidate_cell_010_01,cell_010,1,earliest_valid,1,False,controlled_production,Tom stayed home yesterday. Complete the sentence using the cue (Tom / walk / to the park): ____,Tom did not walk to the park.,"[""Tom did not walk to the park."", ""Tom didn't walk to the park.""]",compositional_holdout,past,none,active,negative,declarative,none
18,candidate_cell_010_03,cell_010,2,maximum_token_set_distance_from_first,3,False,controlled_production,The room stayed cold yesterday because the window remained closed. Complete the sentence using the cue: Mia / not op...,Mia did not open the window.,"[""Mia did not open the window."", ""Mia didn't open the window.""]",compositional_holdout,past,none,active,negative,declarative,none
19,candidate_cell_011_01,cell_011,1,earliest_valid,1,False,controlled_production,"At 7 p.m. yesterday, Mia was in the kitchen. Complete the sentence using “cook”: Mia [____] dinner.",Mia was cooking dinner.,"[""was cooking""]",compositional_holdout,past,progressive,active,positive,declarative,none
20,candidate_cell_011_03,cell_011,2,maximum_token_set_distance_from_first,3,False,controlled_production,"At eight last night, Maya was busy in the kitchen. Complete the sentence using the cue “make dinner”: Maya _____.",Maya was making dinner.,"[""was making dinner""]",compositional_holdout,past,progressive,active,positive,declarative,none
21,candidate_cell_012_01,cell_012,1,earliest_valid,1,False,controlled_production,"It is noon, but Emma's breakfast is still untouched. Use the cue “Emma / eat / breakfast” to complete the response: ...",Emma has not eaten breakfast.,"[""Emma has not eaten breakfast."", ""Emma hasn't eaten breakfast.""]",development,present,perfect,active,negative,declarative,none
22,candidate_cell_012_02,cell_012,2,maximum_token_set_distance_from_first,2,False,controlled_production,The dishes are still dirty. Complete the response using the cue (Emma / not wash / the dishes): ____,Emma has not washed the dishes.,"[""Emma has not washed the dishes."", ""Emma hasn't washed the dishes.""]",development,present,perfect,active,negative,declarative,none
23,candidate_cell_013_01,cell_013,1,earliest_valid,1,False,controlled_production,The dishes are clean now. Complete the sentence using the cue (wash): Maya ____ the dishes.,Maya has washed the dishes.,"[""has washed""]",development,present,perfect,active,positive,declarative,none
24,candidate_cell_013_02,cell_013,2,maximum_token_set_distance_from_first,2,False,controlled_production,Today is not over. Complete the sentence using “open”: Leo ____ the window three times so far today.,Leo has opened the window three times so far today.,"[""has opened""]",development,present,perfect,active,positive,declarative,none
25,candidate_cell_014_01,cell_014,1,earliest_valid,1,False,controlled_production,"When Mia arrived at noon, the door was still closed. Complete the sentence using “open”: Mia ___ the door yet.",Mia had not opened the door yet.,"[""had not opened"", ""hadn't opened""]",development,past,perfect,active,negative,declarative,none
26,candidate_cell_014_03,cell_014,2,maximum_token_set_distance_from_first,3,False,controlled_production,"When the bus arrived, Maya was still at the stop. Complete the sentence using “leave”: Maya _____.",Maya had not left.,"[""had not left"", ""hadn't left""]",development,past,perfect,active,negative,declarative,none
27,candidate_cell_015_03,cell_015,1,earliest_valid,3,False,controlled_production,"The family sat down for dinner at seven. Complete the sentence using the verb in brackets: By then, Mia _____ the ta...","By then, Mia had set the table.","[""had set""]",development,past,perfect,active,positive,declarative,none
28,candidate_cell_016_01,cell_016,1,earliest_valid,1,False,controlled_production,"Mia started washing the car an hour ago, and she is still doing it. Complete the sentence using the verb in brackets...",Mia has been washing the car for an hour.,"[""has been washing""]",development,present,perfect_progressive,active,positive,declarative,none
29,candidate_cell_016_02,cell_016,2,maximum_token_set_distance_from_first,2,False,controlled_production,Maya started cleaning the kitchen an hour ago and is still doing it. Maya [____]. (clean the kitchen),Maya has been cleaning the kitchen.,"[""has been cleaning the kitchen"", ""'s been cleaning the kitchen""]",development,present,perfect_progressive,active,positive,declarative,none
30,candidate_cell_017_06,cell_017,1,earliest_valid,6,True,controlled_production,Nina was tired because she [____] well for several nights. Use the negative past perfect continuous form of “sleep.”,Nina was tired because she had not been sleeping well for several nights.,"[""had not been sleeping"", ""hadn't been sleeping""]",development,past,perfect_progressive,active,negative,declarative,none
31,candidate_cell_017_07,cell_017,2,maximum_token_set_distance_from_first,7,False,controlled_production,Use the negative past perfect continuous with the words in brackets. Ben's clothes were clean because ________. (he ...,Ben's clothes were clean because he had not been painting the wall.,"[""he had not been painting the wall"", ""he hadn't been painting the wall""]",development,past,perfect_progressive,active,negative,declarative,none
32,candidate_cell_018_03,cell_018,1,earliest_valid,3,True,controlled_production,"Maya started painting the fence at 8:00. At noon, she was still working. Complete the sentence using the cue (Maya /...","At noon, Maya had been painting the fence for four hours.","[""Maya had been painting the fence for four hours""]",development,past,perfect_progressive,active,positive,declarative,none
33,candidate_cell_019_02,cell_019,1,earliest_valid,2,False,controlled_production,"Yesterday, someone repaired the broken gate. Report what happened, starting with “The broken gate.” Response: ____",The broken gate was repaired.,"[""The broken gate was repaired.""]",compositional_holdout,past,none,passive,positive,declarative,none
34,candidate_cell_019_03,cell_019,2,maximum_token_set_distance_from_first,3,True,controlled_production,"Yesterday, a worker painted the fence. Complete the sentence using the cue (the fence / paint): _____.",The fence was painted.,"[""The fence was painted""]",compositional_holdout,past,none,passive,positive,declarative,none
35,candidate_cell_020_01,cell_020,1,earliest_valid,1,False,controlled_production,"Every morning, a worker opens the park gate. Complete the sentence using the cue (open): The park gate ____ every mo...",The park gate is opened every morning.,"[""is opened""]",compositional_holdout,present,none,passive,positive,declarative,none
36,candidate_cell_020_03,cell_020,2,maximum_token_set_distance_from_first,3,False,controlled_production,A worker cleans the shop windows every morning. Complete the sentence using the verb in brackets: The shop windows _...,The shop windows are cleaned every morning.,"[""are cleaned""]",compositional_holdout,present,none,passive,positive,declarative,none
37,candidate_cell_021_01,cell_021,1,earliest_valid,1,False,controlled_production,"The workers have started work on the kitchen, but they have not finished. Complete the sentence using the cue (the k...",The kitchen is being painted.,"[""The kitchen is being painted.""]",development,present,progressive,passive,positive,declarative,none
38,candidate_cell_021_03,cell_021,2,maximum_token_set_distance_from_first,3,False,controlled_production,Workers are putting fresh paint on the fence right now. Complete the response using the cue: (the fence / paint) ___,The fence is being painted.,"[""The fence is being painted.""]",development,present,progressive,passive,positive,declarative,none
39,candidate_cell_022_05,cell_022,1,earliest_valid,5,False,controlled_production,"Before the guests arrived, the room was ready. Complete the sentence using the cue “move”: By then, the chairs ____ ...","By then, the chairs had been moved into the hall.","[""had been moved""]",development,past,perfect,passive,positive,declarative,none
40,candidate_cell_023_02,cell_023,1,earliest_valid,2,False,controlled_production,"The café serves lunch, but it closes before dinner. Complete the sentence using “dinner” and “serve”: Dinner ____.",Dinner is not served.,"[""is not served"", ""isn't served""]",development,present,none,passive,negative,declarative,none
41,candidate_cell_023_03,cell_023,2,maximum_token_set_distance_from_first,3,False,controlled_production,"Every morning, Mia washes the red cups but leaves the blue cup alone. Complete the sentence using “wash”: The blue c...",The blue cup is not washed.,"[""is not washed"", ""isn't washed""]",development,present,none,passive,negative,declarative,none
42,candidate_cell_024_02,cell_024,1,earliest_valid,2,False,controlled_production,The car is unavailable today. Complete the response using the words in brackets.\nA: How would Ben get to work?\nB: ...,He would take the bus.,"[""He would take the bus."", ""He'd take the bus.""]",novel_feature_holdout,NA,none,active,positive,declarative,would
43,candidate_cell_024_03,cell_024,2,maximum_token_set_distance_from_first,3,False,controlled_production,"Mia does not have a free afternoon, but imagine that she did. Complete the result using the cue: Mia / visit / her a...",Mia would visit her aunt.,"[""Mia would visit her aunt."", ""Mia'd visit her aunt.""]",novel_feature_holdout,NA,none,active,positive,declarative,would

,item_id,cell_id,selection_metadata.rank,selection_metadata.rule,generation_metadata.candidate_index,curation_metadata.corrected,format,prompt,target_answer,accepted_answers,grammar_split,tense,aspect,voice,polarity,clause,modal
0,candidate_cell_001_01,cell_001,1,earliest_valid,1,False,controlled_production,You want to know whether Mia feeds the cat every morning. Use: Mia / feed the cat every morning. Response: ______,Does Mia feed the cat every morning?,"[""Does Mia feed the cat every morning?""]",development,present,none,active,positive,polar_question,none
1,candidate_cell_001_02,cell_001,2,maximum_token_set_distance_from_first,2,False,controlled_production,Lena wants to know about Tom's daily trip to school. Complete the question using these words: Tom / walk / to school...,Does Tom walk to school every day?,"[""Does Tom walk to school every day?""]",development,present,none,active,positive,polar_question,none
2,candidate_cell_002_01,cell_002,1,earliest_valid,1,False,controlled_production,You want to know about Mia's visit yesterday. Complete the question using “call her sister”: [_____],Did Mia call her sister?,"[""Did Mia call her sister?""]",development,past,none,active,positive,polar_question,none
3,candidate_cell_002_03,cell_002,2,maximum_token_set_distance_from_first,3,False,controlled_production,You cannot remember whether Mia opened the window yesterday. Ask: ____?,Did Mia open the window yesterday?,"[""Did Mia open the window yesterday""]",development,past,none,active,positive,polar_question,none
4,candidate_cell_003_01,cell_003,1,earliest_valid,1,True,controlled_production,"Emma has a dog. Every morning, she ___ before breakfast. (walk / the dog)","Every morning, she walks the dog before breakfast.","[""walks the dog""]",development,present,none,active,positive,declarative,none
5,candidate_cell_003_03,cell_003,2,maximum_token_set_distance_from_first,3,False,controlled_production,Maya has the same routine every morning. Complete the sentence using “pack”: Maya ____ her lunch before school.,Maya packs her lunch before school.,"[""packs""]",development,present,none,active,positive,declarative,none
6,candidate_cell_004_01,cell_004,1,earliest_valid,1,False,controlled_production,"Yesterday, Mia found a dirty cup on the table. Complete the sentence using “wash”: Mia ____ the cup.",Mia washed the cup.,"[""washed""]",development,past,none,active,positive,declarative,none
7,candidate_cell_004_02,cell_004,2,maximum_token_set_distance_from_first,2,False,controlled_production,"Yesterday, Leo needed some fruit for breakfast. Complete the sentence using “buy”: Leo ____ some apples at the shop.",Leo bought some apples at the shop.,"[""bought""]",development,past,none,active,positive,declarative,none
8,candidate_cell_005_03,cell_005,1,earliest_valid,3,False,controlled_production,The room is dark. Tell your friend what to do. Use the cue: turn on / the light\n[____],Turn on the light.,"[""Turn on the light.""]",development,NA,none,active,positive,imperative,none
9,candidate_cell_006_01,cell_006,1,earliest_valid,1,False,controlled_production,The pan is very hot. Warn a child. Use the cue TOUCH: ____,Don't touch the pan.,"[""Don't touch the pan."", ""Do not touch the pan.""]",development,NA,none,active,negative,imperative,none
10,candidate_cell_006_03,cell_006,2,maximum_token_set_distance_from_first,3,False,controlled_production,The floor is wet. Tell your friend what to avoid. Use the cue “run.” Response: _____,Don't run on the wet floor.,"[""Don't run on the wet floor."", ""Do not run on the wet floor.""]",development,NA,none,active,negative,imperative,none
11,candidate_cell_007_01,cell_007,1,earliest_valid,1,False,controlled_production,"Mia usually drinks tea, but she dislikes coffee. Complete the sentence with the cue (drink coffee): Mia ____.",Mia does not drink coffee.,"[""does not drink coffee"", ""doesn't drink coffee""]",compositional_holdout,present,none,active,negative,declarative,none
12,candidate_cell_007_02,cell_007,2,maximum_token_set_distance_from_first,2,False,controlled_production,"Mia usually takes the bus to work, so she ___ to work. (walk)",She does not walk to work.,"[""does not walk"", ""doesn't walk""]",compositional_holdout,present,none,active,negative,declarative,none
13,candidate_cell_008_01,cell_008,1,earliest_valid,1,False,controlled_production,Maya has a brush in her hand. Complete the sentence using “paint”: She [____] the wall.,She is painting the wall.,"[""is painting""]",development,present,progressive,active,positive,declarative,none
14,candidate_cell_008_02,cell_008,2,maximum_token_set_distance_from_first,2,False,controlled_production,Look at Emma in the kitchen. Complete the sentence using “wash” and “the dishes”: Emma ____.,Emma is washing the dishes.,"[""is washing the dishes""]",development,present,progressive,active,positive,declarative,none
15,candidate_cell_009_01,cell_009,1,earliest_valid,1,False,controlled_production,The children are sitting quietly. Use the cue “play” to complete the sentence: They ____ outside.,They are not playing outside.,"[""are not playing"", ""aren't playing""]",development,present,progressive,active,negative,declarative,none
16,candidate_cell_009_02,cell_009,2,maximum_token_set_distance_from_first,2,False,controlled_production,The children are sitting quietly with their books closed. Complete the sentence using “read”: The children ___.,The children are not reading.,"[""are not reading"", ""aren't reading""]",development,present,progressive,active,negative,declarative,none
17,candidate_cell_010_01,cell_010,1,earliest_valid,1,False,controlled_production,Tom stayed home yesterday. Complete the sentence using the cue (Tom / walk / to the park): ____,Tom did not walk to the park.,"[""Tom did not walk to the park."", ""Tom didn't walk to the park.""]",compositional_holdout,past,none,active,negative,declarative,none
18,candidate_cell_010_03,cell_010,2,maximum_token_set_distance_from_first,3,False,controlled_production,The room stayed cold yesterday because the window remained closed. Complete the sentence using the cue: Mia / not op...,Mia did not open the window.,"[""Mia did not open the window."", ""Mia didn't open the window.""]",compositional_holdout,past,none,active,negative,declarative,none
19,candidate_cell_011_01,cell_011,1,earliest_valid,1,False,controlled_production,"At 7 p.m. yesterday, Mia was in the kitchen. Complete the sentence using “cook”: Mia [____] dinner.",Mia was cooking dinner.,"[""was cooking""]",compositional_holdout,past,progressive,active,positive,declarative,none
20,candidate_cell_011_03,cell_011,2,maximum_token_set_distance_from_first,3,False,controlled_production,"At eight last night, Maya was busy in the kitchen. Complete the sentence using the cue “make dinner”: Maya _____.",Maya was making dinner.,"[""was making dinner""]",compositional_holdout,past,progressive,active,positive,declarative,none
21,candidate_cell_012_01,cell_012,1,earliest_valid,1,False,controlled_production,"It is noon, but Emma's breakfast is still untouched. Use the cue “Emma / eat / breakfast” to complete the response: ...",Emma has not eaten breakfast.,"[""Emma has not eaten breakfast."", ""Emma hasn't eaten breakfast.""]",development,present,perfect,active,negative,declarative,none
22,candidate_cell_012_02,cell_012,2,maximum_token_set_distance_from_first,2,False,controlled_production,The dishes are still dirty. Complete the response using the cue (Emma / not wash / the dishes): ____,Emma has not washed the dishes.,"[""Emma has not washed the dishes."", ""Emma hasn't washed the dishes.""]",development,present,perfect,active,negative,declarative,none
23,candidate_cell_013_01,cell_013,1,earliest_valid,1,False,controlled_production,The dishes are clean now. Complete the sentence using the cue (wash): Maya ____ the dishes.,Maya has washed the dishes.,"[""has washed""]",development,present,perfect,active,positive,declarative,none
24,candidate_cell_013_02,cell_013,2,maximum_token_set_distance_from_first,2,False,controlled_production,Today is not over. Complete the sentence using “open”: Leo ____ the window three times so far today.,Leo has opened the window three times so far today.,"[""has opened""]",development,present,perfect,active,positive,declarative,none
25,candidate_cell_014_01,cell_014,1,earliest_valid,1,False,controlled_production,"When Mia arrived at noon, the door was still closed. Complete the sentence using “open”: Mia ___ the door yet.",Mia had not opened the door yet.,"[""had not opened"", ""hadn't opened""]",development,past,perfect,active,negative,declarative,none
26,candidate_cell_014_03,cell_014,2,maximum_token_set_distance_from_first,3,False,controlled_production,"When the bus arrived, Maya was still at the stop. Complete the sentence using “leave”: Maya _____.",Maya had not left.,"[""had not left"", ""hadn't left""]",development,past,perfect,active,negative,declarative,none
27,candidate_cell_015_03,cell_015,1,earliest_valid,3,False,controlled_production,"The family sat down for dinner at seven. Complete the sentence using the verb in brackets: By then, Mia _____ the ta...","By then, Mia had set the table.","[""had set""]",development,past,perfect,active,positive,declarative,none
28,candidate_cell_016_01,cell_016,1,earliest_valid,1,False,controlled_production,"Mia started washing the car an hour ago, and she is still doing it. Complete the sentence using the verb in brackets...",Mia has been washing the car for an hour.,"[""has been washing""]",development,present,perfect_progressive,active,positive,declarative,none
29,candidate_cell_016_02,cell_016,2,maximum_token_set_distance_from_first,2,False,controlled_production,Maya started cleaning the kitchen an hour ago and is still doing it. Maya [____]. (clean the kitchen),Maya has been cleaning the kitchen.,"[""has been cleaning the kitchen"", ""'s been cleaning the kitchen""]",development,present,perfect_progressive,active,positive,declarative,none
30,candidate_cell_017_06,cell_017,1,earliest_valid,6,True,controlled_production,Nina was tired because she [____] well for several nights. Use the negative past perfect continuous form of “sleep.”,Nina was tired because she had not been sleeping well for several nights.,"[""had not been sleeping"", ""hadn't been sleeping""]",development,past,perfect_progressive,active,negative,declarative,none
31,candidate_cell_017_07,cell_017,2,maximum_token_set_distance_from_first,7,False,controlled_production,Use the negative past perfect continuous with the words in brackets. Ben's clothes were clean because ________. (he ...,Ben's clothes were clean because he had not been painting the wall.,"[""he had not been painting the wall"", ""he hadn't been painting the wall""]",development,past,perfect_progressive,active,negative,declarative,none
32,candidate_cell_018_03,cell_018,1,earliest_valid,3,True,controlled_production,"Maya started painting the fence at 8:00. At noon, she was still working. Complete the sentence using the cue (Maya /...","At noon, Maya had been painting the fence for four hours.","[""Maya had been painting the fence for four hours""]",development,past,perfect_progressive,active,positive,declarative,none
33,candidate_cell_019_02,cell_019,1,earliest_valid,2,False,controlled_production,"Yesterday, someone repaired the broken gate. Report what happened, starting with “The broken gate.” Response: ____",The broken gate was repaired.,"[""The broken gate was repaired.""]",compositional_holdout,past,none,passive,positive,declarative,none
34,candidate_cell_019_03,cell_019,2,maximum_token_set_distance_from_first,3,True,controlled_production,"Yesterday, a worker painted the fence. Complete the sentence using the cue (the fence / paint): _____.",The fence was painted.,"[""The fence was painted""]",compositional_holdout,past,none,passive,positive,declarative,none
35,candidate_cell_020_01,cell_020,1,earliest_valid,1,False,controlled_production,"Every morning, a worker opens the park gate. Complete the sentence using the cue (open): The park gate ____ every mo...",The park gate is opened every morning.,"[""is opened""]",compositional_holdout,present,none,passive,positive,declarative,none
36,candidate_cell_020_03,cell_020,2,maximum_token_set_distance_from_first,3,False,controlled_production,A worker cleans the shop windows every morning. Complete the sentence using the verb in brackets: The shop windows _...,The shop windows are cleaned every morning.,"[""are cleaned""]",compositional_holdout,present,none,passive,positive,declarative,none
37,candidate_cell_021_01,cell_021,1,earliest_valid,1,False,controlled_production,"The workers have started work on the kitchen, but they have not finished. Complete the sentence using the cue (the k...",The kitchen is being painted.,"[""The kitchen is being painted.""]",development,present,progressive,passive,positive,declarative,none
38,candidate_cell_021_03,cell_021,2,maximum_token_set_distance_from_first,3,False,controlled_production,Workers are putting fresh paint on the fence right now. Complete the response using the cue: (the fence / paint) ___,The fence is being painted.,"[""The fence is being painted.""]",development,present,progressive,passive,positive,declarative,none
39,candidate_cell_022_05,cell_022,1,earliest_valid,5,False,controlled_production,"Before the guests arrived, the room was ready. Complete the sentence using the cue “move”: By then, the chairs ____ ...","By then, the chairs had been moved into the hall.","[""had been moved""]",development,past,perfect,passive,positive,declarative,none
40,candidate_cell_023_02,cell_023,1,earliest_valid,2,False,controlled_production,"The café serves lunch, but it closes before dinner. Complete the sentence using “dinner” and “serve”: Dinner ____.",Dinner is not served.,"[""is not served"", ""isn't served""]",development,present,none,passive,negative,declarative,none
41,candidate_cell_023_03,cell_023,2,maximum_token_set_distance_from_first,3,False,controlled_production,"Every morning, Mia washes the red cups but leaves the blue cup alone. Complete the sentence using “wash”: The blue c...",The blue cup is not washed.,"[""is not washed"", ""isn't washed""]",development,present,none,passive,negative,declarative,none
42,candidate_cell_024_02,cell_024,1,earliest_valid,2,False,controlled_production,The car is unavailable today. Complete the response using the words in brackets.\nA: How would Ben get to work?\nB: ...,He would take the bus.,"[""He would take the bus."", ""He'd take the bus.""]",novel_feature_holdout,NA,none,active,positive,declarative,would
43,candidate_cell_024_03,cell_024,2,maximum_token_set_distance_from_first,3,False,controlled_production,"Mia does not have a free afternoon, but imagine that she did. Complete the result using the cue: Mia / visit / her a...",Mia would visit her aunt.,"[""Mia would visit her aunt."", ""Mia'd visit her aunt.""]",novel_feature_holdout,NA,none,active,positive,declarative,would

## 7. Development-derived KC candidate space

Feature-value, English-declared operation, supported pairwise-interaction, and exact-development-cell candidates are constructed without learner outcomes. Structural support and activation equivalence are measured on development items before selection.

In [10]:
candidate_inventory = read_json('kc/candidate_inventory.json')
kc_candidates_raw = pd.json_normalize(candidate_inventory['candidates'], sep='.')
kc_candidate_table = kc_candidates_raw[[
    'id', 'family', 'definition', 'cell_support', 'item_support', 'meets_support_threshold',
    'equivalence_class_id', 'equivalent_to', 'is_equivalence_representative',
    'selection_eligible', 'exclusion_reasons', 'supporting_development_cell_ids',
    'supporting_development_item_ids',
]].copy()
for column in ('exclusion_reasons', 'supporting_development_cell_ids', 'supporting_development_item_ids'):
    kc_candidate_table[column] = kc_candidate_table[column].map(compact)
candidate_family_summary = kc_candidates_raw.assign(
    activation_duplicate=kc_candidates_raw['equivalent_to'].notna(),
).groupby('family').agg(
    candidates=('id', 'size'),
    support_eligible=('meets_support_threshold', 'sum'),
    selection_eligible=('selection_eligible', 'sum'),
    activation_duplicates=('activation_duplicate', 'sum'),
    median_cell_support=('cell_support', 'median'),
    median_item_support=('item_support', 'median'),
    maximum_item_support=('item_support', 'max'),
).reset_index()
equivalence_classes = pd.DataFrame([
    {
        'equivalence_class_id': row['equivalence_class_id'],
        'representative_id': row['representative_id'],
        'member_count': len(row['member_ids']),
        'activation_item_support': sum(row['activation_vector']),
        'member_ids': compact(row['member_ids']),
    }
    for row in candidate_inventory['equivalence_classes']
])
candidate_count_table = pd.DataFrame([
    {'metric': metric, 'value': value}
    for metric, value in candidate_inventory['candidate_counts'].items()
])
support_threshold_table = pd.DataFrame([
    {'threshold': name, 'value': value}
    for name, value in candidate_inventory['support_thresholds'].items()
])
show_table('KC candidate-space counts', candidate_count_table)
show_table('Structural support thresholds', support_threshold_table)
show_table('Candidate families and structural support', candidate_family_summary)
show_table('All development-derived KC candidates', kc_candidate_table)
show_table('Development-item activation equivalence classes', equivalence_classes.sort_values(['member_count', 'equivalence_class_id'], ascending=[False, True]))

**KC candidate-space counts** — 9 row(s)

                            metric  value
0                    feature_value      9
1                        operation     10
2                      interaction     18
3                        full_cell     18
4                        raw_total     55
5                 support_eligible     42
6               selection_eligible     28
7   activation_equivalence_classes     38
8  activation_duplicate_candidates     17

**Structural support thresholds** — 2 row(s)

                          threshold  value
0  minimum_interaction_cell_support      2
1  minimum_interaction_item_support      3

**Candidate families and structural support** — 4 row(s)

          family  candidates  support_eligible  selection_eligible  activation_duplicates  median_cell_support  median_item_support  maximum_item_support
0  feature_value           9                 9                   9                      0                  3.0                  6.0                    18
1      full_cell          18                18                   9                      9                  1.0                  2.0                     2
2    interaction          18                 8                   7                      2                  1.0                  2.0                     6
3      operation          10                 7                   3                      6                  2.5                  4.5                    29

**All development-derived KC candidates** — 55 row(s)

,id,family,definition,cell_support,item_support,meets_support_threshold,equivalence_class_id,equivalent_to,is_equivalence_representative,selection_eligible,exclusion_reasons,supporting_development_cell_ids,supporting_development_item_ids
0,kc_cell__tense_na__aspect_none__voice_active__polarity_negative__clause_imperative__modal_none,full_cell,"Represent the exact development GrammarCell tense=NA, aspect=none, voice=active, polarity=negative, clause=imperativ...",1,2,True,activation_class_027,kc_interaction__clause_imperative__and__polarity_negative,False,False,"[""activation_equivalent_on_development_items""]","[""cell_006""]","[""candidate_cell_006_01"", ""candidate_cell_006_03""]"
1,kc_cell__tense_na__aspect_none__voice_active__polarity_positive__clause_imperative__modal_none,full_cell,"Represent the exact development GrammarCell tense=NA, aspect=none, voice=active, polarity=positive, clause=imperativ...",1,1,True,activation_class_029,None,True,True,[],"[""cell_005""]","[""candidate_cell_005_03""]"
2,kc_cell__tense_past__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=past, aspect=none, voice=active, polarity=positive, clause=declara...",1,2,True,activation_class_031,None,True,True,[],"[""cell_004""]","[""candidate_cell_004_01"", ""candidate_cell_004_02""]"
3,kc_cell__tense_past__aspect_none__voice_active__polarity_positive__clause_polar_question__modal_none,full_cell,"Represent the exact development GrammarCell tense=past, aspect=none, voice=active, polarity=positive, clause=polar_q...",1,2,True,activation_class_033,kc_interaction__clause_polar_question__and__tense_past,False,False,"[""activation_equivalent_on_development_items""]","[""cell_002""]","[""candidate_cell_002_01"", ""candidate_cell_002_03""]"
4,kc_cell__tense_past__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=past, aspect=perfect, voice=active, polarity=negative, clause=decl...",1,2,True,activation_class_013,None,True,True,[],"[""cell_014""]","[""candidate_cell_014_01"", ""candidate_cell_014_03""]"
5,kc_cell__tense_past__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=past, aspect=perfect, voice=active, polarity=positive, clause=decl...",1,1,True,activation_class_012,None,True,True,[],"[""cell_015""]","[""candidate_cell_015_03""]"
6,kc_cell__tense_past__aspect_perfect__voice_passive__polarity_positive__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=past, aspect=perfect, voice=passive, polarity=positive, clause=dec...",1,1,True,activation_class_003,kc_interaction__aspect_perfect__and__voice_passive,False,False,"[""activation_equivalent_on_development_items""]","[""cell_022""]","[""candidate_cell_022_05""]"
7,kc_cell__tense_past__aspect_perfect_progressive__voice_active__polarity_negative__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=past, aspect=perfect_progressive, voice=active, polarity=negative,...",1,2,True,activation_class_008,kc_interaction__aspect_perfect_progressive__and__polarity_negative,False,False,"[""activation_equivalent_on_development_items""]","[""cell_017""]","[""candidate_cell_017_06"", ""candidate_cell_017_07""]"
8,kc_cell__tense_past__aspect_perfect_progressive__voice_active__polarity_positive__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=past, aspect=perfect_progressive, voice=active, polarity=positive,...",1,1,True,activation_class_007,None,True,True,[],"[""cell_018""]","[""candidate_cell_018_03""]"
9,kc_cell__tense_present__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=present, aspect=none, voice=active, polarity=positive, clause=decl...",1,2,True,activation_class_032,None,True,True,[],"[""cell_003""]","[""candidate_cell_003_01"", ""candidate_cell_003_03""]"
10,kc_cell__tense_present__aspect_none__voice_active__polarity_positive__clause_polar_question__modal_none,full_cell,"Represent the exact development GrammarCell tense=present, aspect=none, voice=active, polarity=positive, clause=pola...",1,2,True,activation_class_035,kc_interaction__clause_polar_question__and__tense_present,False,False,"[""activation_equivalent_on_development_items""]","[""cell_001""]","[""candidate_cell_001_01"", ""candidate_cell_001_02""]"
11,kc_cell__tense_present__aspect_none__voice_passive__polarity_negative__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=present, aspect=none, voice=passive, polarity=negative, clause=dec...",1,2,True,activation_class_002,kc_interaction__polarity_negative__and__voice_passive,False,False,"[""activation_equivalent_on_development_items""]","[""cell_023""]","[""candidate_cell_023_02"", ""candidate_cell_023_03""]"
12,kc_cell__tense_present__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=present, aspect=perfect, voice=active, polarity=negative, clause=d...",1,2,True,activation_class_017,None,True,True,[],"[""cell_012""]","[""candidate_cell_012_01"", ""candidate_cell_012_02""]"
13,kc_cell__tense_present__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=present, aspect=perfect, voice=active, polarity=positive, clause=d...",1,2,True,activation_class_016,None,True,True,[],"[""cell_013""]","[""candidate_cell_013_01"", ""candidate_cell_013_02""]"
14,kc_cell__tense_present__aspect_perfect_progressive__voice_active__polarity_positive__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=present, aspect=perfect_progressive, voice=active, polarity=positi...",1,2,True,activation_class_010,kc_interaction__aspect_perfect_progressive__and__tense_present,False,False,"[""activation_equivalent_on_development_items""]","[""cell_016""]","[""candidate_cell_016_01"", ""candidate_cell_016_02""]"
15,kc_cell__tense_present__aspect_progressive__voice_active__polarity_negative__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=present, aspect=progressive, voice=active, polarity=negative, clau...",1,2,True,activation_class_022,kc_interaction__aspect_progressive__and__polarity_negative,False,False,"[""activation_equivalent_on_development_items""]","[""cell_009""]","[""candidate_cell_009_01"", ""candidate_cell_009_02""]"
16,kc_cell__tense_present__aspect_progressive__voice_active__polarity_positive__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=present, aspect=progressive, voice=active, polarity=positive, clau...",1,2,True,activation_class_024,None,True,True,[],"[""cell_008""]","[""candidate_cell_008_01"", ""candidate_cell_008_02""]"
17,kc_cell__tense_present__aspect_progressive__voice_passive__polarity_positive__clause_declarative__modal_none,full_cell,"Represent the exact development GrammarCell tense=present, aspect=progressive, voice=passive, polarity=positive, cla...",1,2,True,activation_class_004,kc_interaction__aspect_progressive__and__voice_passive,False,False,"[""activation_equivalent_on_development_items""]","[""cell_021""]","[""candidate_cell_021_01"", ""candidate_cell_021_03""]"
18,kc_feature__aspect__perfect,feature_value,Represent canonical aspect=perfect.,5,8,True,activation_class_020,None,True,True,[],"[""cell_012"", ""cell_013"", ""cell_014"", ""cell_015"", ""cell_022""]","[""candidate_cell_012_01"", ""candidate_cell_012_02"", ""candidate_cell_013_01"", ""candidate_cell_013_02"", ""candidate_cell..."
19,kc_feature__aspect__perfect_progressive,feature_value,Represent canonical aspect=perfect_progressive.,3,5,True,activation_class_011,None,True,True,[],"[""cell_016"", ""cell_017"", ""cell_018""]","[""candidate_cell_016_01"", ""candidate_cell_016_02"", ""candidate_cell_017_06"", ""candidate_cell_017_07"", ""candidate_cell..."
20,kc_feature__aspect__progressive,feature_value,Represent canonical aspect=progressive.,3,6,True,activation_class_025,None,True,True,[],"[""cell_008"", ""cell_009"", ""cell_021""]","[""candidate_cell_008_01"", ""candidate_cell_008_02"", ""candidate_cell_009_01"", ""candidate_cell_009_02"", ""candidate_cell..."
21,kc_feature__clause__imperative,feature_value,Represent canonical clause=imperative.,2,3,True,activation_class_030,None,True,True,[],"[""cell_005"", ""cell_006""]","[""candidate_cell_005_03"", ""candidate_cell_006_01"", ""candidate_cell_006_03""]"
22,kc_feature__clause__polar_question,feature_value,Represent canonical clause=polar_question.,2,4,True,activation_class_037,None,True,True,[],"[""cell_001"", ""cell_002""]","[""candidate_cell_001_01"", ""candidate_cell_001_02"", ""candidate_cell_002_01"", ""candidate_cell_002_03""]"
23,kc_feature__polarity__negative,feature_value,Represent canonical polarity=negative.,6,12,True,activation_class_028,None,True,True,[],"[""cell_006"", ""cell_009"", ""cell_012"", ""cell_014"", ""cell_017"", ""cell_023""]","[""candidate_cell_006_01"", ""candidate_cell_006_03"", ""candidate_cell_009_01"", ""candidate_cell_009_02"", ""candidate_cell..."
24,kc_feature__tense__past,feature_value,Represent canonical tense=past.,7,11,True,activation_class_034,None,True,True,[],"[""cell_002"", ""cell_004"", ""cell_014"", ""cell_015"", ""cell_017"", ""cell_018"", ""cell_022""]","[""candidate_cell_002_01"", ""candidate_cell_002_03"", ""candidate_cell_004_01"", ""candidate_cell_004_02"", ""candidate_cell..."
25,kc_feature__tense__present,feature_value,Represent canonical tense=present.,9,18,True,activation_class_036,None,True,True,[],"[""cell_001"", ""cell_003"", ""cell_008"", ""cell_009"", ""cell_012"", ""cell_013"", ""cell_016"", ""cell_021"", ""cell_023""]","[""candidate_cell_001_01"", ""candidate_cell_001_02"", ""candidate_cell_003_01"", ""candidate_cell_003_03"", ""candidate_cell..."
26,kc_feature__voice__passive,feature_value,Represent canonical voice=passive.,3,5,True,activation_class_006,None,True,True,[],"[""cell_021"", ""cell_022"", ""cell_023""]","[""candidate_cell_021_01"", ""candidate_cell_021_03"", ""candidate_cell_022_05"", ""candidate_cell_023_02"", ""candidate_cell..."
27,kc_interaction__aspect_perfect__and__polarity_negative,interaction,Represent the supported interaction aspect=perfect and polarity=negative.,2,4,True,activation_class_018,None,True,True,[],"[""cell_012"", ""cell_014""]","[""candidate_cell_012_01"", ""candidate_cell_012_02"", ""candidate_cell_014_01"", ""candidate_cell_014_03""]"
28,kc_interaction__aspect_perfect__and__tense_past,interaction,Represent the supported interaction aspect=perfect and tense=past.,3,4,True,activation_class_015,None,True,True,[],"[""cell_014"", ""cell_015"", ""cell_022""]","[""candidate_cell_014_01"", ""candidate_cell_014_03"", ""candidate_cell_015_03"", ""candidate_cell_022_05""]"
29,kc_interaction__aspect_perfect__and__tense_present,interaction,Represent the supported interaction aspect=perfect and tense=present.,2,4,True,activation_class_019,None,True,True,[],"[""cell_012"", ""cell_013""]","[""candidate_cell_012_01"", ""candidate_cell_012_02"", ""candidate_cell_013_01"", ""candidate_cell_013_02""]"
30,kc_interaction__aspect_perfect__and__voice_passive,interaction,Represent the supported interaction aspect=perfect and voice=passive.,1,1,False,activation_class_003,None,True,False,"[""below_interaction_support_threshold""]","[""cell_022""]","[""candidate_cell_022_05""]"
31,kc_interaction__aspect_perfect_progressive__and__polarity_negative,interaction,Represent the supported interaction aspect=perfect_progressive and polarity=negative.,1,2,False,activation_class_008,None,True,False,"[""below_interaction_support_threshold""]","[""cell_017""]","[""candidate_cell_017_06"", ""candidate_cell_017_07""]"
32,kc_interaction__aspect_perfect_progressive__and__tense_past,interaction,Represent the supported interaction aspect=perfect_progressive and tense=past.,2,3,True,activation_class_009,None,True,True,[],"[""cell_017"", ""cell_018""]","[""candidate_cell_017_06"", ""candidate_cell_017_07"", ""candidate_cell_018_03""]"
33,kc_interaction__aspect_perfect_progressive__and__tense_present,interaction,Represent the supported interaction aspect=perfect_progressive and tense=present.,1,2,False,activation_class_010,None,True,False,"[""below_interaction_support_threshold""]","[""cell_016""]","[""candidate_cell_016_01"", ""candidate_cell_016_02""]"
34,kc_interaction__aspect_progressive__and__polarity_negative,interaction,Represent the supported interaction aspect=progressive and polarity=negative.,1,2,False,activation_class_022,None,True,False,"[""below_interaction_support_threshold""]","[""cell_009""]","[""candidate_cell_009_01"", ""candidate_cell_009_02""]"
35,kc_interaction__aspect_progressive__and__tense_present,interaction,Represent the supported interaction aspect=progressive and tense=present.,3,6,True,activation_class_025,kc_feature__aspect__progressive,False,False,"[""activation_equivalent_on_development_items""]","[""cell_008"", ""cell_009"", ""cell_021""]","[""candidate_cell_008_01"", ""candidate_cell_008_02"", ""candidate_cell_009_01"", ""candidate_cell_009_02"", ""candidate_cell..."
36,kc_interaction__aspect_progressive__and__voice_passive,interaction,Represent the supported interaction aspect=progressive and voice=passive.,1,2,False,activation_class_004,None,True,False,"[""below_interaction_support_threshold""]","[""cell_021""]","[""candidate_cell_021_01"", ""candidate_cell_021_03""]"
37,kc_interaction__clause_imperative__and__polarity_negative,interaction,Represent the supported interaction clause=imperative and polarity=negative.,1,2,False,activation_class_027,None,True,False,"[""below_interaction_support_threshold""]","[""cell_006""]","[""candidate_cell_006_01"", ""candidate_cell_006_03""]"
38,kc_interaction__clause_polar_question__and__tense_past,interaction,Represent the supported interaction clause=polar_question and tense=past.,1,2,False,activation_class_033,None,True,False,"[""below_interaction_support_threshold""]","[""cell_002""]","[""candidate_cell_002_01"", ""candidate_cell_002_03""]"
39,kc_interaction__clause_polar_question__and__tense_present,interaction,Represent the supported interaction clause=polar_question and tense=present.,1,2,False,activation_class_035,None,True,False,"[""below_interaction_support_threshold""]","[""cell_001""]","[""candidate_cell_001_01"", ""candidate_cell_001_02""]"
40,kc_interaction__polarity_negative__and__tense_past,interaction,Represent the supported interaction polarity=negative and tense=past.,2,4,True,activation_class_014,None,True,True,[],"[""cell_014"", ""cell_017""]","[""candidate_cell_014_01"", ""candidate_cell_014_03"", ""candidate_cell_017_06"", ""candidate_cell_017_07""]"
41,kc_interaction__polarity_negative__and__tense_present,interaction,Represent the supported interaction polarity=negative and tense=present.,3,6,True,activation_class_023,None,True,True,[],"[""cell_009"", ""cell_012"", ""cell_023""]","[""candidate_cell_009_01"", ""candidate_cell_009_02"", ""candidate_cell_012_01"", ""candidate_cell_012_02"", ""candidate_cell..."
42,kc_interaction__polarity_negative__and__voice_passive,interaction,Represent the supported interaction polarity=negative and voice=passive.,1,2,False,activation_class_002,None,True,False,"[""below_interaction_support_threshold""]","[""cell_023""]","[""candidate_cell_023_02"", ""candidate_cell_023_03""]"
43,kc_interaction__tense_past__and__voice_passive,interaction,Represent the supported interaction tense=past and voice=passive.,1,1,False,activation_class_003,kc_interaction__aspect_perfect__and__voice_passive,False,False,"[""below_interaction_support_threshold"", ""activation_equivalent_on_development_items""]","[""cell_022""]","[""candidate_cell_022_05""]"
44,kc_interaction__tense_present__and__voice_passive,interaction,Represent the supported interaction tense=present and voice=passive.,2,4,True,activation_class_005,None,True,True,[],"[""cell_021"", ""cell_023""]","[""candidate_cell_021_01"", ""candidate_cell_021_03"", ""candidate_cell_023_02"", ""candidate_cell_023_03""]"
45,kc_operation__central_modal,operation,Realise a central modal and base-form complement.,0,0,False,activation_class_001,None,True,False,"[""no_development_item_support""]",[],[]
46,kc_operation__finite_tense_form,operation,Realise a morphologically present- or past-tense finite form.,16,29,True,activation_class_038,None,True,True,[],"[""cell_001"", ""cell_002"", ""cell_003"", ""cell_004"", ""cell_008"", ""cell_009"", ""cell_012"", ""cell_013"", ""cell_014"", ""cell_0...","[""candidate_cell_001_01"", ""candidate_cell_001_02"", ""candidate_cell_002_01"", ""candidate_cell_002_03"", ""candidate_cell..."
47,kc_operation__imperative,operation,Realise an imperative main clause.,2,3,True,activation_class_030,kc_feature__clause__imperative,False,False,"[""activation_equivalent_on_development_items""]","[""cell_005"", ""cell_006""]","[""candidate_cell_005_03"", ""candidate_cell_006_01"", ""candidate_cell_006_03""]"
48,kc_operation__negation,operation,Realise clause-level grammatical negation.,6,12,True,activation_class_028,kc_feature__polarity__negative,False,False,"[""activation_equivalent_on_development_items""]","[""cell_006"", ""cell_009"", ""cell_012"", ""cell_014"", ""cell_017"", ""cell_023""]","[""candidate_cell_006_01"", ""candidate_cell_006_03"", ""candidate_cell_009_01"", ""candidate_cell_009_02"", ""candidate_cell..."
49,kc_operation__operator_inversion,operation,Realise finite-operator and subject inversion.,2,4,True,activation_class_037,kc_feature__clause__polar_question,False,False,"[""activation_equivalent_on_development_items""]","[""cell_001"", ""cell_002""]","[""candidate_cell_001_01"", ""candidate_cell_001_02"", ""candidate_cell_002_01"", ""candidate_cell_002_03""]"
50,kc_operation__passive_dependency,operation,Realise passive BE and a past-participle dependency.,3,5,True,activation_class_006,kc_feature__voice__passive,False,False,"[""activation_equivalent_on_development_items""]","[""cell_021"", ""cell_022"", ""cell_023""]","[""candidate_cell_021_01"", ""candidate_cell_021_03"", ""candidate_cell_022_05"", ""candidate_cell_023_02"", ""candidate_cell..."
51,kc_operation__perfect_dependency,operation,Realise perfect HAVE and its participial dependency.,8,13,True,activation_class_021,None,True,True,[],"[""cell_012"", ""cell_013"", ""cell_014"", ""cell_015"", ""cell_016"", ""cell_017"", ""cell_018"", ""cell_022""]","[""candidate_cell_012_01"", ""candidate_cell_012_02"", ""candidate_cell_013_01"", ""candidate_cell_013_02"", ""candidate_cell..."
52,kc_operation__progressive_dependency,operation,Realise progressive BE and its -ing dependency.,6,11,True,activation_class_026,None,True,True,[],"[""cell_008"", ""cell_009"", ""cell_016"", ""cell_017"", ""cell_018"", ""cell_021""]","[""candidate_cell_008_01"", ""candidate_cell_008_02"", ""candidate_cell_009_01"", ""candidate_cell_009_02"", ""candidate_cell..."
53,kc_operation__subject_wh,operation,Realise a subject-WH main clause without question-triggered inversion.,0,0,False,activation_class_001,kc_operation__central_modal,False,False,"[""no_development_item_support"", ""activation_equivalent_on_development_items""]",[],[]
54,kc_operation__wh_fronting,operation,Front a non-subject WH constituent in a main-clause question.,0,0,False,activation_class_001,kc_operation__central_modal,False,False,"[""no_development_item_support"", ""activation_equivalent_on_development_items""]",[],[]

**Development-item activation equivalence classes** — 38 row(s)

,equivalence_class_id,representative_id,member_count,activation_item_support,member_ids
0,activation_class_001,kc_operation__central_modal,3,0,"[""kc_operation__central_modal"", ""kc_operation__subject_wh"", ""kc_operation__wh_fronting""]"
1,activation_class_003,kc_interaction__aspect_perfect__and__voice_passive,3,1,"[""kc_interaction__aspect_perfect__and__voice_passive"", ""kc_interaction__tense_past__and__voice_passive"", ""kc_cell__t..."
2,activation_class_002,kc_interaction__polarity_negative__and__voice_passive,2,2,"[""kc_interaction__polarity_negative__and__voice_passive"", ""kc_cell__tense_present__aspect_none__voice_passive__polar..."
3,activation_class_004,kc_interaction__aspect_progressive__and__voice_passive,2,2,"[""kc_interaction__aspect_progressive__and__voice_passive"", ""kc_cell__tense_present__aspect_progressive__voice_passiv..."
4,activation_class_006,kc_feature__voice__passive,2,5,"[""kc_feature__voice__passive"", ""kc_operation__passive_dependency""]"
5,activation_class_008,kc_interaction__aspect_perfect_progressive__and__polarity_negative,2,2,"[""kc_interaction__aspect_perfect_progressive__and__polarity_negative"", ""kc_cell__tense_past__aspect_perfect_progress..."
6,activation_class_010,kc_interaction__aspect_perfect_progressive__and__tense_present,2,2,"[""kc_interaction__aspect_perfect_progressive__and__tense_present"", ""kc_cell__tense_present__aspect_perfect_progressi..."
7,activation_class_022,kc_interaction__aspect_progressive__and__polarity_negative,2,2,"[""kc_interaction__aspect_progressive__and__polarity_negative"", ""kc_cell__tense_present__aspect_progressive__voice_ac..."
8,activation_class_025,kc_feature__aspect__progressive,2,6,"[""kc_feature__aspect__progressive"", ""kc_interaction__aspect_progressive__and__tense_present""]"
9,activation_class_027,kc_interaction__clause_imperative__and__polarity_negative,2,2,"[""kc_interaction__clause_imperative__and__polarity_negative"", ""kc_cell__tense_na__aspect_none__voice_active__polarit..."
10,activation_class_028,kc_feature__polarity__negative,2,12,"[""kc_feature__polarity__negative"", ""kc_operation__negation""]"
11,activation_class_030,kc_feature__clause__imperative,2,3,"[""kc_feature__clause__imperative"", ""kc_operation__imperative""]"
12,activation_class_033,kc_interaction__clause_polar_question__and__tense_past,2,2,"[""kc_interaction__clause_polar_question__and__tense_past"", ""kc_cell__tense_past__aspect_none__voice_active__polarity..."
13,activation_class_035,kc_interaction__clause_polar_question__and__tense_present,2,2,"[""kc_interaction__clause_polar_question__and__tense_present"", ""kc_cell__tense_present__aspect_none__voice_active__po..."
14,activation_class_037,kc_feature__clause__polar_question,2,4,"[""kc_feature__clause__polar_question"", ""kc_operation__operator_inversion""]"
15,activation_class_005,kc_interaction__tense_present__and__voice_passive,1,4,"[""kc_interaction__tense_present__and__voice_passive""]"
16,activation_class_007,kc_cell__tense_past__aspect_perfect_progressive__voice_active__polarity_positive__clause_declarative__modal_none,1,1,"[""kc_cell__tense_past__aspect_perfect_progressive__voice_active__polarity_positive__clause_declarative__modal_none""]"
17,activation_class_009,kc_interaction__aspect_perfect_progressive__and__tense_past,1,3,"[""kc_interaction__aspect_perfect_progressive__and__tense_past""]"
18,activation_class_011,kc_feature__aspect__perfect_progressive,1,5,"[""kc_feature__aspect__perfect_progressive""]"
19,activation_class_012,kc_cell__tense_past__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none,1,1,"[""kc_cell__tense_past__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none""]"
20,activation_class_013,kc_cell__tense_past__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none,1,2,"[""kc_cell__tense_past__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none""]"
21,activation_class_014,kc_interaction__polarity_negative__and__tense_past,1,4,"[""kc_interaction__polarity_negative__and__tense_past""]"
22,activation_class_015,kc_interaction__aspect_perfect__and__tense_past,1,4,"[""kc_interaction__aspect_perfect__and__tense_past""]"
23,activation_class_016,kc_cell__tense_present__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none,1,2,"[""kc_cell__tense_present__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none""]"
24,activation_class_017,kc_cell__tense_present__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none,1,2,"[""kc_cell__tense_present__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none""]"
25,activation_class_018,kc_interaction__aspect_perfect__and__polarity_negative,1,4,"[""kc_interaction__aspect_perfect__and__polarity_negative""]"
26,activation_class_019,kc_interaction__aspect_perfect__and__tense_present,1,4,"[""kc_interaction__aspect_perfect__and__tense_present""]"
27,activation_class_020,kc_feature__aspect__perfect,1,8,"[""kc_feature__aspect__perfect""]"
28,activation_class_021,kc_operation__perfect_dependency,1,13,"[""kc_operation__perfect_dependency""]"
29,activation_class_023,kc_interaction__polarity_negative__and__tense_present,1,6,"[""kc_interaction__polarity_negative__and__tense_present""]"
30,activation_class_024,kc_cell__tense_present__aspect_progressive__voice_active__polarity_positive__clause_declarative__modal_none,1,2,"[""kc_cell__tense_present__aspect_progressive__voice_active__polarity_positive__clause_declarative__modal_none""]"
31,activation_class_026,kc_operation__progressive_dependency,1,11,"[""kc_operation__progressive_dependency""]"
32,activation_class_029,kc_cell__tense_na__aspect_none__voice_active__polarity_positive__clause_imperative__modal_none,1,1,"[""kc_cell__tense_na__aspect_none__voice_active__polarity_positive__clause_imperative__modal_none""]"
33,activation_class_031,kc_cell__tense_past__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none,1,2,"[""kc_cell__tense_past__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none""]"
34,activation_class_032,kc_cell__tense_present__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none,1,2,"[""kc_cell__tense_present__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none""]"
35,activation_class_034,kc_feature__tense__past,1,11,"[""kc_feature__tense__past""]"
36,activation_class_036,kc_feature__tense__present,1,18,"[""kc_feature__tense__present""]"
37,activation_class_038,kc_operation__finite_tense_form,1,29,"[""kc_operation__finite_tense_form""]"

,equivalence_class_id,representative_id,member_count,activation_item_support,member_ids
0,activation_class_001,kc_operation__central_modal,3,0,"[""kc_operation__central_modal"", ""kc_operation__subject_wh"", ""kc_operation__wh_fronting""]"
1,activation_class_003,kc_interaction__aspect_perfect__and__voice_passive,3,1,"[""kc_interaction__aspect_perfect__and__voice_passive"", ""kc_interaction__tense_past__and__voice_passive"", ""kc_cell__t..."
2,activation_class_002,kc_interaction__polarity_negative__and__voice_passive,2,2,"[""kc_interaction__polarity_negative__and__voice_passive"", ""kc_cell__tense_present__aspect_none__voice_passive__polar..."
3,activation_class_004,kc_interaction__aspect_progressive__and__voice_passive,2,2,"[""kc_interaction__aspect_progressive__and__voice_passive"", ""kc_cell__tense_present__aspect_progressive__voice_passiv..."
4,activation_class_006,kc_feature__voice__passive,2,5,"[""kc_feature__voice__passive"", ""kc_operation__passive_dependency""]"
5,activation_class_008,kc_interaction__aspect_perfect_progressive__and__polarity_negative,2,2,"[""kc_interaction__aspect_perfect_progressive__and__polarity_negative"", ""kc_cell__tense_past__aspect_perfect_progress..."
6,activation_class_010,kc_interaction__aspect_perfect_progressive__and__tense_present,2,2,"[""kc_interaction__aspect_perfect_progressive__and__tense_present"", ""kc_cell__tense_present__aspect_perfect_progressi..."
7,activation_class_022,kc_interaction__aspect_progressive__and__polarity_negative,2,2,"[""kc_interaction__aspect_progressive__and__polarity_negative"", ""kc_cell__tense_present__aspect_progressive__voice_ac..."
8,activation_class_025,kc_feature__aspect__progressive,2,6,"[""kc_feature__aspect__progressive"", ""kc_interaction__aspect_progressive__and__tense_present""]"
9,activation_class_027,kc_interaction__clause_imperative__and__polarity_negative,2,2,"[""kc_interaction__clause_imperative__and__polarity_negative"", ""kc_cell__tense_na__aspect_none__voice_active__polarit..."
10,activation_class_028,kc_feature__polarity__negative,2,12,"[""kc_feature__polarity__negative"", ""kc_operation__negation""]"
11,activation_class_030,kc_feature__clause__imperative,2,3,"[""kc_feature__clause__imperative"", ""kc_operation__imperative""]"
12,activation_class_033,kc_interaction__clause_polar_question__and__tense_past,2,2,"[""kc_interaction__clause_polar_question__and__tense_past"", ""kc_cell__tense_past__aspect_none__voice_active__polarity..."
13,activation_class_035,kc_interaction__clause_polar_question__and__tense_present,2,2,"[""kc_interaction__clause_polar_question__and__tense_present"", ""kc_cell__tense_present__aspect_none__voice_active__po..."
14,activation_class_037,kc_feature__clause__polar_question,2,4,"[""kc_feature__clause__polar_question"", ""kc_operation__operator_inversion""]"
15,activation_class_005,kc_interaction__tense_present__and__voice_passive,1,4,"[""kc_interaction__tense_present__and__voice_passive""]"
16,activation_class_007,kc_cell__tense_past__aspect_perfect_progressive__voice_active__polarity_positive__clause_declarative__modal_none,1,1,"[""kc_cell__tense_past__aspect_perfect_progressive__voice_active__polarity_positive__clause_declarative__modal_none""]"
17,activation_class_009,kc_interaction__aspect_perfect_progressive__and__tense_past,1,3,"[""kc_interaction__aspect_perfect_progressive__and__tense_past""]"
18,activation_class_011,kc_feature__aspect__perfect_progressive,1,5,"[""kc_feature__aspect__perfect_progressive""]"
19,activation_class_012,kc_cell__tense_past__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none,1,1,"[""kc_cell__tense_past__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none""]"
20,activation_class_013,kc_cell__tense_past__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none,1,2,"[""kc_cell__tense_past__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none""]"
21,activation_class_014,kc_interaction__polarity_negative__and__tense_past,1,4,"[""kc_interaction__polarity_negative__and__tense_past""]"
22,activation_class_015,kc_interaction__aspect_perfect__and__tense_past,1,4,"[""kc_interaction__aspect_perfect__and__tense_past""]"
23,activation_class_016,kc_cell__tense_present__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none,1,2,"[""kc_cell__tense_present__aspect_perfect__voice_active__polarity_positive__clause_declarative__modal_none""]"
24,activation_class_017,kc_cell__tense_present__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none,1,2,"[""kc_cell__tense_present__aspect_perfect__voice_active__polarity_negative__clause_declarative__modal_none""]"
25,activation_class_018,kc_interaction__aspect_perfect__and__polarity_negative,1,4,"[""kc_interaction__aspect_perfect__and__polarity_negative""]"
26,activation_class_019,kc_interaction__aspect_perfect__and__tense_present,1,4,"[""kc_interaction__aspect_perfect__and__tense_present""]"
27,activation_class_020,kc_feature__aspect__perfect,1,8,"[""kc_feature__aspect__perfect""]"
28,activation_class_021,kc_operation__perfect_dependency,1,13,"[""kc_operation__perfect_dependency""]"
29,activation_class_023,kc_interaction__polarity_negative__and__tense_present,1,6,"[""kc_interaction__polarity_negative__and__tense_present""]"
30,activation_class_024,kc_cell__tense_present__aspect_progressive__voice_active__polarity_positive__clause_declarative__modal_none,1,2,"[""kc_cell__tense_present__aspect_progressive__voice_active__polarity_positive__clause_declarative__modal_none""]"
31,activation_class_026,kc_operation__progressive_dependency,1,11,"[""kc_operation__progressive_dependency""]"
32,activation_class_029,kc_cell__tense_na__aspect_none__voice_active__polarity_positive__clause_imperative__modal_none,1,1,"[""kc_cell__tense_na__aspect_none__voice_active__polarity_positive__clause_imperative__modal_none""]"
33,activation_class_031,kc_cell__tense_past__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none,1,2,"[""kc_cell__tense_past__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none""]"
34,activation_class_032,kc_cell__tense_present__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none,1,2,"[""kc_cell__tense_present__aspect_none__voice_active__polarity_positive__clause_declarative__modal_none""]"
35,activation_class_034,kc_feature__tense__past,1,11,"[""kc_feature__tense__past""]"
36,activation_class_036,kc_feature__tense__present,1,18,"[""kc_feature__tense__present""]"
37,activation_class_038,kc_operation__finite_tense_form,1,29,"[""kc_operation__finite_tense_form""]"

## 8. Learner evidence: development acquisition and frozen probes

The mixed synthetic world combines reusable feature, interaction, and weaker exact-cell components. Acquisition contains development items only; every grammar regime is measured in the frozen probe phase. The private oracle-debug artifact is intentionally not loaded.

In [11]:
world = read_yaml('simulation/materialized_world.yaml')
world_overview = pd.DataFrame([{
    'world_id': world['world_id'],
    'claim': world['claim'],
    'seed': world['seed'],
    'learners': world['learners'],
    'passes': world['passes'],
    'item_order': world['item_order'],
    'train_fraction': world['temporal_split']['train_fraction'],
    'validation_fraction': world['temporal_split']['validation_fraction'],
    'test_fraction': world['temporal_split']['test_fraction'],
}])
world_components = pd.json_normalize(world['latent_structure']['components'], sep='.').map(compact)
events = read_jsonl('simulation/events.jsonl.gz')
event_summary = events.groupby(['protocol_phase', 'dataset_split', 'grammar_split']).agg(
    events=('event_id', 'size'),
    learners=('learner_id', 'nunique'),
    items=('item_id', 'nunique'),
    correctness=('correct', 'mean'),
    updates_history_rate=('updates_history', 'mean'),
    updates_mastery_rate=('updates_mastery', 'mean'),
).reset_index()
per_learner = events.groupby('learner_id').agg(
    events=('event_id', 'size'),
    first_sequence_index=('sequence_index', 'min'),
    last_sequence_index=('sequence_index', 'max'),
    correctness=('correct', 'mean'),
).reset_index()
learner_distribution = per_learner[['events', 'first_sequence_index', 'last_sequence_index', 'correctness']].describe().T.reset_index().rename(columns={'index': 'measure'})
event_contract = pd.DataFrame([{
    'events': len(events),
    'learners': events['learner_id'].nunique(),
    'items': events['item_id'].nunique(),
    'acquisition_events': int(events['protocol_phase'].eq('acquisition').sum()),
    'probe_events': int(events['protocol_phase'].eq('probe').sum()),
    'holdout_acquisition_events': int(((events['protocol_phase'] == 'acquisition') & (events['grammar_split'] != 'development')).sum()),
    'probe_events_updating_mastery': int(((events['protocol_phase'] == 'probe') & events['updates_mastery']).sum()),
}])
show_table('Materialized latent-world declaration', world_overview)
show_table('Latent-world structural components', world_components)
show_table('Frozen-probe event contract', event_contract)
show_table('Learner events by protocol phase, temporal split, and grammar regime', event_summary)
show_table('Per-learner event distribution', learner_distribution)
show_table('Chronological learner-event sample', events.head(EVENT_SAMPLE_ROWS), limit=EVENT_SAMPLE_ROWS)

**Materialized latent-world declaration** — 1 row(s)

,world_id,claim,seed,learners,passes,item_order,train_fraction,validation_fraction,test_fraction
0,phase4_mixed_v1,"Responses combine reusable feature knowledge, selected interaction-specific knowledge, and a weaker exact-cell compo...",20260827,1000,6,counterbalanced_rotate_by_learner_and_pass,0.6,0.2,0.2

**Latent-world structural components** — 3 row(s)

,kind,initial_mastery_beta,learning_rate,weight,background_values.tense,background_values.aspect,background_values.voice,background_values.polarity,background_values.clause,background_values.modal,interactions,scope
0,feature_values,"[3.0, 3.0]",0.070,1.00,"[""NA""]","[""none""]","[""active""]","[""positive""]","[""declarative""]","[""none""]",NaN,NaN
1,declared_interactions,"[1.2, 6.8]",0.025,1.50,NaN,NaN,NaN,NaN,NaN,NaN,"[{""activation"": {""aspect"": ""perfect"", ""polarity"": ""negative""}, ""id"": ""perfect_negative""}, {""activation"": {""polarity""...",NaN
2,exact_cells,"[2.0, 4.0]",0.035,0.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,all_cells

**Frozen-probe event contract** — 1 row(s)

   events  learners  items  acquisition_events  probe_events  holdout_acquisition_events  probe_events_updating_mastery
0  204000      1000     44              160000         44000                           0                              0

**Learner events by protocol phase, temporal split, and grammar regime** — 5 row(s)

  protocol_phase dataset_split          grammar_split  events  learners  items  correctness  updates_history_rate  updates_mastery_rate
0    acquisition         train            development  128000      1000     32     0.574359                   1.0                   1.0
1    acquisition    validation            development   32000      1000     32     0.649281                   1.0                   1.0
2          probe          test  compositional_holdout   10000      1000     10     0.639800                   0.0                   0.0
3          probe          test            development   32000      1000     32     0.658406                   0.0                   0.0
4          probe          test  novel_feature_holdout    2000      1000      2     0.408500                   0.0                   0.0

**Per-learner event distribution** — 4 row(s)

                measure   count        mean       std         min         25%         50%         75%         max
0                events  1000.0  204.000000  0.000000  204.000000  204.000000  204.000000  204.000000  204.000000
1  first_sequence_index  1000.0    1.000000  0.000000    1.000000    1.000000    1.000000    1.000000    1.000000
2   last_sequence_index  1000.0  204.000000  0.000000  204.000000  204.000000  204.000000  204.000000  204.000000
3           correctness  1000.0    0.600877  0.036142    0.485294    0.578431    0.602941    0.627451    0.715686

**Chronological learner-event sample** — 20 row(s)

    correct dataset_split       event_id grammar_split  item_difficulty                item_id   learner_id protocol_phase  sequence_index  updates_history  updates_mastery
0         0         train  event_0000001   development             0.15  candidate_cell_001_01  learner_001    acquisition               1             True             True
1         0         train  event_0000002   development             0.15  candidate_cell_001_02  learner_001    acquisition               2             True             True
2         0         train  event_0000003   development             0.15  candidate_cell_002_01  learner_001    acquisition               3             True             True
3         1         train  event_0000004   development             0.15  candidate_cell_002_03  learner_001    acquisition               4             True             True
4         1         train  event_0000005   development             0.00  candidate_cell_003_01  learner_001    acquisition               5             True             True
5         1         train  event_0000006   development             0.00  candidate_cell_003_03  learner_001    acquisition               6             True             True
6         1         train  event_0000007   development             0.00  candidate_cell_004_01  learner_001    acquisition               7             True             True
7         0         train  event_0000008   development             0.00  candidate_cell_004_02  learner_001    acquisition               8             True             True
8         1         train  event_0000009   development             0.15  candidate_cell_005_03  learner_001    acquisition               9             True             True
9         0         train  event_0000010   development             0.15  candidate_cell_006_01  learner_001    acquisition              10             True             True
10        1         train  event_0000011   development             0.15  candidate_cell_006_03  learner_001    acquisition              11             True             True
11        0         train  event_0000012   development             0.00  candidate_cell_008_01  learner_001    acquisition              12             True             True
12        1         train  event_0000013   development             0.00  candidate_cell_008_02  learner_001    acquisition              13             True             True
13        1         train  event_0000014   development             0.00  candidate_cell_009_01  learner_001    acquisition              14             True             True
14        1         train  event_0000015   development             0.00  candidate_cell_009_02  learner_001    acquisition              15             True             True
15        1         train  event_0000016   development             0.00  candidate_cell_012_01  learner_001    acquisition              16             True             True
16        0         train  event_0000017   development             0.00  candidate_cell_012_02  learner_001    acquisition              17             True             True
17        0         train  event_0000018   development             0.00  candidate_cell_013_01  learner_001    acquisition              18             True             True
18        0         train  event_0000019   development             0.00  candidate_cell_013_02  learner_001    acquisition              19             True             True
19        1         train  event_0000020   development             0.00  candidate_cell_014_01  learner_001    acquisition              20             True             True

    correct dataset_split       event_id grammar_split  item_difficulty                item_id   learner_id protocol_phase  sequence_index  updates_history  updates_mastery
0         0         train  event_0000001   development             0.15  candidate_cell_001_01  learner_001    acquisition               1             True             True
1         0         train  event_0000002   development             0.15  candidate_cell_001_02  learner_001    acquisition               2             True             True
2         0         train  event_0000003   development             0.15  candidate_cell_002_01  learner_001    acquisition               3             True             True
3         1         train  event_0000004   development             0.15  candidate_cell_002_03  learner_001    acquisition               4             True             True
4         1         train  event_0000005   development             0.00  candidate_cell_003_01  learner_001    acquisition               5             True             True
5         1         train  event_0000006   development             0.00  candidate_cell_003_03  learner_001    acquisition               6             True             True
6         1         train  event_0000007   development             0.00  candidate_cell_004_01  learner_001    acquisition               7             True             True
7         0         train  event_0000008   development             0.00  candidate_cell_004_02  learner_001    acquisition               8             True             True
8         1         train  event_0000009   development             0.15  candidate_cell_005_03  learner_001    acquisition               9             True             True
9         0         train  event_0000010   development             0.15  candidate_cell_006_01  learner_001    acquisition              10             True             True
10        1         train  event_0000011   development             0.15  candidate_cell_006_03  learner_001    acquisition              11             True             True
11        0         train  event_0000012   development             0.00  candidate_cell_008_01  learner_001    acquisition              12             True             True
12        1         train  event_0000013   development             0.00  candidate_cell_008_02  learner_001    acquisition              13             True             True
13        1         train  event_0000014   development             0.00  candidate_cell_009_01  learner_001    acquisition              14             True             True
14        1         train  event_0000015   development             0.00  candidate_cell_009_02  learner_001    acquisition              15             True             True
15        1         train  event_0000016   development             0.00  candidate_cell_012_01  learner_001    acquisition              16             True             True
16        0         train  event_0000017   development             0.00  candidate_cell_012_02  learner_001    acquisition              17             True             True
17        0         train  event_0000018   development             0.00  candidate_cell_013_01  learner_001    acquisition              18             True             True
18        0         train  event_0000019   development             0.00  candidate_cell_013_02  learner_001    acquisition              19             True             True
19        1         train  event_0000020   development             0.00  candidate_cell_014_01  learner_001    acquisition              20             True             True

## 9. Development-only automated KC selection

The selector starts from reusable feature-value KCs, greedily tests structurally eligible additions under validation log loss plus a per-KC complexity penalty, and backward-prunes. Holdout grammar and reserved test outcomes remain outside selection.

In [12]:
selection_trace = read_json('kc/selection_trace.json')
selection_design_table = pd.DataFrame([{
    'selection_id': selection_trace['selection_id'],
    'selector_model': selection_trace['selector_model']['model'],
    'metric': selection_trace['objective']['metric'],
    'complexity_measure': selection_trace['objective']['complexity'],
    'complexity_penalty_per_KC': selection_trace['objective']['complexity_penalty'],
    'split_mode': selection_trace['split']['mode'],
    'train_events': selection_trace['split']['train_events'],
    'validation_events': selection_trace['split']['validation_events'],
    'held_out_grammar_read': selection_trace['held_out_grammar_read'],
    'reserved_or_holdout_outcomes_read': selection_trace['reserved_or_holdout_outcomes_read'],
    'selected_KCs': len(selection_trace['selected_candidate_ids']),
    'final_validation_log_loss': selection_trace['final_validation_score']['log_loss'],
    'final_objective': selection_trace['final_validation_score']['objective'],
}])
selection_steps = pd.DataFrame([
    {
        'step': row['step'],
        'action': row['action'],
        'selected': row.get('selected'),
        'best_rejected': row.get('best_rejected', {}).get('candidate_id'),
        'validation_n': row.get('score', row.get('best_rejected', {}).get('score', {})).get('n'),
        'log_loss': row.get('score', row.get('best_rejected', {}).get('score', {})).get('log_loss'),
        'KC_count': row.get('score', row.get('best_rejected', {}).get('score', {})).get('kc_count'),
        'complexity_penalty': row.get('score', row.get('best_rejected', {}).get('score', {})).get('complexity_penalty'),
        'objective': row.get('score', row.get('best_rejected', {}).get('score', {})).get('objective'),
        'objective_improvement': row.get('objective_improvement', row.get('best_rejected', {}).get('objective_improvement')),
    }
    for row in selection_trace['trace']
])
candidate_score_rows = []
for row in selection_trace['trace']:
    for scored in row.get('candidate_scores', []):
        candidate_score_rows.append({
            'step': row['step'],
            'candidate_id': scored['candidate_id'],
            'log_loss': scored['score']['log_loss'],
            'KC_count': scored['score']['kc_count'],
            'complexity_penalty': scored['score']['complexity_penalty'],
            'objective': scored['score']['objective'],
            'objective_improvement': scored['objective_improvement'],
        })
candidate_scores = pd.DataFrame(candidate_score_rows)
selected_kcs = kc_candidates_raw.loc[kc_candidates_raw['id'].isin(selection_trace['selected_candidate_ids']), [
    'id', 'family', 'definition', 'cell_support', 'item_support', 'equivalence_class_id',
]].copy()
selected_kcs['selection_order'] = selected_kcs['id'].map({candidate_id: index + 1 for index, candidate_id in enumerate(selection_trace['selected_candidate_ids'])})
selected_kcs = selected_kcs.sort_values('selection_order')
show_table('KC selection design, split, and leakage checks', selection_design_table)
show_table('Automated selection trajectory', selection_steps)
show_table('Candidate scores considered during forward search', candidate_scores.sort_values(['step', 'objective']))
show_table('Frozen automatically selected KC inventory', selected_kcs)

**KC selection design, split, and leakage checks** — 1 row(s)

,selection_id,selector_model,metric,complexity_measure,complexity_penalty_per_KC,split_mode,train_events,validation_events,held_out_grammar_read,reserved_or_holdout_outcomes_read,selected_KCs,final_validation_log_loss,final_objective
0,forward_predictive_parsimony_v1,observable_logistic_kt,log_loss,kc_count,0.0005,chronological,128000,32000,False,False,10,0.646354,0.651354

**Automated selection trajectory** — 3 row(s)

,step,action,selected,best_rejected,validation_n,log_loss,KC_count,complexity_penalty,objective,objective_improvement
0,0,initial_factorized,None,None,32000,0.647160,9,0.0045,0.651660,NaN
1,1,forward_add,kc_interaction__aspect_perfect__and__polarity_negative,None,32000,0.646354,10,0.0050,0.651354,0.000307
2,2,forward_stop,None,kc_interaction__polarity_negative__and__tense_present,32000,0.645991,11,0.0055,0.651491,-0.000137

**Candidate scores considered during forward search** — 19 row(s)

    step                                                 candidate_id  log_loss  KC_count  complexity_penalty  objective  objective_improvement
0      1       kc_interaction__aspect_perfect__and__polarity_negative  0.646354        10              0.0050   0.651354               0.000307
1      1        kc_interaction__polarity_negative__and__tense_present  0.646828        10              0.0050   0.651828              -0.000168
2      1                              kc_operation__finite_tense_form  0.646966        10              0.0050   0.651966              -0.000306
3      1            kc_interaction__tense_present__and__voice_passive  0.646997        10              0.0050   0.651997              -0.000337
4      1                         kc_operation__progressive_dependency  0.647094        10              0.0050   0.652094              -0.000433
5      1  kc_interaction__aspect_perfect_progressive__and__tense_past  0.647113        10              0.0050   0.652113              -0.000452
6      1                             kc_operation__perfect_dependency  0.647170        10              0.0050   0.652170              -0.000510
7      1           kc_interaction__aspect_perfect__and__tense_present  0.647197        10              0.0050   0.652197              -0.000537
8      1              kc_interaction__aspect_perfect__and__tense_past  0.647208        10              0.0050   0.652208              -0.000548
9      1           kc_interaction__polarity_negative__and__tense_past  0.647370        10              0.0050   0.652370              -0.000710
10     2        kc_interaction__polarity_negative__and__tense_present  0.645991        11              0.0055   0.651491              -0.000137
11     2            kc_interaction__tense_present__and__voice_passive  0.646362        11              0.0055   0.651862              -0.000508
12     2                              kc_operation__finite_tense_form  0.646368        11              0.0055   0.651868              -0.000514
13     2                             kc_operation__perfect_dependency  0.646371        11              0.0055   0.651871              -0.000518
14     2           kc_interaction__aspect_perfect__and__tense_present  0.646406        11              0.0055   0.651906              -0.000552
15     2                         kc_operation__progressive_dependency  0.646417        11              0.0055   0.651917              -0.000563
16     2              kc_interaction__aspect_perfect__and__tense_past  0.646420        11              0.0055   0.651920              -0.000566
17     2  kc_interaction__aspect_perfect_progressive__and__tense_past  0.646422        11              0.0055   0.651922              -0.000569
18     2           kc_interaction__polarity_negative__and__tense_past  0.646508        11              0.0055   0.652008              -0.000654

**Frozen automatically selected KC inventory** — 10 row(s)

,id,family,definition,cell_support,item_support,equivalence_class_id,selection_order
0,kc_feature__aspect__perfect,feature_value,Represent canonical aspect=perfect.,5,8,activation_class_020,1
1,kc_feature__aspect__perfect_progressive,feature_value,Represent canonical aspect=perfect_progressive.,3,5,activation_class_011,2
2,kc_feature__aspect__progressive,feature_value,Represent canonical aspect=progressive.,3,6,activation_class_025,3
3,kc_feature__clause__imperative,feature_value,Represent canonical clause=imperative.,2,3,activation_class_030,4
4,kc_feature__clause__polar_question,feature_value,Represent canonical clause=polar_question.,2,4,activation_class_037,5
5,kc_feature__polarity__negative,feature_value,Represent canonical polarity=negative.,6,12,activation_class_028,6
6,kc_feature__tense__past,feature_value,Represent canonical tense=past.,7,11,activation_class_034,7
7,kc_feature__tense__present,feature_value,Represent canonical tense=present.,9,18,activation_class_036,8
8,kc_feature__voice__passive,feature_value,Represent canonical voice=passive.,3,5,activation_class_006,9
9,kc_interaction__aspect_perfect__and__polarity_negative,interaction,Represent the supported interaction aspect=perfect and polarity=negative.,2,4,activation_class_018,10

,id,family,definition,cell_support,item_support,equivalence_class_id,selection_order
0,kc_feature__aspect__perfect,feature_value,Represent canonical aspect=perfect.,5,8,activation_class_020,1
1,kc_feature__aspect__perfect_progressive,feature_value,Represent canonical aspect=perfect_progressive.,3,5,activation_class_011,2
2,kc_feature__aspect__progressive,feature_value,Represent canonical aspect=progressive.,3,6,activation_class_025,3
3,kc_feature__clause__imperative,feature_value,Represent canonical clause=imperative.,2,3,activation_class_030,4
4,kc_feature__clause__polar_question,feature_value,Represent canonical clause=polar_question.,2,4,activation_class_037,5
5,kc_feature__polarity__negative,feature_value,Represent canonical polarity=negative.,6,12,activation_class_028,6
6,kc_feature__tense__past,feature_value,Represent canonical tense=past.,7,11,activation_class_034,7
7,kc_feature__tense__present,feature_value,Represent canonical tense=present.,9,18,activation_class_036,8
8,kc_feature__voice__passive,feature_value,Represent canonical voice=passive.,3,5,activation_class_006,9
9,kc_interaction__aspect_perfect__and__polarity_negative,interaction,Represent the supported interaction aspect=perfect and polarity=negative.,2,4,activation_class_018,10

## 10. Frozen KC policies, item–KC projections, and Q-matrices

The automated policy and comparison policies are projected over the identical fixed item bank. The Q-matrix tables make item coverage, edge count, density, and KCs per item directly inspectable.

In [13]:
policy_summary_rows = []
policy_kc_rows = []
for policy_path in sorted((DATA_DIR / 'kc/policies').glob('*.yaml')):
    policy_name = policy_path.stem
    policy = read_yaml(f'kc/policies/{policy_path.name}')
    q_matrix = pd.read_csv(DATA_DIR / f'kc/q_matrices/{policy_name}.csv')
    kc_columns = [column for column in q_matrix if column != 'item_id']
    edge_count = int(q_matrix[kc_columns].to_numpy().sum()) if kc_columns else 0
    policy_summary_rows.append({
        'representation': policy_name,
        'policy_id': policy['policy_id'],
        'items': len(q_matrix),
        'KCs': len(kc_columns),
        'Q_edges': edge_count,
        'Q_density': edge_count / (len(q_matrix) * len(kc_columns)) if kc_columns else 0.0,
        'KCs_per_item': edge_count / len(q_matrix),
        'uncovered_items': int(q_matrix[kc_columns].sum(axis=1).eq(0).sum()) if kc_columns else len(q_matrix),
    })
    declared_kcs = policy.get('kcs', [
        {
            'id': kc_id,
            'definition': policy['description'],
            'activation': {'generated_by': policy.get('kc_id_pattern', policy.get('kind', 'declared_pattern'))},
        }
        for kc_id in kc_columns
    ])
    for kc in declared_kcs:
        policy_kc_rows.append({
            'representation': policy_name,
            'KC_id': kc['id'],
            'definition': kc['definition'],
            'activation': compact(kc['activation']),
        })
policy_summary = pd.DataFrame(policy_summary_rows).sort_values('KCs')
policy_kcs = pd.DataFrame(policy_kc_rows)
automated_projection = read_jsonl('kc/projections/automated.jsonl')
automated_projection['kc_ids'] = automated_projection['kc_ids'].map(compact)
automated_q_matrix = pd.read_csv(DATA_DIR / 'kc/q_matrices/automated.csv')
show_table('Frozen policy granularity and Q-matrix diagnostics', policy_summary)
show_table('KCs declared by each frozen policy', policy_kcs)
show_table('Automated item→KC projection', automated_projection)
show_table('Automated-policy Q-matrix', automated_q_matrix)

**Frozen policy granularity and Q-matrix diagnostics** — 4 row(s)

           representation                                             policy_id  items  KCs  Q_edges  Q_density  KCs_per_item  uncovered_items
0              factorized                                  medium_v1_factorized     44    9       92   0.232323      2.090909                2
1               automated             selected__forward_predictive_parsimony_v1     44   10       96   0.218182      2.181818                2
2  supported_interactions  medium_v1_factorized_plus_all_supported_interactions     44   16      127   0.180398      2.886364                2
3         oracle_all_cell                       medium_v1_oracle_exact_all_cell     44   24       44   0.041667      1.000000                0

**KCs declared by each frozen policy** — 59 row(s)

,representation,KC_id,definition,activation
0,automated,kc_feature__aspect__perfect,Represent canonical aspect=perfect.,"{""cell"": {""aspect"": ""perfect""}}"
1,automated,kc_feature__aspect__perfect_progressive,Represent canonical aspect=perfect_progressive.,"{""cell"": {""aspect"": ""perfect_progressive""}}"
2,automated,kc_feature__aspect__progressive,Represent canonical aspect=progressive.,"{""cell"": {""aspect"": ""progressive""}}"
3,automated,kc_feature__clause__imperative,Represent canonical clause=imperative.,"{""cell"": {""clause"": ""imperative""}}"
4,automated,kc_feature__clause__polar_question,Represent canonical clause=polar_question.,"{""cell"": {""clause"": ""polar_question""}}"
5,automated,kc_feature__polarity__negative,Represent canonical polarity=negative.,"{""cell"": {""polarity"": ""negative""}}"
6,automated,kc_feature__tense__past,Represent canonical tense=past.,"{""cell"": {""tense"": ""past""}}"
7,automated,kc_feature__tense__present,Represent canonical tense=present.,"{""cell"": {""tense"": ""present""}}"
8,automated,kc_feature__voice__passive,Represent canonical voice=passive.,"{""cell"": {""voice"": ""passive""}}"
9,automated,kc_interaction__aspect_perfect__and__polarity_negative,Represent the supported interaction aspect=perfect and polarity=negative.,"{""cell"": {""aspect"": ""perfect"", ""polarity"": ""negative""}}"
10,factorized,kc_feature__aspect__perfect,Represent canonical aspect=perfect.,"{""cell"": {""aspect"": ""perfect""}}"
11,factorized,kc_feature__aspect__perfect_progressive,Represent canonical aspect=perfect_progressive.,"{""cell"": {""aspect"": ""perfect_progressive""}}"
12,factorized,kc_feature__aspect__progressive,Represent canonical aspect=progressive.,"{""cell"": {""aspect"": ""progressive""}}"
13,factorized,kc_feature__clause__imperative,Represent canonical clause=imperative.,"{""cell"": {""clause"": ""imperative""}}"
14,factorized,kc_feature__clause__polar_question,Represent canonical clause=polar_question.,"{""cell"": {""clause"": ""polar_question""}}"
15,factorized,kc_feature__polarity__negative,Represent canonical polarity=negative.,"{""cell"": {""polarity"": ""negative""}}"
16,factorized,kc_feature__tense__past,Represent canonical tense=past.,"{""cell"": {""tense"": ""past""}}"
17,factorized,kc_feature__tense__present,Represent canonical tense=present.,"{""cell"": {""tense"": ""present""}}"
18,factorized,kc_feature__voice__passive,Represent canonical voice=passive.,"{""cell"": {""voice"": ""passive""}}"
19,oracle_all_cell,kc_oracle_cell__cell_001,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
20,oracle_all_cell,kc_oracle_cell__cell_002,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
21,oracle_all_cell,kc_oracle_cell__cell_003,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
22,oracle_all_cell,kc_oracle_cell__cell_004,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
23,oracle_all_cell,kc_oracle_cell__cell_005,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
24,oracle_all_cell,kc_oracle_cell__cell_006,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
25,oracle_all_cell,kc_oracle_cell__cell_007,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
26,oracle_all_cell,kc_oracle_cell__cell_008,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
27,oracle_all_cell,kc_oracle_cell__cell_009,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
28,oracle_all_cell,kc_oracle_cell__cell_010,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
29,oracle_all_cell,kc_oracle_cell__cell_011,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
30,oracle_all_cell,kc_oracle_cell__cell_012,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
31,oracle_all_cell,kc_oracle_cell__cell_013,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
32,oracle_all_cell,kc_oracle_cell__cell_014,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
33,oracle_all_cell,kc_oracle_cell__cell_015,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
34,oracle_all_cell,kc_oracle_cell__cell_016,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
35,oracle_all_cell,kc_oracle_cell__cell_017,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
36,oracle_all_cell,kc_oracle_cell__cell_018,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
37,oracle_all_cell,kc_oracle_cell__cell_019,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
38,oracle_all_cell,kc_oracle_cell__cell_020,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
39,oracle_all_cell,kc_oracle_cell__cell_021,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
40,oracle_all_cell,kc_oracle_cell__cell_022,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
41,oracle_all_cell,kc_oracle_cell__cell_023,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
42,oracle_all_cell,kc_oracle_cell__cell_024,"Labelled oracle structural extreme with one KC for every exact cell, including evaluation cells; never available to ...","{""generated_by"": ""kc_oracle_cell__{cell_id}""}"
43,supported_interactions,kc_feature__aspect__perfect,Represent canonical aspect=perfect.,"{""cell"": {""aspect"": ""perfect""}}"
44,supported_interactions,kc_feature__aspect__perfect_progressive,Represent canonical aspect=perfect_progressive.,"{""cell"": {""aspect"": ""perfect_progressive""}}"
45,supported_interactions,kc_feature__aspect__progressive,Represent canonical aspect=progressive.,"{""cell"": {""aspect"": ""progressive""}}"
46,supported_interactions,kc_feature__clause__imperative,Represent canonical clause=imperative.,"{""cell"": {""clause"": ""imperative""}}"
47,supported_interactions,kc_feature__clause__polar_question,Represent canonical clause=polar_question.,"{""cell"": {""clause"": ""polar_question""}}"
48,supported_interactions,kc_feature__polarity__negative,Represent canonical polarity=negative.,"{""cell"": {""polarity"": ""negative""}}"
49,supported_interactions,kc_feature__tense__past,Represent canonical tense=past.,"{""cell"": {""tense"": ""past""}}"
50,supported_interactions,kc_feature__tense__present,Represent canonical tense=present.,"{""cell"": {""tense"": ""present""}}"
51,supported_interactions,kc_feature__voice__passive,Represent canonical voice=passive.,"{""cell"": {""voice"": ""passive""}}"
52,supported_interactions,kc_interaction__aspect_perfect__and__polarity_negative,Represent the supported interaction aspect=perfect and polarity=negative.,"{""cell"": {""aspect"": ""perfect"", ""polarity"": ""negative""}}"
53,supported_interactions,kc_interaction__aspect_perfect__and__tense_past,Represent the supported interaction aspect=perfect and tense=past.,"{""cell"": {""aspect"": ""perfect"", ""tense"": ""past""}}"
54,supported_interactions,kc_interaction__aspect_perfect__and__tense_present,Represent the supported interaction aspect=perfect and tense=present.,"{""cell"": {""aspect"": ""perfect"", ""tense"": ""present""}}"
55,supported_interactions,kc_interaction__aspect_perfect_progressive__and__tense_past,Represent the supported interaction aspect=perfect_progressive and tense=past.,"{""cell"": {""aspect"": ""perfect_progressive"", ""tense"": ""past""}}"
56,supported_interactions,kc_interaction__polarity_negative__and__tense_past,Represent the supported interaction polarity=negative and tense=past.,"{""cell"": {""polarity"": ""negative"", ""tense"": ""past""}}"
57,supported_interactions,kc_interaction__polarity_negative__and__tense_present,Represent the supported interaction polarity=negative and tense=present.,"{""cell"": {""polarity"": ""negative"", ""tense"": ""present""}}"
58,supported_interactions,kc_interaction__tense_present__and__voice_passive,Represent the supported interaction tense=present and voice=passive.,"{""cell"": {""tense"": ""present"", ""voice"": ""passive""}}"

**Automated item→KC projection** — 44 row(s)

                  item_id                                                                                                                   kc_ids
0   candidate_cell_001_01                                                     ["kc_feature__clause__polar_question", "kc_feature__tense__present"]
1   candidate_cell_001_02                                                     ["kc_feature__clause__polar_question", "kc_feature__tense__present"]
2   candidate_cell_002_01                                                        ["kc_feature__clause__polar_question", "kc_feature__tense__past"]
3   candidate_cell_002_03                                                        ["kc_feature__clause__polar_question", "kc_feature__tense__past"]
4   candidate_cell_003_01                                                                                           ["kc_feature__tense__present"]
5   candidate_cell_003_03                                                                                           ["kc_feature__tense__present"]
6   candidate_cell_004_01                                                                                              ["kc_feature__tense__past"]
7   candidate_cell_004_02                                                                                              ["kc_feature__tense__past"]
8   candidate_cell_005_03                                                                                       ["kc_feature__clause__imperative"]
9   candidate_cell_006_01                                                     ["kc_feature__clause__imperative", "kc_feature__polarity__negative"]
10  candidate_cell_006_03                                                     ["kc_feature__clause__imperative", "kc_feature__polarity__negative"]
11  candidate_cell_007_01                                                         ["kc_feature__polarity__negative", "kc_feature__tense__present"]
12  candidate_cell_007_02                                                         ["kc_feature__polarity__negative", "kc_feature__tense__present"]
13  candidate_cell_008_01                                                        ["kc_feature__aspect__progressive", "kc_feature__tense__present"]
14  candidate_cell_008_02                                                        ["kc_feature__aspect__progressive", "kc_feature__tense__present"]
15  candidate_cell_009_01                      ["kc_feature__aspect__progressive", "kc_feature__polarity__negative", "kc_feature__tense__present"]
16  candidate_cell_009_02                      ["kc_feature__aspect__progressive", "kc_feature__polarity__negative", "kc_feature__tense__present"]
17  candidate_cell_010_01                                                            ["kc_feature__polarity__negative", "kc_feature__tense__past"]
18  candidate_cell_010_03                                                            ["kc_feature__polarity__negative", "kc_feature__tense__past"]
19  candidate_cell_011_01                                                           ["kc_feature__aspect__progressive", "kc_feature__tense__past"]
20  candidate_cell_011_03                                                           ["kc_feature__aspect__progressive", "kc_feature__tense__past"]
21  candidate_cell_012_01  ["kc_feature__aspect__perfect", "kc_feature__polarity__negative", "kc_feature__tense__present", "kc_interaction__asp...
22  candidate_cell_012_02  ["kc_feature__aspect__perfect", "kc_feature__polarity__negative", "kc_feature__tense__present", "kc_interaction__asp...
23  candidate_cell_013_01                                                            ["kc_feature__aspect__perfect", "kc_feature__tense__present"]
24  candidate_cell_013_02                                                            ["kc_feature__aspect__perfect", "kc_feature__tense__present"]
25  candidate_cell_014_01  ["kc_feature__aspect__perfect", "kc_feature__polarity__negative", "kc_feature__tense__past", "kc_interaction__aspect...
26  candidate_cell_014_03  ["kc_feature__aspect__perfect", "kc_feature__polarity__negative", "kc_feature__tense__past", "kc_interaction__aspect...
27  candidate_cell_015_03                                                               ["kc_feature__aspect__perfect", "kc_feature__tense__past"]
28  candidate_cell_016_01                                                ["kc_feature__aspect__perfect_progressive", "kc_feature__tense__present"]
29  candidate_cell_016_02                                                ["kc_feature__aspect__perfect_progressive", "kc_feature__tense__present"]
30  candidate_cell_017_06                 ["kc_feature__aspect__perfect_progressive", "kc_feature__polarity__negative", "kc_feature__tense__past"]
31  candidate_cell_017_07                 ["kc_feature__aspect__perfect_progressive", "kc_feature__polarity__negative", "kc_feature__tense__past"]
32  candidate_cell_018_03                                                   ["kc_feature__aspect__perfect_progressive", "kc_feature__tense__past"]
33  candidate_cell_019_02                                                                ["kc_feature__tense__past", "kc_feature__voice__passive"]
34  candidate_cell_019_03                                                                ["kc_feature__tense__past", "kc_feature__voice__passive"]
35  candidate_cell_020_01                                                             ["kc_feature__tense__present", "kc_feature__voice__passive"]
36  candidate_cell_020_03                                                             ["kc_feature__tense__present", "kc_feature__voice__passive"]
37  candidate_cell_021_01                          ["kc_feature__aspect__progressive", "kc_feature__tense__present", "kc_feature__voice__passive"]
38  candidate_cell_021_03                          ["kc_feature__aspect__progressive", "kc_feature__tense__present", "kc_feature__voice__passive"]
39  candidate_cell_022_05                                 ["kc_feature__aspect__perfect", "kc_feature__tense__past", "kc_feature__voice__passive"]
40  candidate_cell_023_02                           ["kc_feature__polarity__negative", "kc_feature__tense__present", "kc_feature__voice__passive"]
41  candidate_cell_023_03                           ["kc_feature__polarity__negative", "kc_feature__tense__present", "kc_feature__voice__passive"]
42  candidate_cell_024_02                                                                                                                       []
43  candidate_cell_024_03                                                                                                                       []

**Automated-policy Q-matrix** — 44 row(s)

,item_id,kc_feature__aspect__perfect,kc_feature__aspect__perfect_progressive,kc_feature__aspect__progressive,kc_feature__clause__imperative,kc_feature__clause__polar_question,kc_feature__polarity__negative,kc_feature__tense__past,kc_feature__tense__present,kc_feature__voice__passive,kc_interaction__aspect_perfect__and__polarity_negative
0,candidate_cell_001_01,0,0,0,0,1,0,0,1,0,0
1,candidate_cell_001_02,0,0,0,0,1,0,0,1,0,0
2,candidate_cell_002_01,0,0,0,0,1,0,1,0,0,0
3,candidate_cell_002_03,0,0,0,0,1,0,1,0,0,0
4,candidate_cell_003_01,0,0,0,0,0,0,0,1,0,0
5,candidate_cell_003_03,0,0,0,0,0,0,0,1,0,0
6,candidate_cell_004_01,0,0,0,0,0,0,1,0,0,0
7,candidate_cell_004_02,0,0,0,0,0,0,1,0,0,0
8,candidate_cell_005_03,0,0,0,1,0,0,0,0,0,0
9,candidate_cell_006_01,0,0,0,1,0,1,0,0,0,0
10,candidate_cell_006_03,0,0,0,1,0,1,0,0,0,0
11,candidate_cell_007_01,0,0,0,0,0,1,0,1,0,0
12,candidate_cell_007_02,0,0,0,0,0,1,0,1,0,0
13,candidate_cell_008_01,0,0,1,0,0,0,0,1,0,0
14,candidate_cell_008_02,0,0,1,0,0,0,0,1,0,0
15,candidate_cell_009_01,0,0,1,0,0,1,0,1,0,0
16,candidate_cell_009_02,0,0,1,0,0,1,0,1,0,0
17,candidate_cell_010_01,0,0,0,0,0,1,1,0,0,0
18,candidate_cell_010_03,0,0,0,0,0,1,1,0,0,0
19,candidate_cell_011_01,0,0,1,0,0,0,1,0,0,0
20,candidate_cell_011_03,0,0,1,0,0,0,1,0,0,0
21,candidate_cell_012_01,1,0,0,0,0,1,0,1,0,1
22,candidate_cell_012_02,1,0,0,0,0,1,0,1,0,1
23,candidate_cell_013_01,1,0,0,0,0,0,0,1,0,0
24,candidate_cell_013_02,1,0,0,0,0,0,0,1,0,0
25,candidate_cell_014_01,1,0,0,0,0,1,1,0,0,1
26,candidate_cell_014_03,1,0,0,0,0,1,1,0,0,1
27,candidate_cell_015_03,1,0,0,0,0,0,1,0,0,0
28,candidate_cell_016_01,0,1,0,0,0,0,0,1,0,0
29,candidate_cell_016_02,0,1,0,0,0,0,0,1,0,0
30,candidate_cell_017_06,0,1,0,0,0,1,1,0,0,0
31,candidate_cell_017_07,0,1,0,0,0,1,1,0,0,0
32,candidate_cell_018_03,0,1,0,0,0,0,1,0,0,0
33,candidate_cell_019_02,0,0,0,0,0,0,1,0,1,0
34,candidate_cell_019_03,0,0,0,0,0,0,1,0,1,0
35,candidate_cell_020_01,0,0,0,0,0,0,0,1,1,0
36,candidate_cell_020_03,0,0,0,0,0,0,0,1,1,0
37,candidate_cell_021_01,0,0,1,0,0,0,0,1,1,0
38,candidate_cell_021_03,0,0,1,0,0,0,0,1,1,0
39,candidate_cell_022_05,1,0,0,0,0,0,1,0,1,0
40,candidate_cell_023_02,0,0,0,0,0,1,0,1,1,0
41,candidate_cell_023_03,0,0,0,0,0,1,0,1,1,0
42,candidate_cell_024_02,0,0,0,0,0,0,0,0,0,0
43,candidate_cell_024_03,0,0,0,0,0,0,0,0,0,0

,item_id,kc_feature__aspect__perfect,kc_feature__aspect__perfect_progressive,kc_feature__aspect__progressive,kc_feature__clause__imperative,kc_feature__clause__polar_question,kc_feature__polarity__negative,kc_feature__tense__past,kc_feature__tense__present,kc_feature__voice__passive,kc_interaction__aspect_perfect__and__polarity_negative
0,candidate_cell_001_01,0,0,0,0,1,0,0,1,0,0
1,candidate_cell_001_02,0,0,0,0,1,0,0,1,0,0
2,candidate_cell_002_01,0,0,0,0,1,0,1,0,0,0
3,candidate_cell_002_03,0,0,0,0,1,0,1,0,0,0
4,candidate_cell_003_01,0,0,0,0,0,0,0,1,0,0
5,candidate_cell_003_03,0,0,0,0,0,0,0,1,0,0
6,candidate_cell_004_01,0,0,0,0,0,0,1,0,0,0
7,candidate_cell_004_02,0,0,0,0,0,0,1,0,0,0
8,candidate_cell_005_03,0,0,0,1,0,0,0,0,0,0
9,candidate_cell_006_01,0,0,0,1,0,1,0,0,0,0
10,candidate_cell_006_03,0,0,0,1,0,1,0,0,0,0
11,candidate_cell_007_01,0,0,0,0,0,1,0,1,0,0
12,candidate_cell_007_02,0,0,0,0,0,1,0,1,0,0
13,candidate_cell_008_01,0,0,1,0,0,0,0,1,0,0
14,candidate_cell_008_02,0,0,1,0,0,0,0,1,0,0
15,candidate_cell_009_01,0,0,1,0,0,1,0,1,0,0
16,candidate_cell_009_02,0,0,1,0,0,1,0,1,0,0
17,candidate_cell_010_01,0,0,0,0,0,1,1,0,0,0
18,candidate_cell_010_03,0,0,0,0,0,1,1,0,0,0
19,candidate_cell_011_01,0,0,1,0,0,0,1,0,0,0
20,candidate_cell_011_03,0,0,1,0,0,0,1,0,0,0
21,candidate_cell_012_01,1,0,0,0,0,1,0,1,0,1
22,candidate_cell_012_02,1,0,0,0,0,1,0,1,0,1
23,candidate_cell_013_01,1,0,0,0,0,0,0,1,0,0
24,candidate_cell_013_02,1,0,0,0,0,0,0,1,0,0
25,candidate_cell_014_01,1,0,0,0,0,1,1,0,0,1
26,candidate_cell_014_03,1,0,0,0,0,1,1,0,0,1
27,candidate_cell_015_03,1,0,0,0,0,0,1,0,0,0
28,candidate_cell_016_01,0,1,0,0,0,0,0,1,0,0
29,candidate_cell_016_02,0,1,0,0,0,0,0,1,0,0
30,candidate_cell_017_06,0,1,0,0,0,1,1,0,0,0
31,candidate_cell_017_07,0,1,0,0,0,1,1,0,0,0
32,candidate_cell_018_03,0,1,0,0,0,0,1,0,0,0
33,candidate_cell_019_02,0,0,0,0,0,0,1,0,1,0
34,candidate_cell_019_03,0,0,0,0,0,0,1,0,1,0
35,candidate_cell_020_01,0,0,0,0,0,0,0,1,1,0
36,candidate_cell_020_03,0,0,0,0,0,0,0,1,1,0
37,candidate_cell_021_01,0,0,1,0,0,0,0,1,1,0
38,candidate_cell_021_03,0,0,1,0,0,0,0,1,1,0
39,candidate_cell_022_05,1,0,0,0,0,0,1,0,1,0
40,candidate_cell_023_02,0,0,0,0,0,1,0,1,1,0
41,candidate_cell_023_03,0,0,0,0,0,1,0,1,1,0
42,candidate_cell_024_02,0,0,0,0,0,0,0,0,0,0
43,candidate_cell_024_03,0,0,0,0,0,0,0,0,0,0

## 11. Online knowledge-tracing predictions

Each representation is evaluated with empirical, BKT, and observable logistic KT predictions over the same 204,000 learner events. To keep the notebook responsive, only the automated prediction file is loaded fully; the other retained files are inventoried and their aggregate metrics are read in the evaluation stage.

In [14]:
prediction_artifacts = []
for prediction_path in sorted((DATA_DIR / 'kt').glob('*/predictions.jsonl.gz')):
    representation = prediction_path.parent.name
    result_path = DATA_DIR / f'evaluation/{representation}/results.json'
    expected_rows = read_json(f'evaluation/{representation}/results.json')['input_counts']['predictions'] if result_path.is_file() else pd.NA
    prediction_artifacts.append({
        'representation': representation,
        'relative_path': str(prediction_path.relative_to(DATA_DIR)),
        'compressed_size_bytes': prediction_path.stat().st_size,
        'prediction_rows': expected_rows,
        'techniques': 3,
    })
prediction_artifact_table = pd.DataFrame(prediction_artifacts)
automated_predictions = read_jsonl('kt/automated/predictions.jsonl.gz')
prediction_summary = automated_predictions.groupby('technique').agg(
    predictions=('event_id', 'size'),
    events=('event_id', 'nunique'),
    mean_probability=('probability', 'mean'),
    minimum_probability=('probability', 'min'),
    maximum_probability=('probability', 'max'),
    median_history_events=('history_events', 'median'),
).reset_index()
prediction_sample = automated_predictions.groupby('technique', group_keys=False).head(PREDICTION_SAMPLE_ROWS_PER_TECHNIQUE)
prediction_sample = prediction_sample.merge(
    events[['event_id', 'learner_id', 'item_id', 'correct', 'dataset_split', 'grammar_split', 'protocol_phase']],
    on='event_id', how='left',
)
show_table('Retained KT prediction artifacts', prediction_artifact_table)
show_table('Automated-policy prediction summary by KT technique', prediction_summary)
show_table('Automated-policy prediction sample joined to learner events', prediction_sample, limit=len(prediction_sample))

**Retained KT prediction artifacts** — 4 row(s)

           representation                                   relative_path  compressed_size_bytes  prediction_rows  techniques
0               automated               kt/automated/predictions.jsonl.gz                7605964           612000           3
1              factorized              kt/factorized/predictions.jsonl.gz                7586675           612000           3
2         oracle_all_cell         kt/oracle_all_cell/predictions.jsonl.gz                5711641           612000           3
3  supported_interactions  kt/supported_interactions/predictions.jsonl.gz                7703013           612000           3

**Automated-policy prediction summary by KT technique** — 3 row(s)

   technique  predictions  events  mean_probability  minimum_probability  maximum_probability  median_history_events
0        bkt       204000  204000          0.777030             0.278400             0.900000                  101.5
1  empirical       204000  204000          0.539104             0.052632             0.916667                  101.5
2   logistic       204000  204000          0.599674             0.290747             0.724745                  101.5

**Automated-policy prediction sample joined to learner events** — 24 row(s)

         event_id  history_events  probability  technique   learner_id                item_id  correct dataset_split grammar_split protocol_phase
0   event_0000001               0     0.500000  empirical  learner_001  candidate_cell_001_01        0         train   development    acquisition
1   event_0000002               1     0.333333  empirical  learner_001  candidate_cell_001_02        0         train   development    acquisition
2   event_0000003               2     0.375000  empirical  learner_001  candidate_cell_002_01        0         train   development    acquisition
3   event_0000004               3     0.266667  empirical  learner_001  candidate_cell_002_03        1         train   development    acquisition
4   event_0000005               4     0.250000  empirical  learner_001  candidate_cell_003_01        1         train   development    acquisition
5   event_0000006               5     0.400000  empirical  learner_001  candidate_cell_003_03        1         train   development    acquisition
6   event_0000007               6     0.500000  empirical  learner_001  candidate_cell_004_01        1         train   development    acquisition
7   event_0000008               7     0.600000  empirical  learner_001  candidate_cell_004_02        0         train   development    acquisition
8   event_0000001               0     0.432000        bkt  learner_001  candidate_cell_001_01        0         train   development    acquisition
9   event_0000002               1     0.305442        bkt  learner_001  candidate_cell_001_02        0         train   development    acquisition
10  event_0000003               2     0.357147        bkt  learner_001  candidate_cell_002_01        0         train   development    acquisition
11  event_0000004               3     0.292192        bkt  learner_001  candidate_cell_002_03        1         train   development    acquisition
12  event_0000005               4     0.282293        bkt  learner_001  candidate_cell_003_01        1         train   development    acquisition
13  event_0000006               5     0.553394        bkt  learner_001  candidate_cell_003_03        1         train   development    acquisition
14  event_0000007               6     0.591667        bkt  learner_001  candidate_cell_004_01        1         train   development    acquisition
15  event_0000008               7     0.817454        bkt  learner_001  candidate_cell_004_02        0         train   development    acquisition
16  event_0000001               0     0.393343   logistic  learner_001  candidate_cell_001_01        0         train   development    acquisition
17  event_0000002               1     0.431398   logistic  learner_001  candidate_cell_001_02        0         train   development    acquisition
18  event_0000003               2     0.438969   logistic  learner_001  candidate_cell_002_01        0         train   development    acquisition
19  event_0000004               3     0.467550   logistic  learner_001  candidate_cell_002_03        1         train   development    acquisition
20  event_0000005               4     0.443953   logistic  learner_001  candidate_cell_003_01        1         train   development    acquisition
21  event_0000006               5     0.472182   logistic  learner_001  candidate_cell_003_03        1         train   development    acquisition
22  event_0000007               6     0.473911   logistic  learner_001  candidate_cell_004_01        1         train   development    acquisition
23  event_0000008               7     0.499537   logistic  learner_001  candidate_cell_004_02        0         train   development    acquisition

         event_id  history_events  probability  technique   learner_id                item_id  correct dataset_split grammar_split protocol_phase
0   event_0000001               0     0.500000  empirical  learner_001  candidate_cell_001_01        0         train   development    acquisition
1   event_0000002               1     0.333333  empirical  learner_001  candidate_cell_001_02        0         train   development    acquisition
2   event_0000003               2     0.375000  empirical  learner_001  candidate_cell_002_01        0         train   development    acquisition
3   event_0000004               3     0.266667  empirical  learner_001  candidate_cell_002_03        1         train   development    acquisition
4   event_0000005               4     0.250000  empirical  learner_001  candidate_cell_003_01        1         train   development    acquisition
5   event_0000006               5     0.400000  empirical  learner_001  candidate_cell_003_03        1         train   development    acquisition
6   event_0000007               6     0.500000  empirical  learner_001  candidate_cell_004_01        1         train   development    acquisition
7   event_0000008               7     0.600000  empirical  learner_001  candidate_cell_004_02        0         train   development    acquisition
8   event_0000001               0     0.432000        bkt  learner_001  candidate_cell_001_01        0         train   development    acquisition
9   event_0000002               1     0.305442        bkt  learner_001  candidate_cell_001_02        0         train   development    acquisition
10  event_0000003               2     0.357147        bkt  learner_001  candidate_cell_002_01        0         train   development    acquisition
11  event_0000004               3     0.292192        bkt  learner_001  candidate_cell_002_03        1         train   development    acquisition
12  event_0000005               4     0.282293        bkt  learner_001  candidate_cell_003_01        1         train   development    acquisition
13  event_0000006               5     0.553394        bkt  learner_001  candidate_cell_003_03        1         train   development    acquisition
14  event_0000007               6     0.591667        bkt  learner_001  candidate_cell_004_01        1         train   development    acquisition
15  event_0000008               7     0.817454        bkt  learner_001  candidate_cell_004_02        0         train   development    acquisition
16  event_0000001               0     0.393343   logistic  learner_001  candidate_cell_001_01        0         train   development    acquisition
17  event_0000002               1     0.431398   logistic  learner_001  candidate_cell_001_02        0         train   development    acquisition
18  event_0000003               2     0.438969   logistic  learner_001  candidate_cell_002_01        0         train   development    acquisition
19  event_0000004               3     0.467550   logistic  learner_001  candidate_cell_002_03        1         train   development    acquisition
20  event_0000005               4     0.443953   logistic  learner_001  candidate_cell_003_01        1         train   development    acquisition
21  event_0000006               5     0.472182   logistic  learner_001  candidate_cell_003_03        1         train   development    acquisition
22  event_0000007               6     0.473911   logistic  learner_001  candidate_cell_004_01        1         train   development    acquisition
23  event_0000008               7     0.499537   logistic  learner_001  candidate_cell_004_02        0         train   development    acquisition

## 12. Predictive evaluation and learner-paired uncertainty

The long metrics table holds representation fixed within each row and reports empirical, BKT, and logistic results overall and by grammar regime. The paired table fixes logistic KT and bootstraps learners; negative candidate-minus-reference deltas favor the candidate.

In [15]:
representation_rows = []
metric_rows = []
for result_path in sorted((DATA_DIR / 'evaluation').glob('*/results.json')):
    representation_name = result_path.parent.name
    result = read_json(f'evaluation/{representation_name}/results.json')
    representation_rows.append({'representation': representation_name, **{
        key: compact(value) for key, value in result['representation'].items() if key != 'kc_support'
    }})
    for technique, technique_metrics in result['kt'].items():
        overall = {key: technique_metrics[key] for key in ('n', 'log_loss', 'brier_score', 'auc', 'ece', 'accuracy')}
        metric_rows.append({'representation': representation_name, 'technique': technique, 'grammar_regime': 'all_test', **overall})
        for grammar_regime, regime_metrics in technique_metrics['grammar_split_metrics'].items():
            metric_rows.append({'representation': representation_name, 'technique': technique, 'grammar_regime': grammar_regime, **regime_metrics})
representation_results = pd.DataFrame(representation_rows).sort_values('kcs')
kt_metrics = pd.DataFrame(metric_rows).sort_values(['technique', 'grammar_regime', 'log_loss'])
paired = read_json('evaluation/paired_logistic.json')
paired_rows = pd.DataFrame([
    {
        'grammar_regime': row['grammar_regime'],
        'reference': row['reference'],
        'candidate': row['candidate'],
        'learners': row['n_learners'],
        'events': row['n_events'],
        'delta_log_loss': row['delta_log_loss']['point_estimate'],
        'log_loss_CI_low': row['delta_log_loss']['interval_95'][0],
        'log_loss_CI_high': row['delta_log_loss']['interval_95'][1],
        'delta_Brier': row['delta_brier_score']['point_estimate'],
        'Brier_CI_low': row['delta_brier_score']['interval_95'][0],
        'Brier_CI_high': row['delta_brier_score']['interval_95'][1],
        'interval_excludes_zero': not (row['delta_log_loss']['interval_95'][0] <= 0 <= row['delta_log_loss']['interval_95'][1]),
    }
    for row in paired['comparisons'] if row['available']
])
show_table('Representation granularity and coverage results', representation_results)
show_table('KT metrics by representation, technique, and grammar regime', kt_metrics)
show_table('Fixed-logistic learner-cluster paired comparisons', paired_rows.sort_values(['grammar_regime', 'reference', 'candidate']))

**Representation granularity and coverage results** — 4 row(s)

,representation,policy_id,items,kcs,item_coverage,event_coverage,q_matrix_density,kcs_per_item,redundant_kcs,compositional_coverage
0,factorized,medium_v1_factorized,44,9,0.954545,0.990196,0.232323,2.090909,[],1.0
1,automated,selected__forward_predictive_parsimony_v1,44,10,0.954545,0.990196,0.218182,2.181818,[],1.0
2,supported_interactions,medium_v1_factorized_plus_all_supported_interactions,44,16,0.954545,0.990196,0.180398,2.886364,[],1.0
3,oracle_all_cell,medium_v1_oracle_exact_all_cell,44,24,1.000000,1.000000,0.041667,1.000000,[],0.0

**KT metrics by representation, technique, and grammar regime** — 48 row(s)

            representation  technique         grammar_regime      n  log_loss  brier_score       auc       ece  accuracy
0          oracle_all_cell        bkt               all_test  44000  0.772235     0.270253  0.529215  0.193087  0.562977
1   supported_interactions        bkt               all_test  44000  0.817456     0.275769  0.542285  0.213057  0.641795
2                automated        bkt               all_test  44000  0.826163     0.277927  0.543480  0.219361  0.642295
3               factorized        bkt               all_test  44000  0.827526     0.278252  0.543681  0.220417  0.642295
4          oracle_all_cell        bkt  compositional_holdout  10000  0.740744     0.273637  0.500000  0.207800  0.360200
5   supported_interactions        bkt  compositional_holdout  10000  0.843014     0.284479  0.534308  0.228685  0.638800
6                automated        bkt  compositional_holdout  10000  0.855793     0.287766  0.537843  0.235326  0.639600
7               factorized        bkt  compositional_holdout  10000  0.855793     0.287766  0.537843  0.235326  0.639600
8          oracle_all_cell        bkt            development  32000  0.788000     0.270950  0.516063  0.202027  0.624563
9   supported_interactions        bkt            development  32000  0.813955     0.273055  0.518088  0.213981  0.657125
10               automated        bkt            development  32000  0.821935     0.274995  0.518841  0.219645  0.657563
11              factorized        bkt            development  32000  0.823809     0.275441  0.518686  0.221081  0.657563
12         oracle_all_cell        bkt  novel_feature_holdout   2000  0.677439     0.242180  0.500000  0.023500  0.591500
13               automated        bkt  novel_feature_holdout   2000  0.745673     0.275650  0.500863  0.179741  0.411500
14              factorized        bkt  novel_feature_holdout   2000  0.745673     0.275650  0.500863  0.179741  0.411500
15  supported_interactions        bkt  novel_feature_holdout   2000  0.745673     0.275650  0.500863  0.179741  0.411500
16              factorized  empirical               all_test  44000  0.664682     0.235905  0.514222  0.063439  0.618614
17               automated  empirical               all_test  44000  0.664990     0.236055  0.513776  0.063902  0.617386
18  supported_interactions  empirical               all_test  44000  0.666122     0.236626  0.515894  0.066501  0.611705
19         oracle_all_cell  empirical               all_test  44000  0.692836     0.248658  0.521338  0.115200  0.597841
20               automated  empirical  compositional_holdout  10000  0.664317     0.235749  0.528177  0.066687  0.615800
21              factorized  empirical  compositional_holdout  10000  0.664317     0.235749  0.528177  0.066687  0.615800
22  supported_interactions  empirical  compositional_holdout  10000  0.666068     0.236626  0.531088  0.072139  0.609600
23         oracle_all_cell  empirical  compositional_holdout  10000  0.693147     0.250000  0.500000  0.139800  0.639800
24              factorized  empirical            development  32000  0.659733     0.233470  0.512841  0.077622  0.632437
25               automated  empirical            development  32000  0.660157     0.233677  0.512464  0.078259  0.630750
26  supported_interactions  empirical            development  32000  0.661166     0.234187  0.514944  0.080130  0.624875
27         oracle_all_cell  empirical            development  32000  0.692719     0.248154  0.516132  0.120431  0.596562
28         oracle_all_cell  empirical  novel_feature_holdout   2000  0.693147     0.250000  0.500000  0.091500  0.408500
29               automated  empirical  novel_feature_holdout   2000  0.745673     0.275650  0.500863  0.179741  0.411500
30              factorized  empirical  novel_feature_holdout   2000  0.745673     0.275650  0.500863  0.179741  0.411500
31  supported_interactions  empirical  novel_feature_holdout   2000  0.745673     0.275650  0.500863  0.179741  0.411500
32  supported_interactions   logistic               all_test  44000  0.643334     0.225596  0.565039  0.002725  0.651136
33               automated   logistic               all_test  44000  0.643356     0.225610  0.564123  0.004399  0.651136
34              factorized   logistic               all_test  44000  0.643731     0.225775  0.560356  0.003364  0.651136
35         oracle_all_cell   logistic               all_test  44000  0.657507     0.232565  0.545882  0.041291  0.587591
36  supported_interactions   logistic  compositional_holdout  10000  0.647561     0.227685  0.564529  0.004967  0.639800
37               automated   logistic  compositional_holdout  10000  0.648495     0.228126  0.556192  0.008122  0.639800
38              factorized   logistic  compositional_holdout  10000  0.648729     0.228217  0.558663  0.006941  0.639800
39         oracle_all_cell   logistic  compositional_holdout  10000  0.708344     0.257592  0.506943  0.164778  0.360200
40               automated   logistic            development  32000  0.639669     0.223812  0.539878  0.002748  0.658406
41         oracle_all_cell   logistic            development  32000  0.639885     0.223900  0.540051  0.009440  0.658406
42  supported_interactions   logistic            development  32000  0.639943     0.223937  0.539824  0.003425  0.658406
43              factorized   logistic            development  32000  0.640119     0.224015  0.535833  0.002124  0.658406
44  supported_interactions   logistic  novel_feature_holdout   2000  0.676451     0.241697  0.500863  0.007382  0.591500
45              factorized   logistic  novel_feature_holdout   2000  0.676523     0.241731  0.500863  0.009663  0.591500
46               automated   logistic  novel_feature_holdout   2000  0.676642     0.241788  0.500863  0.012193  0.591500
47         oracle_all_cell   logistic  novel_feature_holdout   2000  0.685272     0.246066  0.500863  0.066522  0.591500

**Fixed-logistic learner-cluster paired comparisons** — 12 row(s)

,grammar_regime,reference,candidate,learners,events,delta_log_loss,log_loss_CI_low,log_loss_CI_high,delta_Brier,Brier_CI_low,Brier_CI_high,interval_excludes_zero
0,all_test,factorized,automated,1000,44000,-0.000375,-0.000631,-0.000109,-0.000166,-0.000281,-0.000046,True
1,all_test,factorized,oracle_all_cell,1000,44000,0.013777,0.012288,0.015234,0.006789,0.006070,0.007491,True
2,all_test,factorized,supported_interactions,1000,44000,-0.000397,-0.000782,-0.000026,-0.000180,-0.000356,-0.000008,True
3,compositional_holdout,factorized,automated,1000,10000,-0.000234,-0.000836,0.000375,-0.000091,-0.000372,0.000192,False
4,compositional_holdout,factorized,oracle_all_cell,1000,10000,0.059615,0.053390,0.065675,0.029375,0.026351,0.032305,True
5,compositional_holdout,factorized,supported_interactions,1000,10000,-0.001168,-0.002042,-0.000246,-0.000532,-0.000935,-0.000109,True
6,development,factorized,automated,1000,32000,-0.000450,-0.000758,-0.000141,-0.000203,-0.000339,-0.000065,True
7,development,factorized,oracle_all_cell,1000,32000,-0.000234,-0.000753,0.000271,-0.000115,-0.000348,0.000112,False
8,development,factorized,supported_interactions,1000,32000,-0.000176,-0.000605,0.000252,-0.000079,-0.000276,0.000117,False
9,novel_feature_holdout,factorized,automated,1000,2000,0.000119,-0.000099,0.000352,0.000057,-0.000047,0.000169,False
10,novel_feature_holdout,factorized,oracle_all_cell,1000,2000,0.008749,0.002039,0.015117,0.004334,0.001039,0.007464,True
11,novel_feature_holdout,factorized,supported_interactions,1000,2000,-0.000072,-0.000281,0.000128,-0.000035,-0.000135,0.000062,False

,grammar_regime,reference,candidate,learners,events,delta_log_loss,log_loss_CI_low,log_loss_CI_high,delta_Brier,Brier_CI_low,Brier_CI_high,interval_excludes_zero
0,all_test,factorized,automated,1000,44000,-0.000375,-0.000631,-0.000109,-0.000166,-0.000281,-0.000046,True
1,all_test,factorized,oracle_all_cell,1000,44000,0.013777,0.012288,0.015234,0.006789,0.006070,0.007491,True
2,all_test,factorized,supported_interactions,1000,44000,-0.000397,-0.000782,-0.000026,-0.000180,-0.000356,-0.000008,True
3,compositional_holdout,factorized,automated,1000,10000,-0.000234,-0.000836,0.000375,-0.000091,-0.000372,0.000192,False
4,compositional_holdout,factorized,oracle_all_cell,1000,10000,0.059615,0.053390,0.065675,0.029375,0.026351,0.032305,True
5,compositional_holdout,factorized,supported_interactions,1000,10000,-0.001168,-0.002042,-0.000246,-0.000532,-0.000935,-0.000109,True
6,development,factorized,automated,1000,32000,-0.000450,-0.000758,-0.000141,-0.000203,-0.000339,-0.000065,True
7,development,factorized,oracle_all_cell,1000,32000,-0.000234,-0.000753,0.000271,-0.000115,-0.000348,0.000112,False
8,development,factorized,supported_interactions,1000,32000,-0.000176,-0.000605,0.000252,-0.000079,-0.000276,0.000117,False
9,novel_feature_holdout,factorized,automated,1000,2000,0.000119,-0.000099,0.000352,0.000057,-0.000047,0.000169,False
10,novel_feature_holdout,factorized,oracle_all_cell,1000,2000,0.008749,0.002039,0.015117,0.004334,0.001039,0.007464,True
11,novel_feature_holdout,factorized,supported_interactions,1000,2000,-0.000072,-0.000281,0.000128,-0.000035,-0.000135,0.000062,False

## 13. KC-selection support and seed stability

Nested learner prefixes test evidence requirements; five independent 1,000-learner streams test full-support seed stability. This is selection stability over the fixed bank and fixed candidate inventory, not empirical learner replication.

In [16]:
stability = read_json('kc/selection_stability.json')
stability_conditions = pd.DataFrame([
    {
        'condition_id': row['condition_id'],
        'seed': row['seed'],
        'learners': row['learners'],
        'stage': row['stage'],
        'selection_events': row['selection_events'],
        'validation_events': row['selection_validation_events'],
        'KC_count': row['kc_count'],
        'addition_count': row['addition_count'],
        'selected_additions': compact(row['selected_addition_ids']),
        'exact_reference_match': row['exact_selected_inventory_match_reference'],
        'validation_log_loss': row['final_validation_score']['log_loss'],
        'objective': row['final_validation_score']['objective'],
    }
    for row in stability['selections']
])
full_support_frequencies = pd.DataFrame(stability['frequencies']['five_seed_full_support']['selected'])
if not full_support_frequencies.empty:
    full_support_frequencies['condition_ids'] = full_support_frequencies['condition_ids'].map(compact)
jaccard_summary_rows = []
for scope, summary in stability['jaccard'].items():
    for inventory_type in ('all_selected', 'additions'):
        jaccard_summary_rows.append({'scope': scope, 'inventory': inventory_type, **summary[inventory_type]})
jaccard_summary = pd.DataFrame(jaccard_summary_rows)
stability_contract = pd.DataFrame([{
    **stability['exact_inventory_matches'],
    **stability['boundary_checks'],
}])
show_table('Selection stability conditions', stability_conditions)
show_table('Full-support five-seed KC selection frequency', full_support_frequencies)
show_table('Inventory Jaccard stability', jaccard_summary)
show_table('Stability conclusions and leakage checks', stability_contract)

**Selection stability conditions** — 9 row(s)

,condition_id,seed,learners,stage,selection_events,validation_events,KC_count,addition_count,selected_additions,exact_reference_match,validation_log_loss,objective
0,seed_20260827__learners_0060,20260827,60,reference_seed_nested_support,9600,1920,10,1,"[""kc_interaction__aspect_perfect__and__polarity_negative""]",True,0.651563,0.656563
1,seed_20260827__learners_0120,20260827,120,reference_seed_nested_support,19200,3840,10,1,"[""kc_interaction__tense_present__and__voice_passive""]",False,0.652277,0.657277
2,seed_20260827__learners_0240,20260827,240,reference_seed_nested_support,38400,7680,10,1,"[""kc_interaction__aspect_perfect__and__polarity_negative""]",True,0.649995,0.654995
3,seed_20260827__learners_0500,20260827,500,reference_seed_nested_support,80000,16000,10,1,"[""kc_interaction__aspect_perfect__and__polarity_negative""]",True,0.647380,0.652380
4,seed_20260827__learners_1000,20260827,1000,reference_seed_nested_support,160000,32000,10,1,"[""kc_interaction__aspect_perfect__and__polarity_negative""]",True,0.646354,0.651354
5,seed_20260828__learners_1000,20260828,1000,full_support_seed_stability,160000,32000,10,1,"[""kc_interaction__aspect_perfect__and__polarity_negative""]",True,0.646152,0.651152
6,seed_20260829__learners_1000,20260829,1000,full_support_seed_stability,160000,32000,10,1,"[""kc_interaction__aspect_perfect__and__polarity_negative""]",True,0.644646,0.649646
7,seed_20260830__learners_1000,20260830,1000,full_support_seed_stability,160000,32000,10,1,"[""kc_interaction__aspect_perfect__and__polarity_negative""]",True,0.648254,0.653254
8,seed_20260831__learners_1000,20260831,1000,full_support_seed_stability,160000,32000,10,1,"[""kc_interaction__aspect_perfect__and__polarity_negative""]",True,0.646378,0.651378

**Full-support five-seed KC selection frequency** — 10 row(s)

,candidate_id,selected_conditions,selection_frequency,condition_ids
0,kc_feature__aspect__perfect,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."
1,kc_feature__aspect__perfect_progressive,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."
2,kc_feature__aspect__progressive,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."
3,kc_feature__clause__imperative,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."
4,kc_feature__clause__polar_question,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."
5,kc_feature__polarity__negative,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."
6,kc_feature__tense__past,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."
7,kc_feature__tense__present,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."
8,kc_feature__voice__passive,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."
9,kc_interaction__aspect_perfect__and__polarity_negative,5,1.0,"[""seed_20260827__learners_1000"", ""seed_20260828__learners_1000"", ""seed_20260829__learners_1000"", ""seed_20260830__lea..."

**Inventory Jaccard stability** — 6 row(s)

                      scope     inventory      mean  median   minimum
0            all_conditions  all_selected  0.959596     1.0  0.818182
1            all_conditions     additions  0.777778     1.0  0.000000
2  reference_nested_support  all_selected  0.927273     1.0  0.818182
3  reference_nested_support     additions  0.600000     1.0  0.000000
4    five_seed_full_support  all_selected  1.000000     1.0  1.000000
5    five_seed_full_support     additions  1.000000     1.0  1.000000

**Stability conclusions and leakage checks** — 1 row(s)

,reference_condition_id,conditions_matching_finalized_reference,full_support_seeds_matching_finalized_reference,all_conditions_identical,all_full_support_seeds_identical,holdout_events_supplied_to_any_selection,reserved_test_events_supplied_to_any_selection
0,seed_20260827__learners_1000,8,5,False,True,0,0

,reference_condition_id,conditions_matching_finalized_reference,full_support_seeds_matching_finalized_reference,all_conditions_identical,all_full_support_seeds_identical,holdout_events_supplied_to_any_selection,reserved_test_events_supplied_to_any_selection
0,seed_20260827__learners_1000,8,5,False,True,0,0

## Final result digest

This final table gathers the principal evidence and its claim boundary. It is a compact reading guide, not a replacement for the stage tables above.

In [17]:
automated_all_logistic = kt_metrics.query(
    "representation == 'automated' and technique == 'logistic' and grammar_regime == 'all_test'"
).iloc[0]
automated_vs_factorized = paired_rows.query(
    "grammar_regime == 'all_test' and reference == 'factorized' and candidate == 'automated'"
).iloc[0]
FINAL_DATASET_SUMMARY = {
    'dataset_id': finalization['dataset_id'],
    'source_descriptors': len(source_rows),
    'canonical_cells': len(canonical_cells),
    'generated_candidates': len(candidate_rows),
    'selected_items': len(selected_bank),
    'learners': events['learner_id'].nunique(),
    'events': len(events),
    'raw_KC_candidates': candidate_inventory['candidate_counts']['raw_total'],
    'selection_eligible_KC_candidates': candidate_inventory['candidate_counts']['selection_eligible'],
    'automatically_selected_KCs': len(selection_trace['selected_candidate_ids']),
}
final_digest = pd.DataFrame([
    {'stage': 'source → canonical', 'result': f"{len(source_rows)} descriptors; {int(mapping_rows['result'].eq('complete').sum())} complete mappings; {len(canonical_cells)} cells", 'claim boundary': 'retained English EGP sample and retained model normalisation'},
    {'stage': 'generation → fixed bank', 'result': f"{len(generation_attempts)} attempts; {len(candidate_rows)} payloads; {len(selected_bank)} selected items; {fold_assignments['cell_id'].nunique()}/{len(canonical_cells)} cells covered", 'claim boundary': 'model-generated and model-judged; packaging correction separately audited'},
    {'stage': 'grammar fold', 'result': '; '.join(f"{row.grammar_split}: {row.cells} cells / {row.selected_items} items" for row in fold_summary.itertuples()), 'claim boundary': 'semantic structural split, not outcome-optimized'},
    {'stage': 'KC candidates', 'result': f"{candidate_inventory['candidate_counts']['raw_total']} raw → {candidate_inventory['candidate_counts']['activation_equivalence_classes']} activation classes → {candidate_inventory['candidate_counts']['selection_eligible']} selection eligible", 'claim boundary': 'equivalence only on the development measurement bank'},
    {'stage': 'automated selection', 'result': f"{len(selection_trace['selected_candidate_ids'])} KCs: nine feature marginals + perfect×negative", 'claim boundary': 'selected on synthetic development learner evidence only'},
    {'stage': 'KT prediction', 'result': f"automated logistic test log loss {automated_all_logistic.log_loss:.6f}; Brier {automated_all_logistic.brier_score:.6f}", 'claim boundary': 'synthetic mixed latent world; observable logistic KT'},
    {'stage': 'paired KC comparison', 'result': f"automated−factorized Δ log loss {automated_vs_factorized.delta_log_loss:.6f} [{automated_vs_factorized.log_loss_CI_low:.6f}, {automated_vs_factorized.log_loss_CI_high:.6f}]", 'claim boundary': 'learner-cluster paired interval; negative favors automated'},
    {'stage': 'selection stability', 'result': f"{stability['exact_inventory_matches']['full_support_seeds_matching_finalized_reference']}/5 full-support seeds match exactly", 'claim boundary': 'one low-support prefix selects a different interaction'},
])
show_table('Machine-readable final counts', pd.DataFrame([FINAL_DATASET_SUMMARY]))
show_table('Evidence-backed final result digest', final_digest)

**Machine-readable final counts** — 1 row(s)

,dataset_id,source_descriptors,canonical_cells,generated_candidates,selected_items,learners,events,raw_KC_candidates,selection_eligible_KC_candidates,automatically_selected_KCs
0,grammar_kt_medium_v1,139,24,77,44,1000,204000,55,28,10

**Evidence-backed final result digest** — 8 row(s)

,stage,result,claim boundary
0,source → canonical,139 descriptors; 44 complete mappings; 24 cells,retained English EGP sample and retained model normalisation
1,generation → fixed bank,78 attempts; 77 payloads; 44 selected items; 24/24 cells covered,model-generated and model-judged; packaging correction separately audited
2,grammar fold,compositional_holdout: 5 cells / 10 items; development: 18 cells / 32 items; novel_feature_holdout: 1 cells / 2 items,"semantic structural split, not outcome-optimized"
3,KC candidates,55 raw → 38 activation classes → 28 selection eligible,equivalence only on the development measurement bank
4,automated selection,10 KCs: nine feature marginals + perfect×negative,selected on synthetic development learner evidence only
5,KT prediction,automated logistic test log loss 0.643356; Brier 0.225610,synthetic mixed latent world; observable logistic KT
6,paired KC comparison,"automated−factorized Δ log loss -0.000375 [-0.000631, -0.000109]",learner-cluster paired interval; negative favors automated
7,selection stability,5/5 full-support seeds match exactly,one low-support prefix selects a different interaction

,stage,result,claim boundary
0,source → canonical,139 descriptors; 44 complete mappings; 24 cells,retained English EGP sample and retained model normalisation
1,generation → fixed bank,78 attempts; 77 payloads; 44 selected items; 24/24 cells covered,model-generated and model-judged; packaging correction separately audited
2,grammar fold,compositional_holdout: 5 cells / 10 items; development: 18 cells / 32 items; novel_feature_holdout: 1 cells / 2 items,"semantic structural split, not outcome-optimized"
3,KC candidates,55 raw → 38 activation classes → 28 selection eligible,equivalence only on the development measurement bank
4,automated selection,10 KCs: nine feature marginals + perfect×negative,selected on synthetic development learner evidence only
5,KT prediction,automated logistic test log loss 0.643356; Brier 0.225610,synthetic mixed latent world; observable logistic KT
6,paired KC comparison,"automated−factorized Δ log loss -0.000375 [-0.000631, -0.000109]",learner-cluster paired interval; negative favors automated
7,selection stability,5/5 full-support seeds match exactly,one low-support prefix selects a different interaction